// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DynamicResourceService
    {
        public DynamicResourceService(System.ServiceModel.Channels.Binding binding) { }
        public string AddResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, string existingDynamicResourceXml) => throw null;
        public Agility.Sdk.Model.Resources.DynamicResourceInfo DeleteResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, string existingDynamicResourceXml) => throw null;
        public Agility.Sdk.Model.Resources.DynamicResourceInfo DeleteResources(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection, string existingDynamicXml) => throw null;
        public string AddResources(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection, string existingDynamicResourceXml) => throw null;
        public int GetNumberOfResources(string sessionId, string dynamicXml) => throw null;
        public string AddResourcesUsingJobRole(string sessionId, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string existingDynamicXml) => throw null;
    }
}
