// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ServerService
    {
        public ServerService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Server.ServerSettings GetServerSettings(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.ServerSettings2 GetServerSettings2(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.ServerSettings3 GetServerSettings3(string sessionId, short settingsSection) => throw null;
        public Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileIdentityCollection GetScanVrsProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Import.DocConversionProfileIdentityCollection GetDocConversionProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Import.DocConversionProfileSummaryCollection GetDocConversionProfileSummaries(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Import.DocumentConversionProfileAssociations GetDocumentConversionProfileAssociations(string sessionId, Agility.Sdk.Model.Capture.Import.DocumentConversionProfileIdentity profileIdentity) => throw null;
        public void DeleteDocConversionProfile(string sessionId, Agility.Sdk.Model.Capture.Import.DocumentConversionProfileIdentity identity, bool force) { }
        public Agility.Sdk.Model.Capture.PdfGeneration.PdfGenerationProfileIdentityCollection GetPdfProfileIdentities(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Separation.SeparationProfileIdentityCollection GetSeparationProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.Lookups.Lookup GetLookup(Agility.Sdk.Model.Lookups.LookupIdentity lookupIdentity) => throw null;
        public void AddLookup(string sessionId, Agility.Sdk.Model.Lookups.Lookup lookup) { }
        public void UpdateLookup(string sessionId, Agility.Sdk.Model.Lookups.Lookup lookup, bool overwrite) { }
        public Agility.Sdk.Model.Lookups.LookupSummaryCollection GetLookups(string sessionId, Agility.Sdk.Model.Lookups.LookupFilter lookupFilter) => throw null;
        public bool DeleteLookup(string sessionId, Agility.Sdk.Model.Lookups.LookupIdentity lookupIdentity) => throw null;
        public void AddTextCode(string sessionId, Agility.Sdk.Model.Server.TextCodes.TextCode textCode) { }
        public void UpdateTextCode(string sessionId, Agility.Sdk.Model.Server.TextCodes.TextCode textCode, bool overwrite) { }
        public Agility.Sdk.Model.Server.TextCodes.TextCodeCollection GetTextCodes(string sessionId, Agility.Sdk.Model.Server.TextCodes.TextCodeFilter textCodeFilter) => throw null;
        public Agility.Sdk.Model.Server.TextCodes.TextCode GetTextCode(string sessionId, string textCodeID) => throw null;
        public void DeleteTextCode(string sessionId, string textCodeID) { }
        public void AddCurrencyCode(string sessionId, Agility.Sdk.Model.CurrencyCodes.CurrencyCode currencyCode) { }
        public void UpdateCurrencyCode(string sessionId, Agility.Sdk.Model.CurrencyCodes.CurrencyCode currencyCode, bool overwrite) { }
        public Agility.Sdk.Model.CurrencyCodes.CurrencyCodeCollection GetCurrencyCodes(string sessionId) => throw null;
        public bool DeleteCurrencyCode(string sessionId, string currencyCode) => throw null;
        public void UpdateServerSettings(string sessionId, Agility.Sdk.Model.Server.ServerSettings serverSettingInformation) { }
        public void UpdateServerSettings2(string sessionId, Agility.Sdk.Model.Server.ServerSettings2 serverSettingInformation2) { }
        public void UpdateServerSettings3(string sessionId, Agility.Sdk.Model.Server.ServerSettings3 serverSettingInformation) { }
        public string UpdateServerSettings4(string sessionId, Agility.Sdk.Model.Server.ServerSettings3 serverSettingInformation, short settingsSection) => throw null;
        public Agility.Sdk.Model.Entities.EntityDefinition GetResourceEntityDefinition(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.CultureCollection GetCultures(string sessionId) => throw null;
        public string GetServerId(string sessionId) => throw null;
        public Agility.Sdk.Model.Processes.ProcessExceptionCollection GetExceptions(string sessionId, short exceptionFilter) => throw null;
        public void DeleteNavigationMenu(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenuIdentity navigationMenuIdentity, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) { }
        public void UpdateNavigationMenu(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenu navigationMenu, string newNavigationMenuId) { }
        public Agility.Sdk.Model.Navigation.NavigationMenuIdentity AddNavigationMenu(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenu navigationMenu) => throw null;
        public Agility.Sdk.Model.Navigation.NavigationControlCollection GetNavigationControls(string sessionId) => throw null;
        public Agility.Sdk.Model.Navigation.NavigationMenuIdentityCollection GetNavigationMenus(string sessionId, Agility.Sdk.Model.Forms.NavigationMenuFilter navigationMenuFilter) => throw null;
        public Agility.Sdk.Model.Navigation.NavigationMenu GetNavigationMenu(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenuIdentity navigationMenuIdentity) => throw null;
        public Agility.Sdk.Model.Variables.SessionVariableCollection GetSessionVariables(string sessionId, Agility.Sdk.Model.Variables.SessionVariableFilter sessionVariableFilter) => throw null;
        public void AddSessionVariable(string sessionId, Agility.Sdk.Model.Variables.SessionVariable sessionVariable) { }
        public void UpdateSessionVariable(string sessionId, Agility.Sdk.Model.Variables.SessionVariable sessionVariable) { }
        public void DeleteSessionVariable(string sessionId, Agility.Sdk.Model.Variables.SessionVariableIdentity sessionVariableIdentity) { }
        public void UpdateSkillLevels(string sessionId, Agility.Sdk.Model.Server.SkillLevelCollection skillLevelCollection, bool overwrite) { }
        public void DeleteResourceExtensionEntity(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity) { }
        public Agility.Sdk.Model.Server.RegularExpressionCollection GetRegularExpressions(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.RegularExpression2 GetRegularExpression(string sessionId, Agility.Sdk.Model.Server.RegularExpressionIdentity regularExpressionIdentity) => throw null;
        public Agility.Sdk.Model.Server.RegularExpression2Collection GetRegularExpressions2(string sessionId) => throw null;
        public void AddRegularExpression(string sessionId, Agility.Sdk.Model.Server.RegularExpression2 expressionToAdd) { }
        public void UpdateRegularExpression(string sessionId, Agility.Sdk.Model.Server.RegularExpression2 expressionToUpdate) { }
        public void DeleteRegularExpression(string sessionId, Agility.Sdk.Model.Server.RegularExpressionIdentity identity) { }
        public Agility.Sdk.Model.Variables.ConditionValidationResult ValidateConditionText(string sessionId, string conditionText, Agility.Sdk.Model.Variables.InputVariableCollection variables) => throw null;
        public Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleSummaryCollection GetWorkAllocationRules(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleFilter workAllocationFilter) => throw null;
        public void AddDASConnectionString(string sessionId, string connectionString) { }
        public void DeleteDASConnectionString(string sessionId, string connectionString) { }
        public void UpdateDASConnectionString(string sessionId, string connectionString, string oldConnectionString) { }
        public Agility.Sdk.Model.Server.StringCollection GetDASConnectionStrings(string sessionId) => throw null;
        public Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity AddJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobSchedule jobSchedule) => throw null;
        public Agility.Sdk.Model.BusinessCalendar.TimeCategoryCollection GetTimeCategories(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.SkillLevelCollection GetSkillLevels(string sessionId) => throw null;
        public Agility.Sdk.Model.Variables.VariableSummaryCollection GetServerVariables(string sessionId, Agility.Sdk.Model.Server.ServerVariablesFilter serverVariablesFilter) => throw null;
        public void DeleteJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity jobScheduleIdentity) { }
        public Agility.Sdk.Model.Server.SkillLevel GetSkillLevel(string sessionId, short skillLevel) => throw null;
        public Agility.Sdk.Model.Server.NoteTypeCollection GetNoteTypes(string sessionId) => throw null;
        public void RemoveAllAuditLogEntries(string sessionId) { }
        public void RemoveAllCompletedJobs(string sessionId) { }
        public void RemoveCompletedJobs(string sessionId, System.DateTime dateFrom, System.DateTime dateTo) { }
        public void RemoveAuditLogEntries(string sessionId, short auditType, System.DateTime fromDate, System.DateTime toDate) { }
        public Agility.Sdk.Model.Audit.AuditEntryCollection GetAuditEntries(string sessionId, Agility.Sdk.Model.Audit.AuditTypeCollection auditTypes, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public Agility.Sdk.Model.Audit.AuditTypeCollection GetAuditEntryTypes(string sessionId) => throw null;
        public void UpdateJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobSchedule jobSchedule) { }
        public void AddServerVariable(string sessionId, Agility.Sdk.Model.Variables.VariableSummary variableSummary) { }
        public void UpdateServerVariable(string sessionId, Agility.Sdk.Model.Variables.VariableSummary variableSummary) { }
        public void UpdateServerVariables(string sessionId, Agility.Sdk.Model.Variables.VariableValue2Collection updatedVariables) { }
        public void DeleteServerVariable(string sessionId, Agility.Sdk.Model.Variables.VariableSummary variableSummary) { }
        public Agility.Sdk.Model.JobSchedulers.JobScheduleSummaryCollection GetJobSchedules(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleFilter jobScheduleFilter) => throw null;
        public Agility.Sdk.Model.JobSchedulers.JobSchedule GetJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity jobScheduleIdentity) => throw null;
        public void AddNoteType(string sessionId, Agility.Sdk.Model.Server.NoteType noteType) { }
        public Agility.Sdk.Model.Component.DotNetComponent InterrogateDotNetComponent(string sessionId, Agility.Sdk.Model.Component.DotNetComponentIdentity componentIdentity) => throw null;
        public Agility.Sdk.Model.Component.DotNetMethod InterrogateDotNetMethod(string sessionId, Agility.Sdk.Model.Component.DotNetMethodIdentity dotNetMethodIdentity) => throw null;
        public Agility.Sdk.Model.Component.DotNetComponent VerifyDotNetComponent(string sessionId, Agility.Sdk.Model.Component.DotNetComponentIdentity componentIdentity) => throw null;
        public Agility.Sdk.Model.Server.StringCollection GetDotNetComponentClasses(string sessionId, Agility.Sdk.Model.Component.DotNetComponentIdentity dotNetComponentIdentity) => throw null;
        public Agility.Sdk.Model.References.DotNet.DotNetReferenceCollection GetDotNetReferences(string sessionId, Agility.Sdk.Model.References.DotNet.DotNetReferenceFilter dotNetReferenceFilter) => throw null;
        public Agility.Sdk.Model.Component.DotNetClass InterrogateDotNetClass(string sessionId, Agility.Sdk.Model.Component.DotNetClassIdentity dotNetClassIdentity) => throw null;
        public bool IsServerVariableInUse(string sessionId, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity) => throw null;
        public Agility.Sdk.Model.Variables.VariableAssociationCollection GetServerVariableAssociations(string sessionId, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity) => throw null;
        public Agility.Sdk.Model.Variables.SessionVariableAssociationCollection GetSessionVariableAssociations(string sessionId, Agility.Sdk.Model.Variables.SessionVariableIdentity sessionVariableIdentity) => throw null;
        public Agility.Sdk.Model.References.DotNet.DotNetReference GetDotNetReference(string sessionId, Agility.Sdk.Model.References.DotNet.DotNetReferenceIdentity referenceIdentity) => throw null;
        public void AddWebServiceReference(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReference webServiceReference) { }
        public void UpdateWebServiceReference(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReference webServiceReference, bool regenerateProxy) { }
        public void DeleteWebServiceReference(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReferenceIdentity webServiceReferenceIdentity) { }
        public Agility.Sdk.Model.References.WebServices.WebServiceReference GetWebServiceReference(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReferenceIdentity webServiceReferenceIdentity) => throw null;
        public Agility.Sdk.Model.References.WebServices.WebServiceReferenceCollection GetWebServiceReferences(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReferenceFilter webServiceReferenceFilter) => throw null;
        public void AddDotNetReference(string sessionId, Agility.Sdk.Model.References.DotNet.DotNetReference dotNetReference) { }
        public void UpdateDotNetReference(string sessionId, Agility.Sdk.Model.References.DotNet.DotNetReference reference, bool overwrite) { }
        public string GetProductDatabaseVersion(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.ProductVersionDetails GetProductVersionDetails(string sessionId) => throw null;
        public Agility.Sdk.Model.Processes.ThreadPoolCollection GetThreadPools(string sessionId) => throw null;
        public Agility.Sdk.Model.Scripting.ScriptingLanguageCollection GetScriptingLanguages(string sessionId, string scriptingEngineName) => throw null;
        public Agility.Sdk.Model.Server.ScriptingSettings GetScriptingSettings(string sessionId) => throw null;
        public void LockJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity jobScheduleIdentity) { }
        public void UnlockJobSchedule(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity jobScheduleIdentity, bool force) { }
        public short GetInstallationType(string sessionId) => throw null;
        public Agility.Sdk.Model.Search.SearchItemResultCollection SearchItems(string sessionId, Agility.Sdk.Model.Search.SearchItemsFilter filter) => throw null;
        public void AddWorkAllocationRule(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRule workAllocationRule) { }
        public void UpdateWorkAllocationRule(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRule workAllocationRule, bool overwrite) { }
        public void DeleteWorkAllocationRule(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleIdentity workAllocationRuleIdentity) { }
        public Agility.Sdk.Model.WorkAllocation.WorkAllocationRule GetWorkAllocationRule(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleIdentity workAllocationRuleIdentity) => throw null;
        public void DeleteDotNetReference(string sessionId, Agility.Sdk.Model.References.DotNet.DotNetReferenceIdentity reference) { }
        public Agility.Sdk.Model.Server.VBScriptValidationResult ValidateVBScript(string sessionId, string script) => throw null;
        public Agility.Sdk.Model.DotNetController.DotNetScriptValidationResult ValidateDotNetScript(string sessionId, Agility.Sdk.Model.DotNetController.DotNetScript script) => throw null;
        public Agility.Sdk.Model.DotNet.MethodInfo GetDotNetMethodInfo(string sessionId, Agility.Sdk.Model.Server.AddIn assemblyType, Agility.Sdk.Model.DotNet.MethodIdentity method) => throw null;
        public Agility.Sdk.Model.Server.LanguageCollection GetServerLanguages(string sessionId) => throw null;
        public Agility.Sdk.Model.License.ProductLicenseSettings GetProductLicenseSettings(string sessionId, string licenseKey, Agility.Sdk.Model.License.LicenseValidationOptions options) => throw null;
        public Agility.Sdk.Model.License.ProductLicenseSettings GetProductLicense(string sessionId) => throw null;
        public Agility.Sdk.Model.License.ProductLicenseSettings GetProductLicense2() => throw null;
        public Agility.Sdk.Model.License.LicenseServers GetProductLicenseServers(string sessionId) => throw null;
        public Agility.Sdk.Model.License.LicenseServers GetProductLicenseServers2() => throw null;
        public void UpdateProductLicenseServers(string sessionId, Agility.Sdk.Model.License.LicenseServers licenseServers) { }
        public void UpdateProductLicenseServers2(Agility.Sdk.Model.License.LicenseServers licenseServers) { }
        public Agility.Sdk.Model.License.ProductLicenses GetProductLicenses(string sessionId, Agility.Sdk.Model.License.LicenseServer licenseServer) => throw null;
        public bool IsWebServiceReferenceInUse(string sessionId, Agility.Sdk.Model.References.WebServices.WebServiceReferenceIdentity webServiceReferenceIdentity) => throw null;
        public byte[] ExportPackage(string sessionId, Agility.Sdk.Model.Package.PackageExportOptions options) => throw null;
        public void ImportPackage(Agility.Sdk.Model.Package.ImportPackageParameter importParameter) { }
        public Agility.Sdk.Model.Package.PackageInformation GetPackageInformation(string sessionId, byte[] packageData) => throw null;
        public Agility.Sdk.Model.Server.LoopOutput ExecuteLoop(string sessionId, object complexVariableValue, int numberOfColumns, double startIndex, Agility.Sdk.Model.Variables.ComplexVarColumnMappingCollection varMembers) => throw null;
        public void SendEmail(string sessionId, Agility.Sdk.Model.Email.EmailInfo emailInfo, string smtpServerName) { }
        public void SendEmail2(string sessionId, Agility.Sdk.Model.Email.EmailInfo2 emailInfo) { }
        public void SendEmail3(string sessionId, Agility.Sdk.Model.Email.EmailInfo3 emailInfo, string smtpServerName, Agility.Sdk.Model.Variables.InputVariableCollection inputVariables) { }
        public Agility.Sdk.Model.Variables.OutputVariableCollection ExecuteCalculationNode(string sessionId, Agility.Sdk.Model.Calculations.CalculationNode calculationNode) => throw null;
        public Agility.Sdk.Model.Variables.ConditionValidationResult ValidateCalculationNode(string sessionId, Agility.Sdk.Model.Calculations.CalculationNode calculationNode) => throw null;
        public Agility.Sdk.Model.Server.SLAStatusCollection GetSLAStatuses(string sessionId) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity IsJobScheduleLocked(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleIdentity scheduleIdentity) => throw null;
        public void DeleteNoteType(string sessionId, string noteTypeId) { }
        public void UpdateNoteType(string sessionId, Agility.Sdk.Model.Server.NoteType noteType) { }
        public void DeleteNotes(string sessionId, Agility.Sdk.Model.Server.StringCollection noteIds) { }
        public Agility.Sdk.Model.Server.LocalisationStringsCollection GetLocalisationStrings(string sessionId, Agility.Sdk.Model.Server.LocalisationIdentity localisationIdentity) => throw null;
        public void SaveLocalisationStrings(string sessionId, Agility.Sdk.Model.Server.LocalisationIdentity localisationIdentity, Agility.Sdk.Model.Server.LocalisationStringsCollection localisationStrings) { }
        public void SaveLocalisationStrings2(string sessionId, Agility.Sdk.Model.Server.LocalisationIdentity2 localisationIdentity, Agility.Sdk.Model.Server.LocalisationStringsCollection localisationStrings) { }
        public Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleImportErrorCollection ImportWorkAllocationRules(string sessionId, Agility.Sdk.Model.WorkAllocation.ExportedWorkAllocationRuleCollection workAllocationRulesToImport, bool overwrite) => throw null;
        public Agility.Sdk.Model.References.WebServices.RestfulServiceOutput ExecuteRestfulWebService(string sessionId, Agility.Sdk.Model.References.WebServices.RestfulService restfulService, Agility.Sdk.Model.References.WebServices.RestfulServiceInputCollection inputs, Agility.Sdk.Model.References.WebServices.RestfulServiceExpressionCollection expressions) => throw null;
        public Agility.Sdk.Model.Server.LocalisationStringsImportErrorCollection ImportLocalisationStrings(string sessionId, Agility.Sdk.Model.Server.ExportedLocalisationStringsCollection localisationStringsToImport) => throw null;
        public Agility.Sdk.Model.Server.LocalisationStringsImportErrorCollection ImportLocalisationStrings2(string sessionId, Agility.Sdk.Model.Server.ExportedLocalisationStringsCollection localisationStringsToImport, bool autoReleaseForms) => throw null;
        public Agility.Sdk.Model.Navigation.NavigationMenu2 GetNavigationMenu2(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenuIdentity navigationMenuIdentity) => throw null;
        public Agility.Sdk.Model.Navigation.NavigationMenuIdentity AddNavigationMenu2(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenu2 navigationMenu) => throw null;
        public void UpdateNavigationMenu2(string sessionId, Agility.Sdk.Model.Navigation.NavigationMenu2 navigationMenu, string newNavigationMenuId) { }
        public Agility.Sdk.Model.Server.WorkerTaskSummaryCollection GetSystemTasks(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.WorkerTaskSummary2Collection GetSystemTasks2(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.FailedNonSystemTasksCollection GetFailedNonSystemTasks(string sessionId) => throw null;
        public void ActivateFailedNonSystemTasks(string sessionId, Agility.Sdk.Model.Server.NonSystemTasksFilter nonSystemTasksFilter) { }
        public void DeleteFailedNonSystemWorkerTasks(string sessionId, Agility.Sdk.Model.Server.NonSystemTasksFilter nonSystemTasksFilter) { }
        public Agility.Sdk.Model.Server.SystemTaskSettings GetSystemTaskSettings(string sessionId, Agility.Sdk.Model.Server.WorkerTaskIdentity identity) => throw null;
        public void UpdateSystemTaskSettings(string sessionId, Agility.Sdk.Model.Server.WorkerTaskSummary systemTaskSettings) { }
        public void UpdateSystemTaskSettings2(string sessionId, Agility.Sdk.Model.Server.WorkerTaskSummary2 systemTaskSettings) { }
        public void UpdateFederatedAuthenticationSetting(string sessionId, bool useFederatedAuthentication) { }
        public Agility.Sdk.Model.Capture.Import.FaxUserCollection GetFaxUsers(string sessionId, Agility.Sdk.Model.Capture.Import.ImportFaxServer importFaxServer) => throw null;
        public void TestMailbox(string sessionId, Agility.Sdk.Model.Capture.Import.ImportSource importSource, Agility.Sdk.Model.Capture.Import.ImportConnectionSummary importConnectionSummary) { }
        public void TestArchivePath(string sessionId, string archivePath, Agility.Sdk.Model.Capture.Import.ImportConnectionSummary importConnectionSummary) { }
        public void TestImportConnection(string sessionId, Agility.Sdk.Model.Capture.Import.ImportConnection importConnection) { }
        public Agility.Sdk.Model.Capture.Import.ImportConnectionIdentity AddImportConnection(string sessionId, Agility.Sdk.Model.Capture.Import.ImportConnection importConnection) => throw null;
        public void DeleteImportConnection(string sessionId, Agility.Sdk.Model.Capture.Import.ImportConnectionIdentity importConnectionIdentity) { }
        public Agility.Sdk.Model.Capture.Import.ImportConnection GetImportConnection(string sessionId, Agility.Sdk.Model.Capture.Import.ImportConnectionIdentity identity) => throw null;
        public Agility.Sdk.Model.Capture.Import.ImportConnectionIdentityCollection GetImportConnections(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Import.ImportConnectionCollection GetImportConnections2(string sessionId) => throw null;
        public void UpdateImportConnection(string sessionId, Agility.Sdk.Model.Capture.Import.ImportConnection importConnection, bool overwrite) { }
        public void ActivateProductLicense(string sessionId, string activationCode, string serverName) { }
        public void ActivateProductLicense2(string activationCode, string serverName) { }
        public string GetProductLicenseActivationCode(string sessionId, string serialNumber, string productCode, string machineId) => throw null;
        public string GetMachineId(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.MachineCollection GetMachines(string sessionId) => throw null;
        public void ActivateProductLicenseAutomatically(string sessionId, string serialNumber, string productCode, string machineId, string serverName) { }
        public void ActivateProductLicenseAutomatically2(string serialNumber, string productCode, string machineId, string serverName) { }
        public byte[] ExportPackage2(string sessionId, Agility.Sdk.Model.Package.PackageExportOptions2 options) => throw null;
        public Agility.Sdk.Model.Package.PackageInformation2 GetPackageInformation2(string sessionId, byte[] packageData, bool isLegacy) => throw null;
        public Agility.Sdk.Model.Package.ImportPackageResult ImportPackage2(string sessionId, byte[] packageData, Agility.Sdk.Model.Package.PackageImportOptions2 importOptions) => throw null;
        public short GetVariableOwnerType(string sessionId, Agility.Sdk.Model.Variables.VariableIdentity2 variableIdentity) => throw null;
        public Agility.Sdk.Model.WorkAllocation.ExportedWorkAllocationRuleCollection ExportWorkAllocationRules(string sessionId, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleIdentityCollection workAllocationRuleIdentityCollection) => throw null;
        public Agility.Sdk.Model.Server.ExportedLocalisationStringsCollection ExportLocalisationStrings(string sessionId, Agility.Sdk.Model.Server.LocalisationIdentityCollection localisationIdentityCollection) => throw null;
        public void DeleteProtectedItem(string sessionId, Agility.Sdk.Model.Security.ProtectedItemSummary itemToDelete) { }
        public Agility.Sdk.Model.Security.ProtectedItemSummaryCollection GetProtectedItems(string sessionId, Agility.Sdk.Model.Security.ProtectedItemFilter protectedItemFilter) => throw null;
        public Agility.Sdk.Model.Package.ImportPackageResult ImportPackage3(string sessionId, byte[] packageData, Agility.Sdk.Model.Package.PackageImportOptions3 importOptions, short packageImportType) => throw null;
        public Agility.Sdk.Model.Package.ImportPackageInfo GetImportPackageData(string sessionId, byte[] packageData, short packageImportType) => throw null;
        public bool IsIntegrationServer(string sessionId) => throw null;
        public Agility.Sdk.Model.RetentionPolicy.RetentionPolicyFailureTypeCollection GetRetentionPolicyFailureTypes(string sessionId) => throw null;
        public Agility.Sdk.Model.RetentionPolicy.RetentionPolicyFailureCollection GetRetentionPolicyFailures(string sessionId, Agility.Sdk.Model.RetentionPolicy.RetentionPolicyFailureFilterCriteria filter) => throw null;
        public void ForceAllUsersToChangePasswordOnNextLogon(string sessionId) { }
        public Agility.Sdk.Model.Capture.PageRenditionCollection GetPageRenditions(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.ReportingTagCollection GetReportingTags(string sessionId) => throw null;
        public void SavePageRenditions(string sessionId, Agility.Sdk.Model.Capture.PageRenditionCollection pageRenditions) { }
        public void SaveReportingTags(string sessionId, Agility.Sdk.Model.Capture.ReportingTagCollection reportingTags) { }
        public Agility.Sdk.Model.Server.ServerSettingsSummary GetServerSettingsSummary(string sessionId) => throw null;
        public void GenerateNewSecurityKey(string sessionId) { }
        public Agility.Sdk.Model.Capture.ProjectIdentityCollection GetCaptureProjectsToPreload(string sessionId) => throw null;
        public Agility.Sdk.Model.Lookups.LookupCollection GetLookups2(Agility.Sdk.Model.Lookups.LookupIdentityCollection lookupIdentityCollection) => throw null;
        public Agility.Sdk.Model.Audit.AuditEntry2Collection GetAuditEntries2(string sessionId, Agility.Sdk.Model.Audit.AuditTypeCollection auditTypes, System.DateTime fromDate, System.DateTime toDate, short category, short level) => throw null;
        public Agility.Sdk.Model.Audit.AuditEntry2Collection GetAuditEntries3(string sessionId, Agility.Sdk.Model.Audit.AuditEntriesFilter filter) => throw null;
        public Agility.Sdk.Model.Audit.AuditCategorisations GetAuditCategorisations(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileCollection GetScanVrsProfilesConfiguration(string sessionId, Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileIdentityCollection vrsProfileIdentities) => throw null;
        public byte[] GetAssetData(string sessionId, string assetId) => throw null;
        public byte[] GetAssetDataByNameAndType(string sessionId, string assetName, short assetType) => throw null;
        public string AddAssetData2(string sessionId, string assetName, byte[] assetData, short assetType, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) => throw null;
        public string AddAssetData(string sessionId, string assetName, byte[] assetData) => throw null;
        public void DeleteAssetData(string sessionId, string assetId) { }
        public Agility.Sdk.Model.Capture.Import.LatestImportConnections GetLatestImportConnections(string sessionId) => throw null;
        public Agility.Sdk.Model.RecentItems.RecentItemCollection GetRecentItems(string sessionId, Agility.Sdk.Model.RecentItems.RecentItemFilter recentItemFilter) => throw null;
        public void DeleteRecentItems(string sessionId) { }
        public bool IsFeatureLicenseAvailable(string sessionId, int licenseId) => throw null;
        public void ExecuteAutoStoreNode(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, string documentId, string folderId, short fileType, bool submitRejectedDocuments) { }
        public Agility.Sdk.Model.Server.CaptureRepositoryConfiguration GetCaptureRepositoryConfiguration(string sessionId) => throw null;
        public Agility.Sdk.Model.Variables.VariableValue2 TestExpression(string sessionId, Agility.Sdk.Model.Variables.VariableValue3Collection inputVariables, string ruleText) => throw null;
        public Agility.Sdk.Model.Server.MachineServiceCollection GetMachineServices(string sessionId, Agility.Sdk.Model.Server.MachineServiceFilter machineServiceFilter) => throw null;
        public Agility.Sdk.Model.Server.StringCollection EncryptStrings(string sessionId, Agility.Sdk.Model.Server.StringCollection unencryptedData) => throw null;
        public Agility.Sdk.Model.Capture.Import.MessageConnectorPoolIdentityCollection GetMessageConnectorPoolIdentities(string sessionId) => throw null;
        public void SaveCustomSecurityStorageSettings(string sessionId, Agility.Sdk.Model.Server.CustomSecureStorageProcesses customSecureStorageProcesses) { }
        public string GetHelpURL(string sessionId) => throw null;
        public string GetKCMDesignerURL(string sessionId) => throw null;
    }
}
