// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CustomActivityTypeService
    {
        public CustomActivityTypeService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Activities.CustomServiceGroup AddCustomServiceGroup(string sessionId, Agility.Sdk.Model.Activities.CustomServiceGroup customServiceGroup) => throw null;
        public Agility.Sdk.Model.Activities.CustomServiceSummaryCollection GetCustomServices(string sessionId, Agility.Sdk.Model.Activities.CustomServiceFilter customServiceFilter) => throw null;
        public void DeleteCustomService(string sessionId, Agility.Sdk.Model.Activities.CustomServiceIdentity customServiceIdentity) { }
        public Agility.Sdk.Model.Activities.CustomService GetCustomService(string sessionId, Agility.Sdk.Model.Activities.CustomServiceIdentity customServiceIdentity) => throw null;
        public Agility.Sdk.Model.Activities.CustomServiceOutputCollection ExecuteCustomService(string sessionId, Agility.Sdk.Model.Activities.CustomServiceIdentity customServiceIdentity, Agility.Sdk.Model.Activities.CustomServiceInputCollection inputs) => throw null;
        public Agility.Sdk.Model.Activities.CustomServiceAssociations GetCustomServiceAssociations(string sessionId, Agility.Sdk.Model.Activities.CustomServiceIdentity customServiceIdentity) => throw null;
    }
}
