// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ManagementService
    {
        public ManagementService(System.ServiceModel.Channels.Binding binding) { }
        public void UpdateWorkerTaskHistoryRetention(string sessionId, short workerTaskType, long retentionPeriodInSeconds) { }
        public Agility.Sdk.Model.Management.WorkerTaskStats GetWorkerTaskStats(string sessionId, Agility.Sdk.Model.Management.WorkerTaskStatsFilter filter) => throw null;
        public Agility.Sdk.Model.Management.WorkerTaskDetailsCollection GetWorkerTasks(string sessionId, Agility.Sdk.Model.Management.WorkerTasksFilter filter) => throw null;
        public Agility.Sdk.Model.Management.ServiceProfileSummaryCollection GetServiceProfiles(string sessionId, Agility.Sdk.Model.Management.ServiceProfileFilter filter) => throw null;
        public Agility.Sdk.Model.Management.CoreWorkerServiceProfile GetCoreWorkerServiceProfile(string sessionId, Agility.Sdk.Model.Management.ServiceProfileIdentity identity) => throw null;
        public Agility.Sdk.Model.Management.ExportServiceProfile GetExportServiceProfile(string sessionId, Agility.Sdk.Model.Management.ServiceProfileIdentity identity) => throw null;
        public int GetServiceProfileRefreshInterval(string sessionId) => throw null;
        public void UpdateServiceProfileRefreshInterval(string sessionId, int serviceProfileRefreshInSeconds) { }
        public void DeleteServiceProfile(string sessionId, Agility.Sdk.Model.Management.ServiceProfileIdentity identity) { }
        public Agility.Sdk.Model.Management.ServiceProfileIdentity AddCoreWorkerServiceProfile(string sessionId, Agility.Sdk.Model.Management.CoreWorkerServiceProfile profile) => throw null;
        public void UpdateCoreWorkerServiceProfile(string sessionId, Agility.Sdk.Model.Management.CoreWorkerServiceProfile profile) { }
        public Agility.Sdk.Model.Management.ServiceProfileIdentity AddTransServerServiceProfile(string sessionId, Agility.Sdk.Model.Management.TransServerServiceProfile profile) => throw null;
        public Agility.Sdk.Model.Management.ServiceProfileIdentity AddExportServiceProfile(string sessionId, Agility.Sdk.Model.Management.ExportServiceProfile profile) => throw null;
        public Agility.Sdk.Model.Management.TransServerServiceProfile GetTransServerServiceProfile(string sessionId, Agility.Sdk.Model.Management.ServiceProfileIdentity identity) => throw null;
        public void UpdateTransServerServiceProfile(string sessionId, Agility.Sdk.Model.Management.TransServerServiceProfile profile) { }
        public void UpdateExportServiceProfile(string sessionId, Agility.Sdk.Model.Management.ExportServiceProfile profile) { }
        public long GetWorkerTaskHistoryRetention(string sessionId, short workerTaskType) => throw null;
        public void SaveMachineServiceProfiles(string sessionId, Agility.Sdk.Model.Management.MachineServiceProfileCollection profiles) { }
        public Agility.Sdk.Model.Management.MachineServiceProfileCollection GetMachineServiceProfiles(string sessionId, Agility.Sdk.Model.Management.MachineServiceProfileFilter filter) => throw null;
        public Agility.Sdk.Model.Management.MachineCoreWorkerServiceProfile GetMachineCoreWorkerServiceProfile(string sessionId, string machineName) => throw null;
        public Agility.Sdk.Model.Management.MachineTransServerServiceProfile GetMachineTransServerServiceProfile(string sessionId, string machineName) => throw null;
        public Agility.Sdk.Model.Management.MachineExportServiceProfile GetMachineExportServiceProfile(string sessionId, string machineName) => throw null;
    }
}
