// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ClientWindowsService
    {
        public ClientWindowsService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Client.ClientSession3 LogOnUsingWindowsAuthentication(short logOnProtocol, bool unconditionalLogOn, bool checkForSecureSession) => throw null;
        public Agility.Sdk.Model.Client.NgClientSession LogOnDesignerUsingWindowsAuthentication(short logOnProtocol, bool unconditionalLogOn, bool checkForSecureSession) => throw null;
    }
}
