// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class TagService
    {
        public TagService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Tags.TagIdentity SaveTag(string sessionId, Agility.Sdk.Model.Tags.Tag tag) => throw null;
        public Agility.Sdk.Model.Tags.TagCollection GetTags(string sessionId, Agility.Sdk.Model.Tags.TagFilter tagFilter) => throw null;
        public Agility.Sdk.Model.Tags.TagIdentityCollection GetTagsForItem(string sessionId, Agility.Sdk.Model.Tags.TagItemIdentity itemIdentity) => throw null;
        public void TagItem(string sessionId, Agility.Sdk.Model.Tags.TaggedItem taggedItem) { }
        public void UnTagItem(string sessionId, Agility.Sdk.Model.Tags.TaggedItem taggedItem) { }
        public void DeleteTag(string sessionId, Agility.Sdk.Model.Tags.TagIdentity tagIdentity) { }
        public Agility.Sdk.Model.Tags.TaggedItemCollection GetTaggedItems(string sessionId, Agility.Sdk.Model.Tags.TaggedItemFilter filter) => throw null;
    }
}
