// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class EntityService
    {
        public EntityService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Entities.EntityInstance GetEntityInstance(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceIdentity entityInstanceIdentity, bool performActions, string language) => throw null;
        public Agility.Sdk.Model.Entities.EntityInstanceIdentity GetEntityInstanceUsingKeyFields(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity, Agility.Sdk.Model.Entities.EntityInstanceFieldCollection keyFields) => throw null;
        public Agility.Sdk.Model.Entities.EntityInstanceSummaryCollection GetEntityInstancesUsingKeyFields(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity, Agility.Sdk.Model.Entities.EntityInstanceFieldCollection keyFields) => throw null;
        public void SetEntityInstanceFields(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceIdentity entityInstance, Agility.Sdk.Model.Entities.EntityInstanceFieldCollection requiredFields) { }
        public Agility.Sdk.Model.Entities.EntityInstanceFieldCollection GetEntityInstanceFields(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceIdentity entityInstance, Agility.Sdk.Model.Entities.EntityFieldIdentityCollection requiredFields) => throw null;
        public Agility.Sdk.Model.Entities.EntityDefinitionRelationships GetEntityDefinitionRelationships(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity) => throw null;
        public void DeleteEntityInstanceListItem(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceIdentity entityInstanceIdentity, Agility.Sdk.Model.Entities.EntityListIdentity entityListIdentity, Agility.Sdk.Model.Entities.EntityListItemAttributeCollection entityListItemAttributes) { }
        public Agility.Sdk.Model.Entities.EntityDefinitionIdentity AddEntityDefinition(string sessionId, Agility.Sdk.Model.Entities.EntityDefinition entityDefinition) => throw null;
        public void UpdateEntityDefinition(string sessionId, Agility.Sdk.Model.Entities.EntityDefinition entityDefinition, bool overwrite) { }
        public Agility.Sdk.Model.Entities.EntityDefinition GetEntityDefinition(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity, string language) => throw null;
        public bool DeleteEntityDefinition(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.Entities.EntityInstance AddEntityInstance(string sessionId, Agility.Sdk.Model.Entities.EntityInstance entityInstance) => throw null;
        public Agility.Sdk.Model.Entities.EntityInstanceCollection GetEntityInstances(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceFilter entityInstanceFilter) => throw null;
        public void DeleteEntityInstance(string sessionId, Agility.Sdk.Model.Entities.EntityInstanceIdentity entityInstanceIdentity) { }
        public Agility.Sdk.Model.Entities.EntityDefinitionIdentityCollection GetEntityDefinitions(string sessionId, Agility.Sdk.Model.Entities.EntityFilter entityFilter) => throw null;
        public void UpdateEntityInstance(string sessionId, Agility.Sdk.Model.Entities.EntityInstance entityInstance, bool overwrite) { }
        public Agility.Sdk.Model.Entities.EntityDefinitionCollection GetEntityDefinitionsList(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentityCollection entityDefinitionsIdentities) => throw null;
        public Agility.Sdk.Model.Entities.EntityInstanceIdentity AddEntityInstance2(string sessionId, Agility.Sdk.Model.Entities.EntityDefinitionIdentity entityDefinitionIdentity, Agility.Sdk.Model.Entities.EntityInstanceFieldCollection entityInstanceFields, string language) => throw null;
    }
}
