// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class WorkQueueDefinitionService
    {
        public WorkQueueDefinitionService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentityCollection GetWorkQueueDefinitions(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionFilter workQueueDefinitionFilter) => throw null;
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionFieldCollection GetFieldDetailsForDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinition GetWorkQueueDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinition GetWorkQueueDefinition2(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity, Agility.Sdk.Model.WorkQueueDefinitions.WorkTypeOptions workTypeOptions) => throw null;
        public void DeleteWorkQueueDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) { }
        public bool UpdateWorkQueueDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinition workQueueDefinition, bool overwrite) => throw null;
        public bool UpdateWorkQueueDefinition2(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinition workQueueDefinition, bool overwrite, Agility.Sdk.Model.WorkQueueDefinitions.UpdateWorkQueueDefinitionOptions updateOptions) => throw null;
        public void AddWorkQueueDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinition workQueueDefinition) { }
        public Agility.Sdk.Model.Processes.ProcessSummaryCollection GetWorkQueueDefinitionAssociatedProcesses(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) => throw null;
        public string GetWorkQueueMetadata(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity CopyWorkQueueDefinition(string sessionId, Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity workQueueDefinitionIdentity) => throw null;
    }
}
