// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class SourceControlService
    {
        public SourceControlService(System.ServiceModel.Channels.Binding binding) { }
        public void AddPackage(string sessionId, Agility.Sdk.Model.SourceControl.SourceControlItem item, Agility.Sdk.Model.SourceControl.AddPackageOptions addPackageOptions) { }
        public Agility.Sdk.Model.Server.StringCollection GetWorkingFolders(string sessionId) => throw null;
        public void CheckoutItem(string sessionId, Agility.Sdk.Model.SourceControl.SourceControlItem item, bool checkoutAssociatedItems) { }
        public void UndoCheckoutItem(string sessionId, Agility.Sdk.Model.SourceControl.SourceControlItem item, bool force) { }
        public void CheckinItem(string sessionId, Agility.Sdk.Model.SourceControl.SourceControlItem item, Agility.Sdk.Model.SourceControl.CheckinOptions checkinOptions) { }
    }
}
