// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class SigningService
    {
        public SigningService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.Softpro.SignDocTemplateIdentityCollection GetSignDocTemplates(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 signDocSite) => throw null;
        public Agility.Sdk.Model.Integration.Softpro.SignDocTemplateSettings GetSignDocTemplate(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 signDocSite, Agility.Sdk.Model.Integration.Softpro.SignDocTemplateIdentity templateIdentity) => throw null;
        public Agility.Sdk.Model.Integration.Softpro.SignDocTemplateSettings2 GetSignDocTemplate2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 signDocSite, Agility.Sdk.Model.Integration.Softpro.SignDocTemplateIdentity templateIdentity) => throw null;
        public Agility.Sdk.Model.Integration.Softpro.GeneratedDocumentTemplateSettings GetGeneratedDocumentTemplate(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 signDocSite, string documentTemplateName) => throw null;
        public Agility.Sdk.Model.Integration.Softpro.GeneratedDocumentTemplateSettings2 GetGeneratedDocumentTemplate2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 signDocSite, string documentTemplateName) => throw null;
        public void DeleteSigningPackage(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteDetails signDocSite, string packageId) { }
    }
}
