// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureProjectService
    {
        public CaptureProjectService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.VersionCollection GetProjectVersions(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) => throw null;
        public void SaveCaptureProject(Agility.Sdk.Model.Capture.ProjectData projectData) { }
        public void LockProject(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) { }
        public void UnlockProject(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) { }
        public void ForceUnlockProject(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) { }
        public void DeleteProject(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity, bool deletePreviousVersions) { }
        public Agility.Sdk.Model.Capture.DocumentGroupIdentity GetDocumentGroupIdentity(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeIdentity GetDocumentTypeIdentity(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity, string documentClassName) => throw null;
        public System.IO.Stream GetProjectFolderZip(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Capture.ProjectDefinition GetCaptureProject(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Capture.ProjectInfo GetProjectInformation(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Capture.ProjectInfoCollection GetProjectInformationCollection(string sessionId, bool getProjectDetails) => throw null;
        public void SaveTrainingSets(Agility.Sdk.Model.Capture.TrainingSetData trainingSetData) { }
        public void SaveBenchmarkSet(Agility.Sdk.Model.Capture.BenchmarkSetData benchmarkSetData) { }
        public System.IO.Stream GetTrainingSets(string sessionId, Agility.Sdk.Model.Capture.ProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Capture.ProjectIdentityCollection GetProjectsWithOnlineLearningEnabled(string sessionId) => throw null;
    }
}
