// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class QueryService
    {
        public QueryService(System.ServiceModel.Channels.Binding binding) { }
        public void AddQuery(string sessionId, Agility.Sdk.Model.Queries.Query query) { }
        public Agility.Sdk.Model.Queries.Query GetQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity) => throw null;
        public void UpdateQuery(string sessionId, Agility.Sdk.Model.Queries.Query query) { }
        public void DeleteQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity query) { }
        public Agility.Sdk.Model.Queries.QuerySummaryCollection GetQueries(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category, short queryType) => throw null;
        public Agility.Sdk.Model.Queries.QueryInfoCollection GetAllQueries(string sessionId, Agility.Sdk.Model.Queries.QuerySearchFilter querySearchFilter) => throw null;
        public void UpdateDefaultQuery(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Queries.QueryIdentity query) { }
        public Agility.Sdk.Model.Queries.Query GetDefaultQuery(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, short queryType) => throw null;
        public Agility.Sdk.Model.Server.NodeTypeCollection GetAllowedNodeTypes(string sessionId, short dynamicResourceFilterType) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentityCollection GetAssociatedForms(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity) => throw null;
    }
}
