// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DynamicsCrmIntegrationService
    {
        public DynamicsCrmIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public string ProcessCrmNode(string sessionId, Agility.Sdk.Model.Integration.CrmAction crmAction) => throw null;
        public Agility.Sdk.Model.Integration.CrmBusinessUnitCollection GetCrmBusinessUnits(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.CrmEntityCollection GetCrmEntities(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.CrmBusinessUnit businessUnit) => throw null;
        public Agility.Sdk.Model.Integration.CrmAttributeCollection GetCrmEntityAttributes(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.CrmBusinessUnit businessUnit, string entityName) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationRepositoryFolderCollection GetIntegrationRepositoryFolders(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.IntegrationRepositoryFolder repositoryFolder, bool getChildren) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationVariableCollection GetCrmRecord(string sessionId, Agility.Sdk.Model.Integration.CrmAction crmAction) => throw null;
        public Agility.Sdk.Model.Integration.CrmOrganisationCollection GetCrmOrganisations(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
    }
}
