// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class PersonaService
    {
        public PersonaService(System.ServiceModel.Channels.Binding binding) { }
        public void AddPersona(string sessionId, Agility.Sdk.Model.Personas.Persona persona) { }
        public Agility.Sdk.Model.Personas.Persona GetPersona(string sessionId, Agility.Sdk.Model.Personas.PersonaIdentity personaIdentity) => throw null;
        public void UpdatePersona(string sessionId, Agility.Sdk.Model.Personas.Persona persona) { }
        public void DeletePersona(string sessionId, Agility.Sdk.Model.Personas.PersonaIdentity persona) { }
        public Agility.Sdk.Model.Personas.PersonaCollection GetPersonas(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category) => throw null;
        public void UpdateGroupMembersWithPersona(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupResource, Agility.Sdk.Model.Personas.PersonaIdentity persona) { }
        public void RemoveGroupMembersPersona(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupResource) { }
        public void UpdateResourcePersona(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Personas.PersonaIdentity persona) { }
        public Agility.Sdk.Model.Personas.Persona GetResourcePersona(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource) => throw null;
    }
}
