// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ChecklistService
    {
        public ChecklistService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Checklists.ChecklistItemCollection GetChecklistItems(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItemFilter checklistItemFilter) => throw null;
        public Agility.Sdk.Model.Checklists.ChecklistItem GetChecklistItem(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItemIdentity checklistIdentity) => throw null;
        public Agility.Sdk.Model.Checklists.ChecklistTemplateCollection GetChecklistTemplates(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplateFilter checklistTemplateFilter) => throw null;
        public Agility.Sdk.Model.Checklists.ChecklistTemplate GetChecklistTemplate(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplateIdentity checklistTemplateIdentity) => throw null;
        public Agility.Sdk.Model.Variables.VariableSummaryCollection GetAllChecklistVariables(string sessionId) => throw null;
        public void AddChecklistItems(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItemCollection checklistItemCollection) { }
        public void AddChecklistTemplates(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplateCollection checklistTemplateCollection) { }
        public void AddChecklistItem(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItem checklistItem) { }
        public void AddChecklistTemplate(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplate checklistTemplate) { }
        public void UpdateChecklistTemplate(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplate checklistTemplate, bool overwrite) { }
        public void UpdateChecklistItem(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItem checklistItem, bool overwrite) { }
        public void DeleteChecklistItem(string sessionId, Agility.Sdk.Model.Checklists.ChecklistItemIdentity checklistItem) { }
        public void DeleteChecklistTemplate(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplateIdentity checklistItem) { }
        public bool IsChecklistTemplateInUse(string sessionId, Agility.Sdk.Model.Checklists.ChecklistTemplateIdentity checklistTemplate) => throw null;
        public void ReviewChecklistVariables(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.VariableIdentityCollection checklistVariables) { }
    }
}
