// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureKfsService
    {
        public CaptureKfsService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.Validation.FieldValidationResultCollection SaveChanges(string sessionId, Agility.Sdk.Model.Capture.CommonInfo commonInfo, Agility.Sdk.Model.Capture.KfsSaveChangesInputs inputs) => throw null;
        public Agility.Sdk.Model.Capture.KfsScanCreateNewJobOutputs ScanCreateNewJob(string sessionId, Agility.Sdk.Model.Capture.KfsScanCreateNewJobInputs kfsCreateNewJobInputs) => throw null;
        public void PerformDeviceSeparation(string sessionId, Agility.Sdk.Model.Capture.Scanning.ScanVrsProfile scanVrsProfile, Agility.Sdk.Model.Capture.Separation.SeparationProfile separationProfile, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity, string folderId) { }
    }
}
