// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CategoryService
    {
        public CategoryService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Categories.CategorySummaryCollection GetCategories(string sessionId, Agility.Sdk.Model.Categories.CategoryFilter categoryFilter) => throw null;
        public Agility.Sdk.Model.Categories.Category GetCategory(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) => throw null;
        public Agility.Sdk.Model.Categories.CategoryIdentity AddCategory(string sessionId, Agility.Sdk.Model.Categories.Category category) => throw null;
        public void UpdateCategory(string sessionId, Agility.Sdk.Model.Categories.Category category) { }
        public void DeleteCategory(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category) { }
        public Agility.Sdk.Model.Categories.CategorySummaryCollection GetImmediateSubcategories(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity parentCategoryIdentity) => throw null;
        public bool HasAccess(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category) => throw null;
        public Agility.Sdk.Model.Categories.CategoryAssociations GetCategoryAssociations(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) => throw null;
    }
}
