// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class BusinessEventService
    {
        public BusinessEventService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.BusinessEvents.EventDefinitionIdentity AddEventDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinition eventDefinition) => throw null;
        public void UpdateEventDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinition eventDefinition, bool overwrite) { }
        public void DeleteEventDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinitionIdentity eventDefinitionIdentity) { }
        public void DeleteEventDefinitions(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) { }
        public Agility.Sdk.Model.BusinessEvents.EventDefinitionSummaryCollection GetEventDefinitions(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinitionFilter eventDefinitionFilter) => throw null;
        public Agility.Sdk.Model.BusinessEvents.EventDefinition GetEventDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinitionIdentity eventDefinitionIdentity) => throw null;
        public bool DoesEventDefinitionExists(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinitionIdentity eventDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.BusinessEvents.AlertDefinitionIdentity AddAlertDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinition alertDefinition) => throw null;
        public void UpdateAlertDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinition alertDefinition, bool overwrite) { }
        public void DeleteAlertDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinitionIdentity alertDefinitionIdentity) { }
        public Agility.Sdk.Model.BusinessEvents.AlertDefinitionSummaryCollection GetAlertDefinitions(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinitionFilter alertDefinitionFilter) => throw null;
        public Agility.Sdk.Model.BusinessEvents.AlertDefinition GetAlertDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinitionIdentity alertDefinitionIdentity) => throw null;
        public bool DoesAlertDefinitionExists(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinitionIdentity alertDefinitionIdentity) => throw null;
        public Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity AddTargetDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinition targetDefinition) => throw null;
        public void UpdateTargetDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinition targetDefinition, bool overwrite) { }
        public void DeleteTargetDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity targetDefinitionIdentity) { }
        public void DeleteTargetDefinitions(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity) { }
        public Agility.Sdk.Model.BusinessEvents.TargetDefinitionSummaryCollection GetTargetDefinitions(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionFilter targetDefinitionFilter) => throw null;
        public Agility.Sdk.Model.BusinessEvents.TargetDefinition GetTargetDefinition(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity targetDefinitionIdentity) => throw null;
        public bool DoesTargetDefinitionExists(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity targetDefinitionIdentity) => throw null;
        public object GetTargetValue(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity targetDefinitionIdentity, short userFrequency) => throw null;
        public bool IsBusinessRuleInUse(string sessionId, Agility.Sdk.Model.BusinessRules.BusinessRuleIdentity businessRuleIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ImportErrorsInfo ImportBusinessEvents(string sessionId, Agility.Sdk.Model.BusinessEvents.ExportedEventCollection eventsToImport, bool overwrite) => throw null;
        public Agility.Sdk.Model.Processes.ImportErrorsInfo ImportBusinessAlerts(string sessionId, Agility.Sdk.Model.BusinessEvents.ExportedAlertCollection alertsToImport, bool overwrite) => throw null;
        public Agility.Sdk.Model.Processes.ImportErrorsInfo ImportBusinessTargets(string sessionId, Agility.Sdk.Model.BusinessEvents.ExportedTargetCollection targetsToImport, bool overwrite) => throw null;
        public Agility.Sdk.Model.BusinessEvents.ExportedTarget ExportBusinessTarget(string sessionId, Agility.Sdk.Model.BusinessEvents.TargetDefinitionIdentity targetToExport) => throw null;
        public Agility.Sdk.Model.BusinessEvents.ExportedEvent ExportBusinessEvent(string sessionId, Agility.Sdk.Model.BusinessEvents.EventDefinitionIdentity eventToExport) => throw null;
        public Agility.Sdk.Model.BusinessEvents.ExportedAlertCollection ExportBusinessAlerts(string sessionId, Agility.Sdk.Model.BusinessEvents.AlertDefinitionIdentityCollection alertsToExport, Agility.Sdk.Model.BusinessEvents.AlertExportOptions alertExportOptions) => throw null;
    }
}
