// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class IntegrationService
    {
        public IntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.MappedIntegrationEventCollection GetIntegrationEventMappings(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.MappedIntegrationEvent GetIntegrationEventMapping(string sessionId, Agility.Sdk.Model.Integration.IntegrationEventIdentity integrationEvent) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationSiteCollection GetIntegrationSites(string sessionId, Agility.Sdk.Model.Integration.IntegrationAddInIdentity addInEntity) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationSite GetIntegrationSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationSite GetIntegrationSite2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSite) => throw null;
        public bool IsIntegrationSiteInUse(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity) => throw null;
        public void UpdateIntegrationEventMapping(string sessionId, bool overwrite, Agility.Sdk.Model.Integration.MappedIntegrationEvent mappedIntegrationEvent) { }
        public Agility.Sdk.Model.Integration.IntegrationSiteIdentity AddIntegrationSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
        public void UpdateIntegrationSite(string sessionId, bool overwrite, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) { }
        public Agility.Sdk.Model.Integration.MappedIntegrationEventIdentity AddIntegrationEventMapping(string sessionId, Agility.Sdk.Model.Integration.MappedIntegrationEvent mappedIntegrationEvent) => throw null;
        public void DeleteIntegrationEventMapping(string sessionId, Agility.Sdk.Model.Integration.MappedIntegrationEvent mappedIntegrationEvent) { }
        public void DeleteIntegrationSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSite) { }
        public bool IsValidSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationEventCollection GetIntegrationEvents(string sessionId, Agility.Sdk.Model.Integration.IntegrationEventCategory eventCategory, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection GetIntegrationEventCategories(string sessionId, Agility.Sdk.Model.Integration.IntegrationEventCategory eventCategory, Agility.Sdk.Model.Integration.IntegrationSiteSummary integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationDataCollection GetIntegrationMetadata(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary integrationSite, Agility.Sdk.Model.Integration.IntegrationEventIdentity2 integrationEvent) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationSiteValidationResults ValidateIntegrationSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationAssociationCollection GetIntegrationAssociations(string sessionId, string siteName, short integrationType) => throw null;
    }
}
