// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocumentTypeVariantService
    {
        public DocumentTypeVariantService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.Variant.DocumentVariantInfo GetDocumentTypeVariant(string sessionId, string documentTypeId, string documentVariantName) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantIdentity AddDocumentTypeVariant(
            string sessionId,
            string documentTypeId,
            string documentVariantName,
            string description,
            System.DateTime? validFrom,
            Agility.Sdk.Model.Capture.Variant.VariantFieldSummaryCollection variantFields
            ) => throw null;
        public void DeleteDocumentTypeVariant(string sessionId, string documentTypeId, string documentVariantName, double version) { }
        public void UpdateDocumentTypeVariant(
            string sessionId,
            string documentTypeId,
            string documentVariantName,
            string newDocumentVariantName,
            string description,
            System.DateTime? validFrom,
            Agility.Sdk.Model.Capture.Variant.VariantFieldSummaryCollection variantFields
            ) { }
        public Agility.Sdk.Model.Capture.Variant.ActivityVariantInfo GetActivityVariant(string sessionId, string documentTypeId, string documentVariantName, string activityVariantName) => throw null;
        public Agility.Sdk.Model.Capture.Variant.ActivityVariantIdentity AddActivityVariant(string sessionId, string documentTypeId, string documentVariantName, string activityVariantName, Agility.Sdk.Model.Capture.Variant.VariantFieldSummaryCollection variantFields) => throw null;
        public void DeleteActivityVariant(string sessionId, string documentTypeId, string documentVariantName, string activityVariantName) { }
        public void UpdateActivityVariant(string sessionId, string documentTypeId, string documentVariantName, string activityVariantName, string newActivityVariantName, Agility.Sdk.Model.Capture.Variant.VariantFieldSummaryCollection variantFields) { }
        public Agility.Sdk.Model.Capture.Variant.VariantFieldIdentityCollection GetVisibleDocumentTypeFieldsForVariant(string sessionId, string docTypeId, string documentVariantName, double variantVersion) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantFieldIdentityCollection GetDocumentTypeFields(string sessionId, string docTypeId) => throw null;
    }
}
