// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class VirtualFolderService
    {
        public VirtualFolderService(System.ServiceModel.Channels.Binding binding) { }
        public void AddDocumentToVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, Agility.Sdk.Model.VirtualFolders.VirtualFolderDocument virtualFolderDocument) { }
        public void AddFolderToVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string existingFolderId, string newFolderName, bool raiseErrorIfExist) { }
        public void DeleteDocumentFromVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, string documentReference, bool raiseErrorIfDoesNotExist) { }
        public void DeleteFolderFromVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, bool raiseErrorIfDoesNotExist) { }
        public Agility.Sdk.Model.VirtualFolders.VirtualFolderContentCollection GetVirtualFolderContents(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, bool recursive, short contentToReturn) => throw null;
        public void UpdateDocumentInVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, Agility.Sdk.Model.VirtualFolders.VirtualFolderDocument virtualFolderDocument) { }
        public void RenameFolderInVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, string folderId, string newFolderName, bool raiseErrorIfDoesNotExist) { }
        public Agility.Sdk.Model.VirtualFolders.VirtualFolderContentCollection FindDocumentsInVirtualFolder(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, Agility.Sdk.Model.VirtualFolders.VirtualFolderDocumentFilter virtualFolderDocumentFilter) => throw null;
    }
}
