// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureSolutionService
    {
        public CaptureSolutionService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.CaptureSolutions.CaptureSolutionSummaryCollection GetCaptureSolutions(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionFilter captureSolutionFilter) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.CaptureSolution GetCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity identity) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.CaptureSolutionSummary SaveCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolution captureSolution) => throw null;
        public Agility.Sdk.Model.Assets.AssetIdentity CreateExportZip(string sessionId, string folderId) => throw null;
        public Agility.Sdk.Model.Assets.AssetIdentity CreateExportZip2(string sessionId, Agility.Sdk.Model.CaptureSolutions.ExportZipInput exportZipInput) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.CaptureSolutionPublishResult PublishCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity captureSolutionIdentity, Agility.Sdk.Model.CaptureSolutions.CaptureSolution captureSolution) => throw null;
        public void DeleteCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity captureSolutionIdentity, bool deleteAllVersions) { }
        public void LockCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity identity) { }
        public void UnlockCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity identity) { }
        public void ForceUnlockCaptureSolution(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity identity) { }
        public Agility.Sdk.Model.Server.StringCollection GetBarcodeTypes(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.StringCollection GetRecognitionLanguages(string sessionId) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Classification.ClassificationTrainingResultCollection AnalyzeClassificationTraining(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolution captureSolution) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.CaptureSolutionArtefacts GetAssociatedArtefacts(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolutionIdentity captureSolutionIdentity) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Extraction.ExtractionTrainingResultCollection TrainAndExtract(string sessionId, string captureProjectId, Agility.Sdk.Model.CaptureSolutions.DocumentTypeCollection documentTypes) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Extraction.ExtractionTrainingResultCollection TrainAndExtractWithSettings(string sessionId, string captureProjectId, Agility.Sdk.Model.CaptureSolutions.DocumentTypeCollection documentTypes, Agility.Sdk.Model.CaptureSolutions.ExtractionSettings settings) => throw null;
        public bool IsTransformationServerInstanceAvailable(string sessionId) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.PredefinedDocumentTypeCollection GetPredefinedDocumentTypes(string sessionId) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Classification.ClassificationTestResultCollection TestClassification(string sessionId, Agility.Sdk.Model.CaptureSolutions.CaptureSolution captureSolution, Agility.Sdk.Model.CaptureSolutions.CaptureDocumentCollection testDocuments) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Extraction.DocumentTrainAndExtractResultCollection TestExtraction(string sessionId, Agility.Sdk.Model.CaptureSolutions.DocumentType documentType, Agility.Sdk.Model.CaptureSolutions.CaptureDocumentCollection testDocuments) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Extraction.DocumentTrainAndExtractResultCollection TestExtractionWithSettings(string sessionId, Agility.Sdk.Model.CaptureSolutions.DocumentType documentType, Agility.Sdk.Model.CaptureSolutions.CaptureDocumentCollection testDocuments, Agility.Sdk.Model.CaptureSolutions.ExtractionSettings extractionSettings) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Extraction.DocumentTrainAndExtractResult DetectTables(string sessionId, string documentId) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.FuzzyLookup.RecordSet.FormattedRecordSet PreviewFuzzyLookupRecords(string sessionId, Agility.Sdk.Model.CaptureSolutions.FuzzyLookup.FuzzyLookupConfiguration configuration) => throw null;
    }
}
