// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class SharepointIntegrationService
    {
        public SharepointIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public string AddItem(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.IntegrationEventCategory integrationEventCategory, Agility.Sdk.Model.Integration.IntegrationDataCollection integrationDataCollection, string sourceDocFilePath, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection parentCategories, string relativePath, bool checkInDocument, bool declareAsRecord, bool isUniqueIdentifierMapped, bool online, bool overwrite) => throw null;
        public string UploadDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, string sourceDocFilePath, string targetDocUrl, string docContentType, bool declareAsRecord, bool isUniqueIdentifierMapped, bool online) => throw null;
        public string CreateSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, string webUrl, string title, string description, string template, bool useUniquePermissions, bool sharedNavigation, bool isAlreadyExists, bool isUniqueIdentifierMapped) => throw null;
        public string CreateFolder(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity, string relativeFolderUrl, string folderName, bool isAlreadyExists, bool isUniqueIdentifierMapped) => throw null;
        public string CreateFolder2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, string relativeFolderUrl, string folderName, bool isAlreadyExists, bool isUniqueIdentifierMapped) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationTemplateDataCollection GetTemplates(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary integrationSite) => throw null;
        public void GetDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite site, Agility.Sdk.Model.Integration.IntegrationEventCategory list, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection parentCategories, string relativePath, string documentName, string documentSavePath, bool checkout, string mappedGuid) { }
        public string GetDocument2(string sessionId, Agility.Sdk.Model.Integration.SharePoint.GetDocumentInput getDocumentInput) => throw null;
        public void DeleteItem(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.IntegrationEventCategory sharepointList, string itemName, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection parentCategories, string relativePath, string mappedGuid, bool deleteFolder) { }
        public void MoveItem(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.IntegrationDataCollection fields, Agility.Sdk.Model.Integration.IntegrationEventCategory integrationEventCategory, string relativePath, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection sourceCategories, Agility.Sdk.Model.Integration.IntegrationEventCategory targetIntegrationEventCategory, string targetRelativePath, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection targetCategories, string itemName, string mappedGuid, bool checkInDocument, bool declareAsRecord, bool overwrite) { }
        public void MoveItem2(string sessionId, Agility.Sdk.Model.Integration.SharePoint.SharepointMoveItemInput moveItemInput) { }
        public string UploadDocument2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.SourceDocument sourceDocument, string targetDocUrl, string docContentType, bool declareAsRecord, bool isUniqueIdentifierMapped, bool online) => throw null;
        public string AddItem2(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite, Agility.Sdk.Model.Integration.IntegrationEventCategory integrationEventCategory, Agility.Sdk.Model.Integration.IntegrationDataCollection integrationDataCollection, Agility.Sdk.Model.Integration.SourceDocument sourceDocument, Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection parentCategories, string relativePath, bool checkInDocument, bool declareAsRecord, bool isUniqueIdentifierMapped, bool online, bool overwrite) => throw null;
        public string AddItem3(string sessionId, Agility.Sdk.Model.Integration.SharePoint.SharepointAddItemInput addItemInput) => throw null;
        public string UploadDocument3(string sessionId, Agility.Sdk.Model.Integration.SharePoint.SharepointUploadDocumentInput uploadDocumentInput) => throw null;
        public Agility.Sdk.Model.Integration.SharePoint.RetentionLabelCollection GetRetentionLabels(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity) => throw null;
    }
}
