// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ResourceService
    {
        public ResourceService(System.ServiceModel.Channels.Binding binding) { }
        public string GetResourceName(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Categories.CategoryIdentity GetWorkingCategory(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetResources(string sessionId, Agility.Sdk.Model.Resources.ResourceFilter resourceFilter, Agility.Sdk.Model.Resources.ResourceIconSettings resourceIconSettings) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity4Collection GetResourceIdentities(string sessionId, Agility.Sdk.Model.Resources.ResourceFilter resourceFilter) => throw null;
        public Agility.Sdk.Model.Resources.WorkerResource GetWorkerResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.WorkerGroupResource GetWorkerGroupResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.WorkerGroupResource3 GetWorkerGroupResource2(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddWorkerResource(string sessionId, Agility.Sdk.Model.Resources.WorkerResource resource) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddWorkerGroupResource(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource resource) => throw null;
        public void UpdateWorkerResource(string sessionId, Agility.Sdk.Model.Resources.WorkerResource resource, bool overwrite) { }
        public void UpdateWorkerGroupResource(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource resource, bool overwrite) { }
        public void UpdateWorkerGroupResource2(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource2 resource, bool overwrite) { }
        public void UpdateWorkerGroupResource3(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource2 resource, Agility.Sdk.Model.Resources.ResourceIdentityCollection addMembers, Agility.Sdk.Model.Resources.ResourceIdentityCollection removeMembers, bool overwrite) { }
        public void UpdateExternalWorkerGroupResource(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource resource, bool overwrite) { }
        public void DeleteResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, bool checkMaps, bool overrideSupervisorCheck) { }
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetAssociatedGroups(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.SubordinateCollection GetSupervisors(string sessionId, Agility.Sdk.Model.Resources.SupervisorFilter supervisorFilter) => throw null;
        public Agility.Sdk.Model.Resources.SupervisorCollection GetSupervisors2(string sessionId, Agility.Sdk.Model.Resources.SupervisorFilter supervisorFilter) => throw null;
        public Agility.Sdk.Model.Categories.CategoryIdentity GetCategoryForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceSummary GetResourceSummary(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.WorkAllocation.WorkAllocationRule GetWorkAllocationRuleForGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupIdentity) => throw null;
        public void AssignWorkAllocationRuleToGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupIdentity, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleIdentity ruleIdentity) { }
        public Agility.Sdk.Model.Resources.ResourceIdentity AddCaseParticipant(string sessionId, Agility.Sdk.Model.Resources.WorkerResource resource) => throw null;
        public void UpdateCaseParticipant(string sessionId, Agility.Sdk.Model.Resources.WorkerResource resource) { }
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetResourcesUsingSearchCriteria(string sessionId, Agility.Sdk.Model.Resources.ResourceSearchFilter resourceSearchFilter) => throw null;
        public Agility.Sdk.Model.Resources.SubordinateCollection GetSubordinates(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Resources.SubordinateFilter subordinateFilter) => throw null;
        public Agility.Sdk.Model.Resources.SubordinateCollection GetSubordinateGroups(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupResource, bool recursiveGroups) => throw null;
        public void RemoveSubordinatesExclusionFromManualWorkAllocation(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public void DelegateFromTo(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity delegator, Agility.Sdk.Model.Resources.ResourceIdentity delegatee, Agility.Sdk.Model.Resources.DelegationOptions options) { }
        public void ExcludeFromManualWorkAllocation(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public System.DateTime GetFutureDateUsingWorkingTimeForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int days, int hours, int minutes, int seconds) => throw null;
        public System.DateTime GetFutureDateUsingWorkingDaysForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int days) => throw null;
        public System.DateTime GetFutureDateUsingWorkingHoursForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int hours) => throw null;
        public System.DateTime GetFutureDateUsingWorkingMinutesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int minutes) => throw null;
        public System.DateTime GetFutureDateUsingWorkingSecondsForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int seconds) => throw null;
        public System.DateTime GetPastDateUsingWorkingTimeForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int days, int hours, int minutes, int seconds) => throw null;
        public System.DateTime GetPastDateUsingWorkingDaysForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int days) => throw null;
        public System.DateTime GetPastDateUsingWorkingHoursForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int hours) => throw null;
        public System.DateTime GetPastDateUsingWorkingMinutesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int minutes) => throw null;
        public System.DateTime GetPastDateUsingWorkingSecondsForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, int seconds) => throw null;
        public int GetWorkingDaysBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, bool useOnLoanGroupResourceId, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupResourceIdentity) => throw null;
        public int GetWorkingHoursBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, bool useOnLoanGroupResourceId, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupResourceIdentity) => throw null;
        public int GetWorkingMinutesBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, bool useOnLoanGroupResourceId, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupResourceIdentity) => throw null;
        public int GetWorkingSecondsBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, bool useOnLoanGroupResourceId, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupResourceIdentity) => throw null;
        public int GetLoanedSecondsForResourceBetweenDates(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupIdentity) => throw null;
        public Agility.Sdk.Model.TimePeriod GetLoanedTimeForResourceBetweenDates(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime fromDate, System.DateTime toDate, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupIdentity) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingHoursBreakdownForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, int hours) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingMinutesBreakdownForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, int minutes) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingSecondsBreakdownForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, int seconds) => throw null;
        public bool IsWorkingDateTimeForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime dateToCheck) => throw null;
        public bool IsWorkingDayForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, System.DateTime dateToCheck) => throw null;
        public Agility.Sdk.Model.Server.SkillLevel GetSkillLevelOfResourceForProcess(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public bool RemoveSkillLevelForResourceAndProcess(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string comments) => throw null;
        public System.DateTime ApplySkillLevelToResourceAndProcess(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processId, Agility.Sdk.Model.Server.SkillLevel skillLevel, string comments, bool overwrite) => throw null;
        public Agility.Sdk.Model.Resources.ResourceProcessSkillLevelCollection GetResourceSkillLevelsForProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceProcessSkillLevelCollection GetProcessSkillLevelsForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.AvailableResources GetAvailableResourcesWithSkillLevelForActivities(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentityCollection activities, System.DateTime startDate, System.DateTime endDate) => throw null;
        public Agility.Sdk.Model.Resources.AvailableResources GetAvailableResourcesWithSkillLevelForActivities2(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentityCollection activities, System.DateTime startDate, System.DateTime endDate) => throw null;
        public Agility.Sdk.Model.Resources.ResourceAvailabilityCollection GetAvailableResourcesWithSkillLevelForProcess(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupResourceIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short skillLevel, System.DateTime startDate, System.DateTime endDate) => throw null;
        public void UpdateDelegation(string sessionId, Agility.Sdk.Model.Resources.DelegateInfo delegateInfo, bool overwrite) { }
        public void UnDelegate(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity delegator) { }
        public Agility.Sdk.Model.Resources.DelegateInfoCollection GetDelegations(string sessionId) => throw null;
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetMembersOfGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupResourceId, bool useManualWorkAllocationExclusion) => throw null;
        public Agility.Sdk.Model.Resources.ResourceOnLoanCollection GetResourcesOnLoanBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroup) => throw null;
        public Agility.Sdk.Model.Resources.NetTimeForResource GetNetTimeBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, int workloadInSeconds, System.DateTime fromDate, System.DateTime toDate, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroupIdentity) => throw null;
        public Agility.Sdk.Model.Resources.Delegate GetDelegation(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity delegatorResource) => throw null;
        public void AddWorkerGroupResourceMember(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupResource, Agility.Sdk.Model.Resources.ResourceIdentity memberResource) { }
        public bool DoesResourceExist(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity GetResourceIdFromResourceIdentity(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public string GetResourceEmailAddress(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity GetResourceSupervisor(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity GetResourceWorkingGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentityCollection GetAssociatedProcesses(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentityCollection GetRoleMembers(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity2Collection GetResourcesEmailAddresses(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentityCollection resources) => throw null;
        public void UpdateResourceSupervisor(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Resources.ResourceIdentity supervisorIdentity) { }
        public void UpdateResourceWorkingGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Resources.ResourceIdentity workingGroup) { }
        public void RemoveWorkAllocationRuleFromGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity groupIdentity, Agility.Sdk.Model.WorkAllocation.WorkAllocationRuleIdentity ruleIdentity) { }
        public Agility.Sdk.Model.Productivity.TeamProductivityInfo GetProductivityForTeamResources(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity team) => throw null;
        public string AddNote(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity ownerId, string subject, string noteText) => throw null;
        public Agility.Sdk.Model.Server.NoteCollection GetNotes(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity ownerId, Agility.Sdk.Model.Server.NoteFilter noteFilter) => throw null;
        public int GetResourceNoteCount(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity ownerId, short status) => throw null;
        public void UpdateNotesStatus(string sessionId, Agility.Sdk.Model.Resources.NoteIdentityCollection noteIdCollection, short status) { }
        public Agility.Sdk.Model.Resources.SkillLevelHistoryCollection GetSkillLevelHistory(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Resources.NetTimeForResource GetLoanedTimeForResourcesBetweenDates(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, int workloadInSeconds, System.DateTime fromDate, System.DateTime toDate, Agility.Sdk.Model.Resources.ResourceIdentity onLoanGroup) => throw null;
        public bool IsResourceInGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Resources.ResourceIdentity groupIdentity) => throw null;
        public Agility.Sdk.Model.Resources.LdapSynchronizationResult SynchronizeWithLdap(string sessionId, Agility.Sdk.Model.Resources.LdapSynchronizationSettings settings) => throw null;
        public Agility.Sdk.Model.Resources.LdapSynchonizationErrors ProcessLdapSynchronizationErrors(string sessionId, Agility.Sdk.Model.Resources.LdapSynchronizationData synchronizationData) => throw null;
        public void AddExternalWorkerGroupResource(string sessionId, Agility.Sdk.Model.Resources.WorkerGroupResource groupResource) { }
        public bool DoesResourceHaveDelegators(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity delegatee) => throw null;
        public bool DoesResourceHaveADelegatee(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity delegator) => throw null;
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetResources2(string sessionId, Agility.Sdk.Model.Resources.ResourceFilter2 resourceFilter, Agility.Sdk.Model.Resources.ResourceIconSettings resourceIconSettings) => throw null;
        public long GetNumberOfActivitiesAssignedToResource(string sessionId, Agility.Sdk.Model.Resources.ResourceActivityFilter resourceActivityFilter) => throw null;
        public void RemoveResourceFromGroup(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Resources.ResourceIdentity groupIdentity) { }
        public bool IsExcludedFromManualWorkAllocation(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public void RemoveExclusionFromManualWorkAllocation(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public Agility.Sdk.Model.Resources.SubordinateCollection GetSubordinates2(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Resources.SubordinateFilter2 subordinateFilter) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity GetResourceIdFromResourceIdentity2(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity2 resourceIdentity) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingTimeBetweenDatesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceTimeFilter resourceTimeFilter) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddCaseParticipant2(string sessionId, Agility.Sdk.Model.Resources.CaseParticipant caseParticipant) => throw null;
        public Agility.Sdk.Model.Resources.LdapResourceCollection GetFailedToSynchLdapResourcesFromXml(string sessionId, string errorsXml) => throw null;
        public void AddWorkerResource2(string sessionId, Agility.Sdk.Model.Resources.WorkerResource2 resource) { }
        public void UpdateWorkerResource2(string sessionId, Agility.Sdk.Model.Resources.WorkerResource2 resource, bool overwrite) { }
        public void UpdateWorkerResource3(string sessionId, Agility.Sdk.Model.Resources.WorkerResource2 resource, Agility.Sdk.Model.Resources.ResourceIdentityCollection addToGroups, Agility.Sdk.Model.Resources.ResourceIdentityCollection removeFromGroups, bool overwrite) { }
        public Agility.Sdk.Model.Resources.WorkerResource2 GetWorkerResource2(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource) => throw null;
        public void AddCaseParticipant3(string sessionId, Agility.Sdk.Model.Resources.CaseParticipant2 resource) { }
        public void UpdateCaseParticipant2(string sessionId, Agility.Sdk.Model.Resources.UpdatedCaseParticipant resource, bool overwrite) { }
        public Agility.Sdk.Model.Resources.CaseParticipant2 GetCaseParticipant(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddCaseParticipant4(string sessionId, Agility.Sdk.Model.Resources.CaseParticipant2 resource) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddWorkerResource3(string sessionId, Agility.Sdk.Model.Resources.WorkerResource2 resource) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity AddWorkerResource4(string sessionId, Agility.Sdk.Model.Resources.WorkerResource2 resource, Agility.Sdk.Model.Resources.ResourceIdentityCollection addToGroups) => throw null;
        public Agility.Sdk.Model.Resources.ResourceSummaryCollection GetGroupResourceMembers(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
    }
}
