// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class BusinessIntelligenceService
    {
        public BusinessIntelligenceService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Forms.InsightIdentityCollection GetViews(string sessionId) => throw null;
        public Agility.Sdk.Model.Forms.InsightIdentityCollection GetCharts(string sessionId) => throw null;
    }
}
