// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CCMIntegrationService
    {
        public CCMIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.CCM.CCMProjectIdentityCollection GetProjects(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary) => throw null;
        public void GetContract(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary) { }
        public bool IsDistributionEnabled(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary) => throw null;
        public string GetDataBackboneXSD(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMDataBackbone GetDataBackbone(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMProjectDataCollection GetDataBackboneForProjects(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentityCollection projects) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMDocumentPackTemplateIdentityCollection GetDocumentPackTemplates(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity, bool onDemandOnly) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMLetterbookIdentityCollection GetLetterbooks(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMPackTemplateData GetPackTemplateData(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity, Agility.Sdk.Model.Integration.CCM.CCMDocumentPackTemplateIdentity packIdentity) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMDocumentTemplateIdentityCollection GetDocumentTemplatesForProject(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity, bool onDemandOnly) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMDocumentTemplateIdentityCollection GetDocumentTemplatesForLetterbook(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity, Agility.Sdk.Model.Integration.CCM.CCMLetterbookIdentity letterbookIdentity) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMInteractiveSession StartInteractiveSession(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, Agility.Sdk.Model.Integration.CCM.CCMProjectIdentity projectIdentity, Agility.Sdk.Model.Integration.CCM.CCMTemplateIdentity templateIdentity, string dataBackboneXml, string trackingJobId, short modeOfOperation, string packId, Agility.Sdk.Model.Integration.CCM.CCMInteractiveSessionStartSettings startSettings) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMInteractiveSessionOutput CompleteInteractiveSession(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, Agility.Sdk.Model.Integration.CCM.CCMInteractiveSession interactiveSession, Agility.Sdk.Model.Integration.CCM.CCMDocumentFormConfigurationCollection documentsConfiguration, Agility.Sdk.Model.CCMDistributionType distributionType, Agility.Sdk.Model.Integration.CCM.OrganisationalMetaDataCollection organisationalMetaData, string trackingJobId, Agility.Sdk.Model.Integration.CCM.CCMInteractiveSessionSettings sessionSettings) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMDistributeActivityOutput ExecuteCCMDistributeActivity(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMDistributeActivityConfiguration distributeActivityConfiguration) => throw null;
        public string GetDesignerUrl(string sessionId, string userId) => throw null;
        public Agility.Sdk.Model.Integration.CCM.CCMComposeActivityOutput ExecuteCCMComposeActivity(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMComposeActivityConfiguration composeActivityConfiguration) => throw null;
        public void ExecuteCCMPackActivity(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 serverIdentity, Agility.Sdk.Model.Integration.CCM.CCMPackageActivityConfiguration packActivityConfiguration) { }
        public bool IsOutputManagementAvailable(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteSummary serverSummary) => throw null;
    }
}
