// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ProcessTestService
    {
        public ProcessTestService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Processes.Test.TestCaseIdentity SaveTestCase(string sessionId, Agility.Sdk.Model.Processes.Test.TestCase testCase) => throw null;
        public Agility.Sdk.Model.Processes.Test.TestCase GetTestCase(string sessionId, Agility.Sdk.Model.Processes.Test.TestCaseIdentity testCaseIdentity, Agility.Sdk.Model.Processes.Test.TestCaseOptions testCaseOptions) => throw null;
        public void SaveTestActivityConfigurations(string sessionId, Agility.Sdk.Model.Processes.Test.TestActivityConfigurationCollection testActivityConfigurations) { }
        public Agility.Sdk.Model.Processes.Test.TestActivityConfigurationCollection GetTestActivityConfigurations(string sessionId, Agility.Sdk.Model.Processes.Test.TestCaseIdentity testCaseIdentity, Agility.Sdk.Model.Nodes.ProcessNodeIdentity processNodeIdentity) => throw null;
        public Agility.Sdk.Model.Processes.Test.ProcessTestInitialization GetProcessTestInitialization(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void DeleteTestActivityConfiguration(string sessionId, Agility.Sdk.Model.Processes.Test.TestCaseIdentity testCaseIdentity, Agility.Sdk.Model.Nodes.ProcessNodeIdentity processNodeIdentity) { }
        public Agility.Sdk.Model.Processes.Test.TestCaseSummaryCollection GetTestPlanSummary(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void DeleteTestCase(string sessionId, Agility.Sdk.Model.Processes.Test.TestCaseIdentity testCaseIdentity) { }
        public Agility.Sdk.Model.Processes.Test.TestSuiteSummaryCollection GetTestSuitesSummary(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteFilter testSuiteFilter) => throw null;
        public void SaveTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuite testSuite) { }
        public Agility.Sdk.Model.Processes.Test.TestSuite GetTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity) => throw null;
        public void LockTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity) { }
        public void UnlockTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity, bool force) { }
        public Agility.Sdk.Model.Processes.Test.TestScriptActionResult ExecuteTestStep(string sessionId, Agility.Sdk.Model.Processes.Test.TestInputs testInputs) => throw null;
        public Agility.Sdk.Model.Processes.Test.ScriptStepIdentity AddScriptStep(string sessionId, Agility.Sdk.Model.Processes.Test.ScriptStep scriptStep) => throw null;
        public void UpdateScriptStep(string sessionId, Agility.Sdk.Model.Processes.Test.ScriptStep scriptStep) { }
        public void DeleteScriptStep(string sessionId, Agility.Sdk.Model.Processes.Test.ScriptStepIdentity stepIdentity) { }
        public Agility.Sdk.Model.Processes.Test.TestSuiteVersionCollection GetTestSuiteVersions(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity) => throw null;
        public void DeleteTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity) { }
        public Agility.Sdk.Model.Processes.Test.TestCaseIdentity CopyTestCase(string sessionId, Agility.Sdk.Model.Processes.Test.TestCaseIdentity testCaseIdentity) => throw null;
        public Agility.Sdk.Model.Processes.Test.TestPlanOutputCollection ExecuteTestPlan(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.Test.TestSuiteOutputCollection ExecuteTestSuite(string sessionId, Agility.Sdk.Model.Processes.Test.TestSuiteIdentity testSuiteIdentity) => throw null;
    }
}
