// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DataModelService
    {
        public DataModelService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Server.DataModel CreateDataModelFromJSON(string sessionId, string sampleJSON) => throw null;
        public Agility.Sdk.Model.Server.DataModelIdentity SaveDataModel(string sessionId, Agility.Sdk.Model.Server.DataModel dataModel, bool release) => throw null;
        public Agility.Sdk.Model.Server.DataModel GetDataModel(string sessionId, Agility.Sdk.Model.Server.DataModelIdentity dataModelIdentity) => throw null;
        public void LockDataModel(string sessionId, Agility.Sdk.Model.Server.DataModelIdentity dataModelIdentity) { }
        public void UnlockDataModel(string sessionId, Agility.Sdk.Model.Server.DataModelIdentity dataModelIdentity, bool force) { }
        public Agility.Sdk.Model.NameValuePairCollection UpdateDataObjectFormVariables(string sessionId, Agility.Sdk.Model.Forms.DataObjectFormVarsUpdate dataObjectFormVarsUpdate) => throw null;
        public Agility.Sdk.Model.NameValuePairCollection UpdateDataObjectFormVariables2(Agility.Sdk.Model.Forms.DataObjectFormVarsUpdate dataObjectFormVarsUpdate) => throw null;
    }
}
