// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ProcessService
    {
        public ProcessService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Processes.ProcessIdentity SaveProcess(string sessionId, Agility.Sdk.Model.Processes.Process process, Agility.Sdk.Model.Processes.SaveProcessOptions saveProcessOptions) => throw null;
        public Agility.Sdk.Model.Processes.SavedProcess SaveProcess2(string sessionId, Agility.Sdk.Model.Processes.Process process, Agility.Sdk.Model.Processes.SaveProcessOptions saveProcessOptions) => throw null;
        public Agility.Sdk.Model.Processes.Process GetProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessImportError ImportProcess(string sessionId, Agility.Sdk.Model.Processes.ExportedProcess processToImport, Agility.Sdk.Model.Processes.ProcessImportOptions importOptions) => throw null;
        public Agility.Sdk.Model.Processes.ProcessImportError2 ImportProcess2(string sessionId, Agility.Sdk.Model.Processes.ExportedProcess processToImport, Agility.Sdk.Model.Processes.ProcessImportOptions importOptions) => throw null;
        public Agility.Sdk.Model.Nodes.NodeSummaryCollection GetProcessNodes(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.States.StateIdentityCollection GetProcessStatesSummary(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessInfo GetProcessInfo(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processInfoFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummaryCollection GetRecentProcesses(string sessionId, Agility.Sdk.Model.Processes.RecentProcessFilter filter) => throw null;
        public string GetEmbeddedProcessViewerData(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short dataFormat, short testDebugMode) => throw null;
        public Agility.Sdk.Model.Milestones.MilestoneSummaryCollection GetProcessMilestones(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummaryCollection GetProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessFilter filter) => throw null;
        public Agility.Sdk.Model.States.StateIdentityCollection GetAllProcessStates(string sessionId) => throw null;
        public void DeleteSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) { }
        public Agility.Sdk.Model.Variables.VariableSummaryCollection GetSkinRuleVariables(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Skins.SkinSummary2Collection GetSkinsSummaryByTemplate(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Nodes.SkinNodeCollection GetSkinNodes(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) => throw null;
        public Agility.Sdk.Model.Variables.SkinVariableCollection GetSkinVariables(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummary GetProcessSummary(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummary4 GetProcessSummary2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessTemplate GetProcessTemplate(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Variables.VariableCollection GetProcessVariables(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Skins.SkinIdentity AddSkin(string sessionId, Agility.Sdk.Model.Skins.Skin skin) => throw null;
        public Agility.Sdk.Model.Skins.Skin GetSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessInitialization GetProcessInitialization(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessViewerData GetProcessViewerData(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public double GetLatestProcessVersion(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short status) => throw null;
        public void AddNode(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.ProcessNode newNodeInfo) { }
        public void AddNodes(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.ProcessNodeCollection newNodesInfo) { }
        public void DeleteNode(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.NodeIdentity2 nodeIdentity) { }
        public void DeleteNodes(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.NodeIdentity2Collection nodeNames) { }
        public void CreateProcess(string sessionId, Agility.Sdk.Model.Processes.CreateProcessInfo newMapInfo) { }
        public void CreateProcessBasedOnExisting(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity baseProcessIdentity, string processName) { }
        public Agility.Sdk.Model.Processes.ProcessIdentity AddAlertProcess(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category, string processName) => throw null;
        public Agility.Sdk.Model.Roles.RoleCollection GetProcessRoles(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Roles.RoleFilter roleFilter) => throw null;
        public Agility.Sdk.Model.Activities.ProcessActivitySummaryCollection GetActivitiesForProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessActivityFilter processActivityFilter) => throw null;
        public void DeleteProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) { }
        public Agility.Sdk.Model.Processes.SkillLevelProcessRatioCollection GetProcessSkillLevelRatios(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short ratioType) => throw null;
        public System.DateTime UpdateProcessSkillLevelRatios(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.SkillLevelProcessRatioCollection skillLevelProcessRatioCollection, bool overwrite) => throw null;
        public Agility.Sdk.Model.Processes.ProcessVersionCollection GetProcessVersions(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessVersionFilter processVersionFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessVersion2Collection GetProcessVersions2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessVersionFilter processVersionFilter) => throw null;
        public Agility.Sdk.Model.Activities.ActivitiesSummary GetActivitiesSummary(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentityCollection processActivityIdentityCollection) => throw null;
        public Agility.Sdk.Model.Processes.ProcessDependencies GetProcessDependencies(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public string GetProcessHelpText(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessType GetProcessType(string sessionId, string processId) => throw null;
        public short GetProcessPriority(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentity GetProcessIdentityForProcessName(string sessionId, string processName) => throw null;
        public string GetProcessNameForProcessIdentity(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessVariableAssociations GetProcessVariableAssociations(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string varId, bool isProcessEvent) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentity IsProcessLocked(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void LockProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) { }
        public void ReleaseProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) { }
        public bool DoesProcessUseDynamicServiceStandards(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public short GetProcessAccessPermission(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short accessType) => throw null;
        public Agility.Sdk.Model.Variables.SkinVariableCollection GetProcessTemplateSkinVariables(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skin) => throw null;
        public double GetLatestProcessTemplateVersion(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processTemplate) => throw null;
        public Agility.Sdk.Model.Skins.SkinIdentityCollection GetSkinVersions(string sessionId, Agility.Sdk.Model.Skins.SkinSummary skinSummary) => throw null;
        public Agility.Sdk.Model.Skins.SkinSummary2Collection GetSkinVersions2(string sessionId, Agility.Sdk.Model.Skins.SkinSummary skinSummary) => throw null;
        public Agility.Sdk.Model.Skins.SkinSummary2Collection GetSkins(string sessionId, Agility.Sdk.Model.Skins.SkinFilter skinFilter) => throw null;
        public string ExportSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinToExport) => throw null;
        public void DeleteSkins(string sessionId, Agility.Sdk.Model.Processes.ProcessTemplate processTemplate) { }
        public void UpdateProcessPriority(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short priority) { }
        public void UpdateProcessExpectedDuration(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Targets.Duration duration) { }
        public void UpdateProcessBudget(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.Budget budget) { }
        public void UpdateProcessExpectedCost(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, double expectedCost) { }
        public void UpdateActivityExpectedDueDate(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity processActivityIdentity, Agility.Sdk.Model.Targets.Duration duration) { }
        public void UpdateActivityPriority(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity activityIdentity, short priority) { }
        public void UpdateActivityExpectedDuration(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity activityIdentity, Agility.Sdk.Model.Targets.Duration duration) { }
        public void UpdateProcessActivityResources(string sessionId, Agility.Sdk.Model.Processes.Process businessProcess) { }
        public void UpdateActivityResources(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity processActivityIdentity, Agility.Sdk.Model.Resources.ActivityResources activityResources) { }
        public void AddProcessRoles(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Roles.RoleCollection roles) { }
        public Agility.Sdk.Model.Processes.ProcessPerformanceStats GetProcessPerformanceStats(string sessionId, Agility.Sdk.Model.Processes.ProcessPerformanceStatsFilter processPerformanceStatsFilter) => throw null;
        public void ReplaceProcessRoleMembers(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resources) { }
        public Agility.Sdk.Model.Processes.ProcessEventCollection GetProcessEvents(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentityCollection GetProcessTemplates(string sessionId, Agility.Sdk.Model.Processes.ProcessTemplateFilter filter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentityCollection GetCaseDefinitionAssociatedProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public bool CanCaseDefinitionBeCopied(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Events.EventAssociationCollection GetCaseProcessEventAssociations(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Milestones.MilestoneAssociationCollection GetCaseProcessMilestoneAssociations(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void UpdateRagForProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.RagStatus ragStatus) { }
        public string IsSkinLocked(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) => throw null;
        public void LockSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) { }
        public void UnlockSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity, bool force) { }
        public void UnlockProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Resources.ResourceIdentity lockResourceInfo, bool force) { }
        public bool IsSkinVariableInUse(string sessionId, Agility.Sdk.Model.Variables.VariableIdentity variable, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void ResetQualityCounts(string sessionId) { }
        public Agility.Sdk.Model.Processes.ProcessVersion2 RevertProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.RevertProcessOptions revertProcessOptions) => throw null;
        public Agility.Sdk.Model.Skins.SkinIdentity RevertSkin(string sessionId, Agility.Sdk.Model.Skins.SkinIdentity skinIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ImportProcessData GetImportProcessData(string sessionId, Agility.Sdk.Model.Processes.ExportedProcess processToImport) => throw null;
        public void ImportSkin(string sessionId, string skinXml) { }
        public Agility.Sdk.Model.Processes.DeleteProcessErrorCollection DeleteProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentityCollection processes) => throw null;
        public string GetLatestProcessName(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ExportedProcessCollection ExportProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processToExport, Agility.Sdk.Model.Processes.ProcessExportOptions exportOptions) => throw null;
        public Agility.Sdk.Model.Processes.ExportedProcessCollection ExportProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentityCollection processesToExport, Agility.Sdk.Model.Processes.ProcessExportOptions exportOptions) => throw null;
        public Agility.Sdk.Model.Processes.ProcessImportErrorCollection ImportProcesses(string sessionId, Agility.Sdk.Model.Processes.ExportedProcessCollection processesToImport, Agility.Sdk.Model.Processes.ProcessImportOptions importOptions) => throw null;
        public void UpdateActivitiesAssociatedFile(string sessionId, Agility.Sdk.Model.Processes.ProcessActivityAssociatedFileCollection processActivityAssociatedFiles) { }
        public void UpdateAssociatedFileForProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessAssociatedForm processAssociatedForm) { }
        public Agility.Sdk.Model.Processes.ExportedProcessDocument ExportProcessDocument(Agility.Sdk.Model.Processes.ProcessIdentityCollection processesToExport, Agility.Sdk.Model.Processes.ProcessDocumentExportOptions options) => throw null;
        public Agility.Sdk.Model.Processes.ProcessDocument GetProcessDocument(string sessionId, Agility.Sdk.Model.Processes.ProcessDocumentSettings processDocumentSettings) => throw null;
        public void RemoveProcessSkillLevelRatio(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short skillLevel, short ratioType) { }
        public Agility.Sdk.Model.Processes.ImportProcessDataCollection GetImportProcessesData(string sessionId, Agility.Sdk.Model.Processes.ExportedProcessCollection processesToImport) => throw null;
        public bool IsMilestoneInUse(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processType, Agility.Sdk.Model.Milestones.MilestoneIdentity milestoneIdentity) => throw null;
        public bool IsVariableInUse(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processType, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity) => throw null;
        public bool IsStateInUseAssociatedProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processType, Agility.Sdk.Model.States.StateIdentity stateIdentity) => throw null;
        public Agility.Sdk.Model.WorkQueueDefinitions.WorkQueueDefinitionIdentity GetProcessWorkQueueDefinition(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public bool IsRoleInUse(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processType, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessInitialization GetProcessInitialization2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessInitializationOptions initializationOptions) => throw null;
        public Agility.Sdk.Model.Variables.InputOutputVariables GetActivityInputsOutputs(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity processActivityIdentity) => throw null;
        public Agility.Sdk.Model.Processes.XpdlImportErrorCollection ImportXpdl(string sessionId, string xpdlToImport) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummary2Collection GetProcesses2(string sessionId, Agility.Sdk.Model.Processes.ProcessFilter2 processFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessCaptureRuntimeSettings GetProcessCaptureSettings(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.SkillLevelProcessRatio GetSkillLevelProcessRatio(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short skillLevel, short ratioType) => throw null;
        public Agility.Sdk.Model.Processes.ProcessImportErrorCollection ImportProcesses2(string sessionId, Agility.Sdk.Model.Processes.ExportedProcessData exportedProcessData, Agility.Sdk.Model.Processes.ProcessImportOptions2 importOptions) => throw null;
        public Agility.Sdk.Model.Activities.ActivityNotification GetActivityEmailSettings(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.NodeIdentity nodeIdentity) => throw null;
        public Agility.Sdk.Model.Activities.ProcessActivity2 GetActivityDetails(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.NodeIdentity nodeIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessInfo2 GetProcessInfo2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, short processInfoFilter) => throw null;
        public bool IsProcessInUseAsChildProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeCollection GetDocumentTypesForProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummary3Collection GetProcesses3(string sessionId, Agility.Sdk.Model.Processes.ProcessFilter4 processFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummary4Collection GetProcesses4(string sessionId, Agility.Sdk.Model.Processes.ProcessFilter4 processFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessNoteCollection GetProcessNotes(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void AddProcessNote(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessNote processNote) { }
        public void UpdateProcessNote(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Processes.ProcessNote processNote) { }
        public Agility.Sdk.Model.DocumentContainer.DocumentProcessRuleCollection GetDocumentProcessRules(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.PrecompileResults PrecompileSyncProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentityCollection syncProcesses) => throw null;
        public Agility.Sdk.Model.Processes.ProcessActivitiesCollection GetActivitiesForProcesses(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentityCollection identities) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentityCollection GetProcessesSummary(string sessionId, Agility.Sdk.Model.Processes.ProcessesSummaryFilter processesSummaryFilter) => throw null;
        public Agility.Sdk.Model.Variables.VariableAssociationCollection GetAssociatedServerVariables(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationSiteIdentity2Collection GetAssociatedIntegrations(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
    }
}
