// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class JobService
    {
        public JobService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Jobs.JobProperties GetMinJobDetails(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter filter, short maxWQFieldCount) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJob(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJobInCaseWithDocuments(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity caseProcessIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization) => throw null;
        public Agility.Sdk.Model.States.StateHistoryCollection GetStateChangeHistory(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public string GetJobState(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobProperties GetJobProperties(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter filter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentity GetJobProcessIdentity(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public void UpdateJobExpectedFinishTime(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, System.DateTime expectedFinishTime, bool resetException) { }
        public void AddJobNote(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Server.NoteInfo noteInfo) { }
        public void ReplaceJobRoleMembers(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resources) { }
        public void ReEvaluateSkin(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Skins.SkinEvaluationOptions skinOptions) { }
        public void SuspendJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobNote jobNote) { }
        public void TerminateJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public void ActivateJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public void HoldJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.OnHoldOptions onHoldOptions) { }
        public void HoldJob2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.OnHoldOptions2 onHoldOptions) { }
        public Agility.Sdk.Model.Processes.ProcessViewerData GetJobViewerData(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, bool associatedJobs) => throw null;
        public Agility.Sdk.Model.Processes.ProcessViewerData2 GetJobViewerData2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, bool associatedJobs) => throw null;
        public void UpgradeJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public void UpdateJobSpend(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, double value) { }
        public void UpdateJobNote(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, System.DateTime dateNoteEntered, Agility.Sdk.Model.Server.NoteInfo noteInfo) { }
        public void UpdateJobPriority(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, short jobPriority) { }
        public void UpdateJobOwners(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public void UpdateJobOwner(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Resources.ResourceIdentity jobOwner) { }
        public void RestartJob(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.ProcessActivityIdentityCollection embeddedProcessList, short restartType, Agility.Sdk.Model.Jobs.JobIdentity subJobIdentity) { }
        public void RaiseEvent(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string eventName, string eventSource, Agility.Sdk.Model.Variables.InputVariableCollection updatedVariables) { }
        public void RaiseAnonymousEvent(Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string eventName, string eventSource, Agility.Sdk.Model.Variables.InputVariableCollection updatedVariables) { }
        public Agility.Sdk.Model.Jobs.JobCountCollection GetJobCount(string sessionId, Agility.Sdk.Model.Jobs.JobCountFilter jobCountFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobCount2Collection GetJobCount2(string sessionId, Agility.Sdk.Model.Jobs.JobCountFilter jobCountFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobEventCollection GetJobEvents(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRoleCollection GetJobCaseRoles(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Variables.VariableValue GetJobVariableValue(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity) => throw null;
        public bool IsAccessPermitted(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, short accessType) => throw null;
        public Agility.Sdk.Model.Jobs.JobInfo GetJobInfo(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter filter) => throw null;
        public Agility.Sdk.Model.Jobs.SubJobIdentity GetSubJobId(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, short embeddedProcessCount) => throw null;
        public Agility.Sdk.Model.Jobs.JobHistoryCollection GetJobHistory(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, bool associatedJobs) => throw null;
        public Agility.Sdk.Model.Jobs.JobList GetJobs(string sessionId, Agility.Sdk.Model.Jobs.JobFilter jobFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobList GetJobs2(string sessionId, Agility.Sdk.Model.Jobs.JobFilter2 jobFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobList GetJobs3(string sessionId, Agility.Sdk.Model.Jobs.JobFilter3 jobFilter) => throw null;
        public Agility.Sdk.Model.Variables.JobVariableHistoryCollection GetJobVariableHistory(string sessionId, Agility.Sdk.Model.Nodes.JobNodeIdentity jobNodeIdentity, Agility.Sdk.Model.Variables.JobVariableHistoryFilter jobVariableHistoryFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobMilestoneCollection GetJobMilestones(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobNoteCollection GetJobNotes(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobNoteFilter jobNoteFilter) => throw null;
        public Agility.Sdk.Model.Roles.RoleCollection GetJobRoles(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public void AddRoleMember(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public void AddToNumericVarValue(string sessionId, Agility.Sdk.Model.Variables.VariableIdentity2 variableIdentity, object variableValueToAdd) { }
        public void DeleteJobNote(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, System.DateTime dateNoteEntered) { }
        public void DeleteRoleMember(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public void UpdateJobMilestoneTargetDate(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Milestones.MilestoneIdentity milestoneIdentity, System.DateTime newTargetDate) { }
        public void UpdateJobMilestoneActualDate(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Milestones.MilestoneIdentity milestoneIdentity, System.DateTime newActualDate) { }
        public void UpdateJobState(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string jobState) { }
        public void PurgeJobs(string sessionId, Agility.Sdk.Model.Jobs.PurgeJobsOptions options) { }
        public void PurgeJobsByID(string sessionId, Agility.Sdk.Model.Server.StringCollection jobIds) { }
        public string GetJobLanguage(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public string GetJobSource(string sessionId, string jobId) => throw null;
        public void UpdateJobLanguage(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string languageName) { }
        public void UpdateJobSource(string sessionId, string jobId, string jobSource) { }
        public void UpdateJobCustomerData(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, string customerData, Agility.Sdk.Model.Variables.OutputVariableCollection variables) { }
        public bool PerformSampling(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public bool PerformChecking(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public void RecoverJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public void RecoverJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection) { }
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJobInCase(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity caseProcessIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobMilestoneCollection GetUpdatedMilestones(string sessionId, System.DateTime lastUpdatedDateTime, short databaseConnectionType) => throw null;
        public void ResetJobVariables(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivity, Agility.Sdk.Model.Jobs.JobIdentity subJob, bool useLatestHistory, System.DateTime setTime) { }
        public void UpdateJobOwnerUsingSearchCriteria(string sessionId, Agility.Sdk.Model.Jobs.JobFilter jobFilter, Agility.Sdk.Model.Resources.ResourceIdentity jobOwner) { }
        public Agility.Sdk.Model.Variables.VariableValueCollection GetJobVariablesValues(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.VariableIdentityCollection variableIdentityCollection) => throw null;
        public Agility.Sdk.Model.Jobs.SubJobProperties GetSubJobProperties(string sessionId, Agility.Sdk.Model.Jobs.SubJobIdentity subJobIdentity, short jobDatabase) => throw null;
        public void UnHoldJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public void ActivateJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection) { }
        public void SuspendJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection, Agility.Sdk.Model.Jobs.JobNote jobNote) { }
        public void TerminateJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection) { }
        public void HoldJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection, Agility.Sdk.Model.Jobs.OnHoldOptions onHoldOptions) { }
        public void UnHoldJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobIdentityCollection) { }
        public Agility.Sdk.Model.Jobs.JobProgressOutput CreateJobAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization) => throw null;
        public void UpdateJobVariables(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.UpdatedVariableCollection updatedVariables) { }
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJobAndStartAt(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization, Agility.Sdk.Model.Activities.ProcessActivityIdentity processActivityIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJobUsingProcessType(string sessionId, short processType, string caseReference, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobInitialization2 jobInitialization) => throw null;
        public void ReevaluatePrecondition(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) { }
        public string GetSubJobViewerData(string sessionId, Agility.Sdk.Model.Jobs.SubJobIdentity subJobIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessViewerData2 GetSubJobViewerData3(string sessionId, Agility.Sdk.Model.Jobs.SubJobIdentity subJobIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, bool getSubJobProperties) => throw null;
        public int EvaluateScore(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity job) => throw null;
        public Agility.Sdk.Model.Jobs.SyncJob CreateJobSync(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole GetJobRole(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole2 GetJobRole2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole3 GetJobRole3(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public string CreateCustomProcessForJob(string sessionId, string jobId, string categoryName, string newProcessName) => throw null;
        public string UpgradeJobs(string sessionId, Agility.Sdk.Model.Jobs.JobIdentityCollection jobsToUpgrade) => throw null;
        public string UpgradeJobs2(string sessionId, Agility.Sdk.Model.Jobs.UpgradeJobFilter upgradeJobFilter) => throw null;
        public void UpgradeJobsAsync(string sessionId, Agility.Sdk.Model.Jobs.UpgradeJobFilter upgradeJobFilter) { }
        public Agility.Sdk.Model.Jobs.JobProgressOutput CreateJobInCaseAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobInitialization jobInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput CreateJobWithDocumentsAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput2 CreateJobWithDocumentsAndProgress2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput CreateJobInCaseWithDocumentsAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput2 CreateJobInCaseWithDocumentsAndProgress2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public Agility.Sdk.Model.Jobs.JobProperties2 GetJobProperties2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter filter) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateJobWithDocuments(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization jobWithDocsInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobHistoryCollection GetJobHistory2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter jobHistoryFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobsSummaryCollection GetJobsSummary(string sessionId, Agility.Sdk.Model.Jobs.JobSummaryFilter jobSummaryFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobsSummaryResults GetJobsSummaryWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobField groupByField) => throw null;
        public Agility.Sdk.Model.Processes.ProcessIdentity GetJobProcessIdentity2(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, short embeddedProcessCount) => throw null;
        public Agility.Sdk.Model.Jobs.JobExceptionSummaryCollection GetExceptionMaps(string sessionId, Agility.Sdk.Model.Jobs.JobExceptionFilter jobExceptionFilter) => throw null;
        public Agility.Sdk.Model.Variables.JobVariableCollection GetJobVariables(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobList GetJobs4(string sessionId, Agility.Sdk.Model.Jobs.JobFilter4 jobFilter) => throw null;
        public Agility.Sdk.Model.Queries.JobQueryResult GetJobsWithQuery(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobQueryFilter jobQueryFilter) => throw null;
        public Agility.Sdk.Model.Queries.JobQueryResult2 GetJobsWithQueryAndFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobFieldValue jobFieldValue) => throw null;
        public Agility.Sdk.Model.Queries.JobQueryResult2 GetJobsWithQueryAndMergedFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobFilterOverride jobFilterOverride) => throw null;
        public int GetJobsCountWithQueryAndMergedFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobFilterOverride jobFilterOverride) => throw null;
        public int GetJobsAggregateWithQueryAndMergedFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, short aggregateType, short aggregateStandardField, string aggregateMetadataField, Agility.Sdk.Model.Jobs.JobFilterOverride jobFilterOverride) => throw null;
        public Agility.Sdk.Model.Queries.JobQueryResult2 GetJobsWithQuery2(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobQueryFilter jobQueryFilter) => throw null;
        public int GetJobsCountWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobQueryFilter jobQueryFilter) => throw null;
        public int GetJobsAggregateWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobQueryFilter jobQueryFilter, short aggregateType, short aggregateStandardField, string aggregateMetadataField) => throw null;
        public Agility.Sdk.Model.Jobs.SyncJobWithDocuments CreateJobSyncWithDocuments(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentsInitialization2 jobWithDocsInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public Agility.Sdk.Model.Jobs.SyncJobWithDocument CreateJobSyncWithDocument(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Jobs.JobWithDocumentInitialization jobWithDocInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public void ArchiveJobs(string sessionId) { }
        public void SuspendJobs2(string sessionId, Agility.Sdk.Model.Jobs.SuspendJobsInfo suspendJobsInfo) { }
        public void SuspendJob2(string sessionId, Agility.Sdk.Model.Jobs.SuspendJobInfo suspendJobInfo) { }
        public void ActivateJobsWithSuspendReason(string sessionId, string suspendReason) { }
        public object UpdateJobComplexVariable(string sessionId, Agility.Sdk.Model.Variables.UpdateComplexVariableAction updateComplexVariableAction) => throw null;
        public Agility.Sdk.Model.Variables.ComplexVariableActionOutput GetJobComplexVariableRows(string sessionId, Agility.Sdk.Model.Variables.UpdateComplexVariableAction updateComplexVariableAction) => throw null;
        public Agility.Sdk.Model.Variables.ComplexVariableValueRowCollection GetJobComplexVariableForTable(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity) => throw null;
        public void UpdateJobComplexVariableFromTable(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.Variables.VariableIdentity variableIdentity, Agility.Sdk.Model.Variables.ComplexVariableValueRowCollection complexVariableRows) { }
        public object UpdateDataObjectListVariable(string sessionId, Agility.Sdk.Model.Variables.UpdateDataListVariableAction updateDataListVariableAction) => throw null;
        public Agility.Sdk.Model.Variables.DataListVariableActionOutput GetDataObjectListVariableRows(string sessionId, Agility.Sdk.Model.Variables.UpdateDataListVariableAction updateDataListVariableAction) => throw null;
        public Agility.Sdk.Model.Jobs.JobsSummaryResults GetJobsSummaryWithQueryAndMergedFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Jobs.JobField groupByField, Agility.Sdk.Model.Jobs.JobFilterOverride jobFilterOverride) => throw null;
    }
}
