// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class FormVariantService
    {
        public FormVariantService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Forms.FormVariants.FormElements GetFormElements(string sessionId, string formName) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantIdentity AddFormVariant(string sessionId, string formVariantName, string formName, string formVariantDescription, Agility.Sdk.Model.Forms.FormVariants.FormVariantElements formElements) => throw null;
        public void UpdateFormVariant(string sessionId, string formVariantName, string formName, string newFormVariantName, string formVariantDescription, Agility.Sdk.Model.Forms.FormVariants.FormVariantElements formElements) { }
        public void DeleteFormVariant(string sessionId, string formVariantName, string formName) { }
        public Agility.Sdk.Model.Capture.Variant.VariantSummaryCollection GetFormVariants(string sessionId, string formName) => throw null;
        public Agility.Sdk.Model.Forms.FormVariants.FormVariant GetFormVariant(string sessionId, string formVariantName, string formName) => throw null;
    }
}
