// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class SecurityService
    {
        public SecurityService(System.ServiceModel.Channels.Binding binding) { }
        public short GetACLPermission(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, short aclType) => throw null;
        public Agility.Sdk.Model.Security.SecurityRole GetSecurityRole(string sessionId, Agility.Sdk.Model.Security.SecurityRoleIdentity securityRoleIdentity) => throw null;
        public Agility.Sdk.Model.Security.SecurityToken GetSecurityToken(string sessionId, Agility.Sdk.Model.Security.SecurityTokenIdentity securityTokenIdentity) => throw null;
        public Agility.Sdk.Model.Security.SecurityTokenCollection GetSecurityTokens(string sessionId, Agility.Sdk.Model.Security.SecurityTokenFilter securityTokenFilter) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProvider GetAuthenticationProvider(string sessionId, Agility.Sdk.Model.Authentication.AuthenticationProviderIdentity authenticationProviderIdentity) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProviderIdentityCollection GetAuthenticationProvidersSummary(string sessionId) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProviderCollection GetAuthenticationProviders(string sessionId) => throw null;
        public Agility.Sdk.Model.Security.SecurityRoleCollection GetSecurityRoles(string sessionId, Agility.Sdk.Model.Security.SecurityRoleFilter securityRoleFilter) => throw null;
        public Agility.Sdk.Model.Security.SecurityRoleIdentity AddSecurityRole(string sessionId, Agility.Sdk.Model.Security.SecurityRole securityRole) => throw null;
        public Agility.Sdk.Model.Security.SecurityTokenIdentity AddSecurityToken(string sessionId, Agility.Sdk.Model.Security.SecurityToken securityToken) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProviderIdentity AddAuthenticationProvider(string sessionId, Agility.Sdk.Model.Authentication.AuthenticationProvider authenticationProvider) => throw null;
        public void DeleteSecurityRole(string sessionId, Agility.Sdk.Model.Security.SecurityRoleIdentity securityRoleIdentity) { }
        public void DeleteSecurityToken(string sessionId, Agility.Sdk.Model.Security.SecurityTokenIdentity securityTokenIdentity) { }
        public void DeleteAuthenticationProvider(string sessionId, Agility.Sdk.Model.Authentication.AuthenticationProviderIdentity authenticationProviderIdentity) { }
        public void UpdateSecurityRole(string sessionId, Agility.Sdk.Model.Security.SecurityRole securityRole) { }
        public void UpdateSecurityToken(string sessionId, Agility.Sdk.Model.Security.SecurityToken securityToken) { }
        public void UpdateAuthenticationProvider(string sessionId, Agility.Sdk.Model.Authentication.AuthenticationProvider authenticationProvider) { }
        public Agility.Sdk.Model.Resources.ResourceAclCollection GetResourceACLs(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public Agility.Sdk.Model.Resources.ResourceAclCollection GetACLInfo(string sessionId, short aclType) => throw null;
        public void SaveAclInfo(string sessionId, Agility.Sdk.Model.Resources.ResourceAclCollection aclInfo) { }
        public Agility.Sdk.Model.Security.SecurityTokenIdentityCollection GetSecurityTokensForResource(string sessionId) => throw null;
        public Agility.Sdk.Model.Resources.ResourceAclCollection GetCaptureACLInfo(string sessionId) => throw null;
        public Agility.Sdk.Model.Server.StringCollection EncryptStrings(string sessionId, Agility.Sdk.Model.Server.StringCollection unencryptedData) => throw null;
    }
}
