// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaseService
    {
        public CaseService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Jobs.JobMilestoneCollection GetCaseMilestones(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole GetCaseRole(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRoleCollection GetCaseRoles(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole2 GetCaseRole2(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobRole2Collection GetCaseRoles2(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void AddCaseRoleMember(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public Agility.Sdk.Model.Jobs.JobProperties GetCaseJobProperties(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobHistoryFilter filter) => throw null;
        public Agility.Sdk.Model.CaseProcesses.CaseSummary GetCaseSummary(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void AddCaseNote(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Server.NoteInfo noteInfo) { }
        public void AddLinkedCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity sourceCase, Agility.Sdk.Model.CaseProcesses.CaseIdentity targetCase, string linkDescription) { }
        public void AddRoleMember(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public void ChangeCaseState(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, string jobState) { }
        public Agility.Sdk.Model.Jobs.JobIdentity GetCaseId(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void DeleteLinkedCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity sourceCase, Agility.Sdk.Model.CaseProcesses.CaseIdentity targetCase) { }
        public Agility.Sdk.Model.CaseProcesses.LinkedCaseCollection GetLinkedCasesForCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void UpdateLinkedCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity sourceCase, Agility.Sdk.Model.CaseProcesses.CaseIdentity oldTargetCase, Agility.Sdk.Model.CaseProcesses.CaseIdentity newTargetCase, string linkDescription) { }
        public Agility.Sdk.Model.States.StateCollection GetCaseStates(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Variables.VariableAssociationCollection GetCaseVariableAssociations(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public bool DoesCaseExist(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobEventCollection GetCaseEvents(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void DeleteRoleMember(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public Agility.Sdk.Model.Jobs.JobNoteCollection GetCaseNotes(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.CaseProcesses.CaseNoteFilter caseNoteFilter) => throw null;
        public Agility.Sdk.Model.Jobs.JobInfoCollection GetJobsAssociatedWithCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void ReplaceRoleMembers(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Roles.RoleIdentity roleIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection) { }
        public void UpdateCaseSpend(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, double newSpendValue) { }
        public void UpdateCaseMilestoneTargetDate(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobMilestone jobMilestone) { }
        public void UpdateCaseMilestoneActualDate(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.JobMilestone jobMilestone, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) { }
        public Agility.Sdk.Model.Variables.VariableValueCollection GetCaseVariablesValues(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Variables.VariableIdentityCollection variableIdentityCollection) => throw null;
        public Agility.Sdk.Model.Jobs.JobHistoryCollection GetCaseHistory(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, bool associatedJobs) => throw null;
        public void CloseCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) { }
        public void PutCaseOnHold(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Jobs.OnHoldOptions onHoldOptions) { }
        public void ActivateCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, bool activateAllAssociatedJobs) { }
        public void SuspendCase(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, bool suspendAllAssociatedJobs) { }
        public void TakeCaseOffHold(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, bool takeOffHoldAllAssociatedJobs) { }
        public string CreateCase(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseInitialization caseInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateCaseWithDocuments(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseWithDocumentsInitialization caseWithDocumentsInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobIdentity CreateCase2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseInitialization caseInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobProgressOutput CreateCaseAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseInitialization caseInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput CreateCaseWithDocumentsAndProgress(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseWithDocumentsInitialization caseWithDocumentsInitialization) => throw null;
        public Agility.Sdk.Model.Jobs.JobWithDocumentsProgressOutput2 CreateCaseWithDocumentsAndProgress2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, string caseReference, Agility.Sdk.Model.CaseProcesses.CaseWithDocumentsInitialization caseWithDocumentsInitialization, Agility.Sdk.Model.Variables.VariableIdentityCollection variablesToReturn) => throw null;
        public void RaiseEvent(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, string eventName, string eventSource, Agility.Sdk.Model.Variables.InputVariableCollection updatedVariables) { }
        public void ForceValidCaseDocument(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, string comment) { }
        public void ReevaluateCaseDocumentRequiredDates(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) { }
        public bool ConfirmCaseDocument(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public void ReceivedCaseDocument(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentIdentity documentIdentity, bool useSource, string source, bool useStatus, short status) { }
        public Agility.Sdk.Model.Processes.ProcessIdentityCollection GetProcessesForCase(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public Agility.Sdk.Model.CaseProcesses.CaseIdentity GetCaseIdentity(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
        public void UpdateCaseReference(string sessionId, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, string newCaseReference) { }
    }
}
