// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class BusinessCalendarService
    {
        public BusinessCalendarService(System.ServiceModel.Channels.Binding binding) { }
        public System.DateTime GetFutureDateUsingWorkingTime(string sessionId, System.DateTime fromDate, int days, int hours, int minutes, int seconds) => throw null;
        public string GetFutureDateUsingWorkingDays2(string sessionId, int days) => throw null;
        public System.DateTime GetFutureDateUsingWorkingDays(string sessionId, System.DateTime fromDate, int days) => throw null;
        public System.DateTime GetFutureDateUsingWorkingHours(string sessionId, System.DateTime fromDate, int hours) => throw null;
        public System.DateTime GetFutureDateUsingWorkingMinutes(string sessionId, System.DateTime fromDate, int minutes) => throw null;
        public System.DateTime GetFutureDateUsingWorkingSeconds(string sessionId, System.DateTime fromDate, int seconds) => throw null;
        public System.DateTime GetPastDateUsingWorkingTime(string sessionId, System.DateTime fromDate, int days, int hours, int minutes, int seconds) => throw null;
        public System.DateTime GetPastDateUsingWorkingDays(string sessionId, System.DateTime fromDate, int days) => throw null;
        public System.DateTime GetPastDateUsingWorkingHours(string sessionId, System.DateTime fromDate, int hours) => throw null;
        public System.DateTime GetPastDateUsingWorkingMinutes(string sessionId, System.DateTime fromDate, int minutes) => throw null;
        public System.DateTime GetPastDateUsingWorkingSeconds(string sessionId, System.DateTime fromDate, int seconds) => throw null;
        public int GetWorkingDaysBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public int GetWorkingHoursBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public int GetWorkingMinutesBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public int GetWorkingSecondsBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingHoursBreakdown(string sessionId, int hours) => throw null;
        public bool GetUseBusinessCalendar(string sessionId) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingMinutesBreakdown(string sessionId, int minutes) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingSecondsBreakdown(string sessionId, int seconds) => throw null;
        public bool IsWorkingDateTime(string sessionId, System.DateTime dateToCheck) => throw null;
        public bool IsWorkingDay(string sessionId, System.DateTime dateToCheck) => throw null;
        public Agility.Sdk.Model.TimePeriod GetHoursBreakdown(string sessionId, int hours) => throw null;
        public Agility.Sdk.Model.TimePeriod GetMinutesBreakdown(string sessionId, int minutes) => throw null;
        public Agility.Sdk.Model.TimePeriod GetSecondsBreakdown(string sessionId, int seconds) => throw null;
        public string GetBusinessCalendarDataAsXml(string sessionId, short calendarYear) => throw null;
        public string GetBusinessCalendarDataAsXmlForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, short calendarYear) => throw null;
        public string ExportBusinessCalendarDataAsXml(string sessionId) => throw null;
        public string UpdateBusinessCalendarDataFromXml(string sessionId, short calendarYear, string xml) => throw null;
        public string ImportBusinessCalendarDataFromXml(string sessionId, string xml) => throw null;
        public System.DateTime UpdateBusinessCalendarDataFromXmlForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, short calendarYear, bool overwrite, System.DateTime lastModifiedDate, string xml) => throw null;
        public void AddTimeCategory(string sessionId, Agility.Sdk.Model.BusinessCalendar.TimeCategory timeCategory) { }
        public Agility.Sdk.Model.BusinessCalendar.TimeCategory AddTimeCategory2(string sessionId, Agility.Sdk.Model.BusinessCalendar.TimeCategory timeCategory) => throw null;
        public void UpdateTimeCategory(string sessionId, Agility.Sdk.Model.BusinessCalendar.TimeCategory timeCategory, bool overwrite) { }
        public void DeleteTimeCategory(string sessionId, Agility.Sdk.Model.BusinessCalendars.TimeCategoryIdentity timeCategoryIdentity) { }
        public Agility.Sdk.Model.Resources.WorkPatternAuditLogEntryCollection GetWorkPatternAuditLog(string sessionId, Agility.Sdk.Model.Resources.WorkPatternAuditLogFilter workPatternAuditLogFilter) => throw null;
        public Agility.Sdk.Model.Resources.CalendarAuditLogEntryCollection GetCalendarAuditLog(string sessionId, Agility.Sdk.Model.Resources.CalendarAuditLogFilter calendarAuditLogFilter) => throw null;
        public Agility.Sdk.Model.BusinessCalendar.TimeCategory GetTimeCategory(string sessionId, Agility.Sdk.Model.BusinessCalendars.TimeCategoryIdentity timeCategoryIdentity) => throw null;
        public Agility.Sdk.Model.TimePeriod GetWorkingTimeBetweenDates(string sessionId, System.DateTime fromDate, System.DateTime toDate) => throw null;
        public Agility.Sdk.Model.Resources.WorkPatternIdentityCollection GetWorkPatternsForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
    }
}
