// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ActivityService
    {
        public ActivityService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Activities.JobActivityInfo GetJobActivityInfo(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, string simulationId) => throw null;
        public Agility.Sdk.Model.Activities.LockedActivityCollection LockActivities(string sessionId, Agility.Sdk.Model.Activities.LockActivitiesFilter activityFilter) => throw null;
        public Agility.Sdk.Model.Activities.ActivitySettings GetCaptureActivitySettings(string sessionId, Agility.Sdk.Model.Activities.ProcessActivityIdentity activityIdentity) => throw null;
        public void UnlockActivities(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentityCollection activitiesToUnlock) { }
        public Agility.Sdk.Model.Activities.WorkQueue GetWorkQueue(string sessionId, Agility.Sdk.Model.Activities.JobActivityFilter jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Activities.JobActivity TakeActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) => throw null;
        public void CompleteActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityOutput jobActivityOutput) { }
        public void CompleteActivityWithDocuments(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityWithDocumentsOutput jobActivityWithDocumentsOutput) { }
        public void CancelActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) { }
        public void UpdateActivityPriority(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, short activityPriority) { }
        public void UpdateActivityDueDate(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, System.DateTime dueDate, bool resetException) { }
        public void ReassignActivity(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity originalResource, Agility.Sdk.Model.Resources.ResourceIdentity newResource, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) { }
        public void AllocateActivity(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) { }
        public void AllocateActivities(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Activities.JobActivityIdentityCollection activities) { }
        public Agility.Sdk.Model.Activities.ActivityList GetActivities(string sessionId, Agility.Sdk.Model.Activities.JobActivityFilter2 jobActivityFilter) => throw null;
        public string GetLiveUsableResourceEmailAddresses(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, short sendTo) => throw null;
        public void ReassignActivities(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity originalResource, Agility.Sdk.Model.Resources.ResourceIdentity newResource, Agility.Sdk.Model.Activities.JobActivityIdentityCollection jobActivityIdentities) { }
        public void UpdateActivityResources(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection) { }
        public Agility.Sdk.Model.Activities.JobActivityInfoCollection GetAllTakenActivities(string sessionId) => throw null;
        public int GetNumberOfActivities(string sessionId, Agility.Sdk.Model.Activities.JobActivityCountFilter jobActivityCountFilter) => throw null;
        public Agility.Sdk.Model.TimePeriod GetExpectedDurationForActivities(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentityCollection jobActivityIdentityCollection) => throw null;
        public Agility.Sdk.Model.Activities.WorkQueueOverview GetWorkQueueOverview(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource, Agility.Sdk.Model.Activities.WorkQueueOverviewFilter activityFilter) => throw null;
        public Agility.Sdk.Model.Activities.JobActivityInfoCollection GetActivitiesInJobWithStatus(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, short liveActivityStatus) => throw null;
        public void SaveActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityOutput jobActivityOutput) { }
        public Agility.Sdk.Model.Jobs.JobHistoryCollection GetCompletedActivitiesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Activities.CompletedActivitiesFilter activitiesFilter) => throw null;
        public void ReassignAllActivities(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity originalResource, Agility.Sdk.Model.Resources.ResourceIdentity newResource) { }
        public int GetAssignedActivityCountForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity, Agility.Sdk.Model.Activities.ActivityCountFilter activityCountFilter) => throw null;
        public void ResetTakenActivitiesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resource) { }
        public void CompletePendingActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityOutput jobActivityOutput) { }
        public Agility.Sdk.Model.Activities.JobActivity TakeActivityFromJob(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Activities.JobActivity TakeAnyActivity(string sessionId) => throw null;
        public Agility.Sdk.Model.Activities.JobActivityInfoCollection GetTakenActivitiesForResource(string sessionId, Agility.Sdk.Model.Resources.ResourceIdentity resourceIdentity) => throw null;
        public void CreateAdhocActivity(string sessionId, Agility.Sdk.Model.Activities.AdhocActivity adhocActivity) { }
        public void PerformAutoWorkAllocation(string sessionId, Agility.Sdk.Model.WorkAllocation.AutoWorkAllocationOptions filter) { }
        public void AddActivityResources(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection) { }
        public void DeleteActivityResources(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Resources.ResourceIdentityCollection resourceIdentityCollection) { }
        public Agility.Sdk.Model.Resources.ResourceIdentityCollection GetActivityUsableResources(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobProgressOutput CompleteActivityAndProgress(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityOutput jobActivityOutput) => throw null;
        public Agility.Sdk.Model.Jobs.JobProgressOutput CompleteActivityWithDocumentsAndProgress(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityWithDocumentsOutput jobActivityWithDocumentsOutput) => throw null;
        public Agility.Sdk.Model.Activities.WorkSummary GetWorkSummary(string sessionId, Agility.Sdk.Model.Activities.WorkSummaryFilter filter) => throw null;
        public void CreateAlertActivity(string sessionId, Agility.Sdk.Model.Activities.AlertActivity alertActivity) { }
        public void ResetTakenActivities(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentityCollection activitiesToReset) { }
        public Agility.Sdk.Model.Activities.NextActivity TakeNextActivity2(string sessionId, Agility.Sdk.Model.Activities.TakeNextActivityFilter filter) => throw null;
        public Agility.Sdk.Model.Activities.NextActivity TakeNextActivity(string sessionId, bool useCombinedWorkQueue) => throw null;
        public void CompletePendingActivityWithDocuments(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityWithDocumentsOutput jobActivityWithDocumentsOutput) { }
        public Agility.Sdk.Model.Activities.WorkQueue2 GetWorkQueue2(string sessionId, Agility.Sdk.Model.Activities.JobActivityFilter3 jobActivityFilter) => throw null;
        public void PartiallyCompleteActivity(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, Agility.Sdk.Model.Activities.JobActivityOutput jobActivityOutput) { }
        public Agility.Sdk.Model.Activities.JobActivityInfo2 GetJobActivityInfo2(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity2 jobActivityIdentity, string simulationId) => throw null;
        public Agility.Sdk.Model.Activities.ActivityList GetActivities2(string sessionId, Agility.Sdk.Model.Activities.JobActivityFilter3 jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Activities.JobActivitiesSummaryCollection GetActivitiesSummary(string sessionId, Agility.Sdk.Model.Activities.JobActivitySummaryFilter activitySummaryFilter) => throw null;
        public Agility.Sdk.Model.Activities.ActivityNotification GetActivityEmailSettings(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Nodes.NodeIdentity nodeIdentity, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.Activities.JobActivityInfo3 GetJobActivityInfo3(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity2 jobActivityIdentity) => throw null;
        public Agility.Sdk.Model.Queries.WorkQueueQueryResult GetWorkQueueWithQuery(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Queries.WorkQueueQueryResult2 GetWorkQueueWithQuery2(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Queries.ActivityQueryResult GetActivitiesWithQuery(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Queries.ActivityQueryResult2 GetActivitiesWithQueryAndFilter(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.ActivityFieldValue activityFieldValue) => throw null;
        public Agility.Sdk.Model.Queries.ActivityQueryResult2 GetActivitiesWithQuery2(string sessionId, bool useDefaultQuery, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public int GetActivitiesCountWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public int GetWorkQueueCountWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.JobActivityQueryFilter jobActivityFilter) => throw null;
        public Agility.Sdk.Model.Activities.JobActivityInfo4 GetJobActivityInfo4(string sessionId, Agility.Sdk.Model.Activities.JobActivityIdentity2 jobActivityIdentity) => throw null;
        public Agility.Sdk.Model.Activities.ActivitiesSummaryResults GetActivitiesSummaryWithQuery(string sessionId, Agility.Sdk.Model.Queries.QueryIdentity queryIdentity, Agility.Sdk.Model.Activities.ActivityField groupByField) => throw null;
    }
}
