// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocumentSetService
    {
        public DocumentSetService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.DocumentSet.JobDocumentSet GetJobDocumentSet(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.DocumentSet.JobDocumentSetStatus AddJobDocument(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.DocumentSet.JobDocument jobDocument) => throw null;
        public Agility.Sdk.Model.DocumentSet.JobDocumentSetStatus AddDocumentToDocumentSet(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.DocumentSet.DocumentSetDocument documentSetDocument) => throw null;
        public Agility.Sdk.Model.DocumentSet.JobDocumentSetStatus EvaluateJobDocumentSet(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public Agility.Sdk.Model.DocumentSet.JobDocumentSetStatus RemoveJobDocument(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.DocumentSet.JobDocumentIdentity jobDocumentIdentity) => throw null;
        public Agility.Sdk.Model.DocumentSet.JobDocumentSetStatus UpdateJobDocumentFields(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.DocumentSet.JobDocumentIdentity jobDocumentIdentity, Agility.Sdk.Model.DocumentSet.DocumentSetDocTypeFieldCollection fields) => throw null;
    }
}
