// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class KapowIntegrationService
    {
        public KapowIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.KapowProjectIdentityCollection GetProjects(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity siteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.KapowRobotIdentityCollection GetRobots(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity siteIdentity, Agility.Sdk.Model.Integration.KapowProjectIdentity projectIdentity) => throw null;
        public Agility.Sdk.Model.Component.DotNetMethod InterrogateRobotComponentMethod(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity siteIdentity, Agility.Sdk.Model.Integration.KapowRobotIdentity robotIdentity) => throw null;
    }
}
