// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class FormService
    {
        public FormService(System.ServiceModel.Channels.Binding binding) { }
        public double GetLatestFormVersion(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.Form GetForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentity GetFormIdentity(string sessionId, string formName) => throw null;
        public string GetFormVariantJSFileName(Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity, Agility.Sdk.Model.Forms.RuntimeFormIdentity runtimeFormIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantSummaryCollection GetFormVariants(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormVariants.FormVariant GetFormVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormVariants.FormElements2 GetFormElements(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantIdentity SaveFormVariant(string sessionId, Agility.Sdk.Model.Forms.FormVariants.FormVariant formVariant) => throw null;
        public void DeleteFormVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) { }
        public void LockFormVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) { }
        public Agility.Sdk.Model.Forms.FormVariants.FormVariant CopyFormVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public void UnlockFormVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity, bool force) { }
        public Agility.Sdk.Model.Resources.ResourceIdentity IsFormVariantLocked(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormTemplate GetFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity) => throw null;
        public Agility.Sdk.Model.Forms.SavedForm SaveForm(string sessionId, Agility.Sdk.Model.Forms.Form form) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentityCollection GetRecentForms(string sessionId, int numberOfForms) => throw null;
        public Agility.Sdk.Model.Forms.RecentFormCollection GetRecentForms2(string sessionId, int numberOfForms) => throw null;
        public Agility.Sdk.Model.Forms.RecentForm2Collection GetRecentForms3(string sessionId, int numberOfForms) => throw null;
        public void DeleteForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) { }
        public void DeleteFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity) { }
        public Agility.Sdk.Model.Forms.Events.EventOutputDataCollection ExecuteFormEvents(Agility.Sdk.Model.Forms.FormIdentity formIdentity, string methodName, Agility.Sdk.Model.Forms.Events.EventInputDataCollection eventsToExecute, string locale, string locale2, bool isMobile) => throw null;
        public Agility.Sdk.Model.Forms.FormSummary2Collection GetForms(string sessionId, Agility.Sdk.Model.Forms.FormFilter formFilter) => throw null;
        public Agility.Sdk.Model.Forms.RuntimeFormSummary GetRuntimeFormSummary(string sessionId, Agility.Sdk.Model.Forms.RuntimeFormIdentity runtimeFormIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentityCollection GetFormVersions(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.SiteIdentity AddSite(string sessionId, Agility.Sdk.Model.Forms.Site site) => throw null;
        public void UpdateSite(string sessionId, Agility.Sdk.Model.Forms.Site site) { }
        public void DeleteSite(string sessionId, Agility.Sdk.Model.Forms.SiteIdentity siteIdentity) { }
        public Agility.Sdk.Model.Forms.SiteIdentityCollection GetSites(string sessionId, Agility.Sdk.Model.Forms.SiteFilter filter) => throw null;
        public Agility.Sdk.Model.Forms.Site GetSite(string sessionId, Agility.Sdk.Model.Forms.SiteIdentity siteIdentity) => throw null;
        public Agility.Sdk.Model.Forms.SiteIdentityCollection GetRecentSites(string sessionId) => throw null;
        public void LockForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) { }
        public void UnlockForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity, bool force) { }
        public void LockFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity) { }
        public void UnlockFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity, bool force) { }
        public void AddTheme(string sessionId, Agility.Sdk.Model.Forms.Theme theme) { }
        public void UpdateTheme(string sessionId, Agility.Sdk.Model.Forms.Theme theme) { }
        public Agility.Sdk.Model.Forms.Theme GetTheme(string sessionId, Agility.Sdk.Model.Forms.ThemeIdentity themeIdentity) => throw null;
        public Agility.Sdk.Model.Forms.ThemeIdentityCollection GetThemes(string sessionId, Agility.Sdk.Model.Forms.ThemeFilter filter) => throw null;
        public Agility.Sdk.Model.Forms.ThemeIdentityCollection GetThemeIdentities(string sessionId, Agility.Sdk.Model.Forms.ThemeFilter filter) => throw null;
        public void DeleteTheme(string sessionId, Agility.Sdk.Model.Forms.ThemeIdentity themeIdentity) { }
        public Agility.Sdk.Model.Resources.ResourceIdentity IsFormLocked(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.CssClassCollection GetCssClasses(string sessionId, string fileName) => throw null;
        public string GetFormJSFileName(Agility.Sdk.Model.Forms.RuntimeFormIdentity runtimeFormIdentity) => throw null;
        public Agility.Sdk.Model.Capture.CaptureFormInfo GetCaptureFormJSFileName(short formType, string captureReferenceId, double version, Agility.Sdk.Model.Forms.SiteIdentity siteIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormImportErrorCollection ImportForms(string sessionId, Agility.Sdk.Model.Forms.ExportedFormInfo exportedFormInfo, Agility.Sdk.Model.Forms.FormImportOptions formImportOptions) => throw null;
        public Agility.Sdk.Model.Forms.ImportFormData GetImportFormData(string sessionId, Agility.Sdk.Model.Forms.ImportFormInfo importFormInfo) => throw null;
        public Agility.Sdk.Model.Forms.SiteLanguageCollection GetSiteLanguages(Agility.Sdk.Model.Forms.SiteIdentity siteIdentity) => throw null;
        public Agility.Sdk.Model.Server.StringCollection BuildForms(string sessionId, short formType, Agility.Sdk.Model.Forms.BuildForms.BuildFormData buildFormData) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentity BuildStandardForm(string sessionId, Agility.Sdk.Model.Forms.BuildForms.BuildStandardFormData buildFormData) => throw null;
        public Agility.Sdk.Model.Forms.Form InitializeStandardForm(string sessionId, Agility.Sdk.Model.Forms.BuildForms.BuildStandardFormData buildFormData) => throw null;
        public Agility.Sdk.Model.Server.StringCollection RegenerateForms(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity, bool overwriteExisting, bool release) => throw null;
        public Agility.Sdk.Model.Forms.FormIdentity CopyForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.FormTemplateIdentity CopyFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity) => throw null;
        public Agility.Sdk.Model.Forms.BuildForms.RegenerateFormsResult RegenerateForms2(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity, bool overwriteExisting, bool release) => throw null;
        public Agility.Sdk.Model.Forms.BuildForms.RegenerateFormsResult RegenerateForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity, Agility.Sdk.Model.Forms.RegenerateFormOptions regenerateFormOptions) => throw null;
        public Agility.Sdk.Model.Forms.FormSummary3Collection GetForms2(string sessionId, Agility.Sdk.Model.Forms.FormFilter2 formFilter) => throw null;
        public Agility.Sdk.Model.Server.LocalisedStringCollection GetFormLocalisedStrings(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity, string language) => throw null;
        public Agility.Sdk.Model.Forms.FormImportErrorCollection ImportForms2(string sessionId, Agility.Sdk.Model.Forms.ExportedFormInfo2 exportedFormInfo, Agility.Sdk.Model.Forms.Events.FormImportOptions2 formImportOptions) => throw null;
        public Agility.Sdk.Model.Forms.Events.ImportFormData2 GetImportFormData2(string sessionId, Agility.Sdk.Model.Forms.ImportFormInfo importFormInfo) => throw null;
        public Agility.Sdk.Model.Forms.FormImportErrorCollection ImportLegacyPackage(string sessionId, Agility.Sdk.Model.Package.PackageInformation2 packageInformation, Agility.Sdk.Model.Forms.Events.FormImportOptions2 formImportOptions) => throw null;
        public Agility.Sdk.Model.Forms.FormSummary3Collection GetFormVersions2(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Forms.ExportedFormInfo ExportForms(string sessionId, Agility.Sdk.Model.Forms.FormIdentityCollection forms, Agility.Sdk.Model.Forms.FormExportOptions formExportOptions) => throw null;
        public Agility.Sdk.Model.Forms.Events.EventOutputDataCollection ExecuteFormEvents2(Agility.Sdk.Model.Forms.FormIdentity formIdentity, string methodName, Agility.Sdk.Model.Forms.Events.EventInputDataCollection eventsToExecute, string locale, string locale2, short formTargetDevice) => throw null;
        public Agility.Sdk.Model.Forms.FormInitializationData GetFormInitializationData(string sessionId, Agility.Sdk.Model.Forms.FormInitializationInput formInitializationInput) => throw null;
        public Agility.Sdk.Model.Server.StringCollection BuildForms2(string sessionId, Agility.Sdk.Model.Forms.BuildForms.BuildFormInfoCollection buildFormInfoCollection) => throw null;
        public Agility.Sdk.Model.Forms.FormSummary4Collection GetForms3(string sessionId, Agility.Sdk.Model.Forms.FormFilter2 formFilter) => throw null;
        public void RevertFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplateIdentity formTemplateIdentity) { }
        public Agility.Sdk.Model.Forms.FormTemplateSummaryCollection GetFormTemplates(string sessionId, Agility.Sdk.Model.Forms.FormTemplateFilter formTemplateFilter) => throw null;
        public Agility.Sdk.Model.Forms.FormTemplateIdentity SaveFormTemplate(string sessionId, Agility.Sdk.Model.Forms.FormTemplate formTemplate) => throw null;
        public Agility.Sdk.Model.Forms.BuildForms.BuildFormResultCollection BuildActivityForms(string sessionId, Agility.Sdk.Model.Forms.BuildForms.BuildFormInfoCollection buildFormInfoCollection) => throw null;
        public Agility.Sdk.Model.NameValuePairCollection GetDataObjectFormVariableDefaultValues(string sessionId, Agility.Sdk.Model.NameValuePairCollection dataObjectVariables) => throw null;
    }
}
