// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureDesignService
    {
        public CaptureDesignService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Server.StringCollection GetBasicDocumentGroupNames(string sessionId) => throw null;
        public Agility.Sdk.Model.CaptureDesign.BasicDocumentGroup GetBasicDocumentGroupForEditing(string sessionId, string name) => throw null;
        public void CancelEditing(string sessionId, Agility.Sdk.Model.CaptureDesign.BasicDocumentGroup basicDocumentGroup) { }
        public void SaveBasicDocumentGroup(string sessionId, Agility.Sdk.Model.CaptureDesign.BasicDocumentGroup basicDocumentGroup) { }
    }
}
