// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class AIService
    {
        public AIService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.GenerativeAI.AIProviderIdentity AddAIProvider(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProvider provider) => throw null;
        public void UpdateAIProvider(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProvider provider) { }
        public void DeleteAIProvider(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProviderIdentity providerIdentity) { }
        public Agility.Sdk.Model.Integration.GenerativeAI.AIProvider GetAIProvider(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProviderIdentity providerIdentity) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.AIProvider GetAIProviderForCoPilot(string sessionId) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.AIProviderSummaryCollection GetAIProviders(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProviderFilter filter) => throw null;
        public Agility.Sdk.Model.Server.WorkerTaskIdentity GenerateItemAsync(string sessionId, Agility.Sdk.Model.Server.StringCollection inputPrompts, short aiGroupingType) => throw null;
        public Agility.Sdk.Model.Server.WorkerTaskIdentity RegenerateItemAsync(string sessionId, string existingItemJson, Agility.Sdk.Model.Server.StringCollection inputPrompts, short aiGroupingType) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppSummary SaveAsQuickWorkflow(string sessionId, Agility.Sdk.Model.Processes.Process process) => throw null;
        public Agility.Sdk.Model.Forms.SavedForm SaveForm(string sessionId, Agility.Sdk.Model.Forms.Form form) => throw null;
        public Agility.Sdk.Model.Processes.SavedProcess SaveProcess(string sessionId, Agility.Sdk.Model.Processes.Process process, bool release) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.GeneratedProcess GetGeneratedProcess(string sessionId, Agility.Sdk.Model.Server.WorkerTaskIdentity workerTaskIdentity) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.GeneratedForm GetGeneratedForm(string sessionId, Agility.Sdk.Model.Server.WorkerTaskIdentity workerTaskIdentity) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.GenerativeAIOutput ExecuteGenerativeAIPrompt(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.GenerativeAIPromptInputs inputs) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.GenerativeAIOutput ExecuteGenerativeAIChatPrompt(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.GenerativeAIChatPromptInputs inputs) => throw null;
        public Agility.Sdk.Model.Integration.GenerativeAI.GeneratedDataModel GetGeneratedDataModel(string sessionId, Agility.Sdk.Model.Server.WorkerTaskIdentity workerTaskIdentity) => throw null;
        public Agility.Sdk.Model.Server.DataModelIdentity SaveDataModel(string sessionId, Agility.Sdk.Model.Server.DataModel dataModel, bool release) => throw null;
        public Agility.Sdk.Model.Server.TranslatedStrings GetTranslatedStrings(string sessionId, Agility.Sdk.Model.Server.WorkerTaskIdentity workerTaskIdentity) => throw null;
        public Agility.Sdk.Model.Server.WorkerTaskIdentity CheckProviderCompatibility(string sessionId, Agility.Sdk.Model.Integration.GenerativeAI.AIProvider provider) => throw null;
    }
}
