// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocAISolutionStreamingService
    {
        public DocAISolutionStreamingService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.DocAI.DocAIDocument UploadTrainingDocument(Agility.Sdk.Model.DocAI.UploadTrainingDocumentParameters parameters) => throw null;
    }
}
