// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class PerceptiveContentIntegrationService
    {
        public PerceptiveContentIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.PerceptiveContent.ViewIdentityCollection GetViewsUsingSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite integrationSite) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.CreateFolderResult CreateFolder(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, Agility.Sdk.Model.Integration.PerceptiveContent.CreateFolderInput input, bool suspendJobOnError) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.FolderTypeIdentityCollection GetFolderTypes(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationDataCollection GetCustomPropertiesForFolderType(string sessionId, string folderTypeId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.DrawerCollection GetDrawers(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.GetDocumentResult GetDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteIdentity, string documentId, Agility.Sdk.Model.Integration.PerceptiveContent.GetDocumentDestinationInfo getDocumentDestinationInfo) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.CancelCheckoutDocumentResult UndoCheckoutDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteIdentity, Agility.Sdk.Model.Integration.PerceptiveContent.CancelCheckoutDocumentInput cancelCheckoutDocumentInput, bool suspendJobOnError) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.DocumentTypeIdentityCollection GetDocumentTypes(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationDataCollection GetCustomPropertiesForDocumentType(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, string documentTypeId) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.CaptureProfileIdentityCollection GetCaptureProfiles(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationDataCollection GetCaptureProfile(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, string captureProfileId) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.AddDocumentResult AddDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, Agility.Sdk.Model.Integration.PerceptiveContent.AddDocumentInput addDocumentInput) => throw null;
        public Agility.Sdk.Model.Server.StringCollection GetDocumentProperties(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity) => throw null;
        public void UpdateDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 integrationSiteIdentity, Agility.Sdk.Model.Integration.PerceptiveContent.UpdateDocumentInput documentInput) { }
        public Agility.Sdk.Model.Integration.PerceptiveContent.FindDocumentsOutput FindDocuments(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteId, Agility.Sdk.Model.Integration.PerceptiveContent.FindDocumentsInput findDocumentsInput) => throw null;
        public void CheckinDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteID, Agility.Sdk.Model.Integration.PerceptiveContent.CheckinDocumentInput checkinDocumentInput) { }
        public Agility.Sdk.Model.Integration.PerceptiveContent.DocumentViewerUrlSettings GetDocumentViewerUrlSettings(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteIdentity) => throw null;
        public Agility.Sdk.Model.Integration.PerceptiveContent.DeleteDocumentResult DeleteDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity2 siteId, string documentId, bool suspendJobOnError) => throw null;
    }
}
