// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ExportConnectorService
    {
        public ExportConnectorService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector2(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector3(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, bool takePageImageFromRendition, short pageRenditionNumber) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector4(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, bool takePageImageFromRendition, short pageRenditionNumber, short exportOrder, bool exportSourceDocument, bool exportPageImage) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector5(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, bool takePageImageFromRendition, short pageRenditionNumber, short exportOrder, bool exportSourceDocument, bool exportPageImage, bool markCompleted) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector6(string sessionId, string documentId, string folderId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, Agility.Sdk.Model.Activities.JobActivityIdentity jobActivityIdentity, bool takePageImageFromRendition, short pageRenditionNumber, short exportOrder, bool exportSourceDocument, bool exportPageImage, bool markCompleted, short includeAnnotations) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorResult ExecuteExportConnector7(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnectorInput exportConnectorInput) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorSummaryCollection GetExportConnectors(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnector GetExportConnector(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnectorIdentity exportConnectorIdentity) => throw null;
        public void AddExportConnector(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnector exportConnector) { }
        public void UpdateExportConnector(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnector exportConnector) { }
        public void DeleteExportConnector(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnectorIdentity exportConnectorIdentity) { }
        public Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection GetExportConnectorDocTypeMappings(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Export.ExportConnectorMappingCollection GetExportConnectorMappings(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public void SaveExportConnectorMappings(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnectorDocTypeMappingCollection mappingCollection, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) { }
        public string ExportConnectorConfiguration(string sessionId, Agility.Sdk.Model.Capture.Export.ExportConnectorIdentity connector) => throw null;
        public void ImportConnectorConfiguration(
            string sessionId,
            string xml,
            bool? overwrite
            ) { }
    }
}
