// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class OCRService
    {
        public OCRService(System.ServiceModel.Channels.Binding binding) { }
        public void AddOCRProvider(string sessionId, Agility.Sdk.Model.Integration.OCR.OCRProvider OCRProvider) { }
        public void UpdateOCRProvider(string sessionId, Agility.Sdk.Model.Integration.OCR.OCRProvider OCRProvider) { }
        public void DeleteOCRProvider(string sessionId, Agility.Sdk.Model.Integration.OCR.OCRProviderIdentity OCRProviderIdentity) { }
        public Agility.Sdk.Model.Integration.OCR.OCRProvider GetOCRProvider(string sessionId, Agility.Sdk.Model.Integration.OCR.OCRProviderIdentity OCRProviderIdentity) => throw null;
        public Agility.Sdk.Model.Integration.OCR.OCRProviderCollection GetOCRProviders(string sessionId) => throw null;
    }
}
