// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class PackageStreamingService
    {
        public PackageStreamingService(System.ServiceModel.Channels.Binding binding) { }
        public System.IO.Stream ExportPackageToStream() => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageImportResult ImportPackageFromStream(System.IO.Stream packageData) => throw null;
    }
}
