// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class AssetService
    {
        public AssetService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Assets.AssetIdentity AddAsset(string sessionId, Agility.Sdk.Model.Assets.Asset asset) => throw null;
        public Agility.Sdk.Model.Assets.Asset GetAsset(string sessionId, Agility.Sdk.Model.Assets.AssetIdentity assetIdentity) => throw null;
        public Agility.Sdk.Model.Assets.AssetSummaryCollection GetAssetSummaries(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category, short assetType) => throw null;
        public void UpdateAsset(string sessionId, Agility.Sdk.Model.Assets.Asset asset) { }
        public void DeleteAsset(string sessionId, Agility.Sdk.Model.Assets.AssetIdentity asset) { }
        public string GetAssetId(string sessionId, Agility.Sdk.Model.Assets.AssetIdentity asset) => throw null;
        public void AddAssets(string sessionId, Agility.Sdk.Model.Assets.AssetCollection assets) { }
        public Agility.Sdk.Model.Assets.AssetCollection GetAssets(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category, short assetType) => throw null;
        public System.IO.Stream GetAssetImage(string sessionId, Agility.Sdk.Model.Assets.AssetIdentity assetIdentity, string mimeType, int desiredHeight, int desiredWidth, short imagePixelFormat) => throw null;
    }
}
