// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class UserService
    {
        public UserService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Users.Session LogOn(Agility.Sdk.Model.Users.UserIdentity userIdentity) => throw null;
        public Agility.Sdk.Model.Users.Session LogOnWithPassword(Agility.Sdk.Model.Users.UserIdentityWithPassword userIdentityWithPassword) => throw null;
        public Agility.Sdk.Model.Users.Session LogOnWithWindowsAuthentication(short logOnProtocol, bool unconditionalLogOn) => throw null;
        public void LogOff(string sessionId) { }
        public Agility.Sdk.Model.Users.Session ValidateSession(string sessionId) => throw null;
        public Agility.Sdk.Model.Resources.LoggedOnUserCollection GetLoggedOnUsers(string sessionId) => throw null;
        public Agility.Sdk.Model.Resources.LoggedOnUser2Collection GetLoggedOnUsers2(string sessionId) => throw null;
        public void LogOffUsers2(string sessionId, Agility.Sdk.Model.Server.StringCollection resourceIds) { }
        public void LogOffUsers(string sessionId, Agility.Sdk.Model.Server.StringCollection sessionIds) { }
        public Agility.Sdk.Model.Users.Session GetSession(Agility.Sdk.Model.Users.UserIdentity2 userIdentity) => throw null;
        public Agility.Sdk.Model.Users.Session GetSessionWithPassword(Agility.Sdk.Model.Users.UserIdentityWithPassword userIdentity) => throw null;
        public Agility.Sdk.Model.Users.Session LogOnWithEmailAddress(Agility.Sdk.Model.Users.UserEmailIdentity userEmailIdentity) => throw null;
        public Agility.Sdk.Model.Users.Session2 LogOn2(Agility.Sdk.Model.Users.UserIdentity userIdentity) => throw null;
        public Agility.Sdk.Model.Users.Session2 LogOnWithPassword2(Agility.Sdk.Model.Users.UserIdentityWithPassword userIdentityWithPassword) => throw null;
        public Agility.Sdk.Model.Users.Session2 LogOnWithWindowsAuthentication2(short logOnProtocol, bool unconditionalLogOn) => throw null;
        public Agility.Sdk.Model.Users.Session2 LogOnWithEmailAddress2(Agility.Sdk.Model.Users.UserEmailIdentity userEmailIdentity) => throw null;
        public string GetWindowsUser() => throw null;
        public Agility.Sdk.Model.Users.LogonState ChangePassword(string sessionId, string oldPassword, string newPassword) => throw null;
        public string GetFederatedAuthenticationSignInUrl(string callbackUrl, Agility.Sdk.Model.Authentication.AuthenticationProviderIdentity authenticationProviderIdentity, short callbackProtocol, string origin) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProvidersForSignIn GetFederatedAuthenticationProvidersForSignIn(string callbackUrl, short callbackProtocol, string origin) => throw null;
        public void ForgotPassword(string emailAddress) { }
        public void ChangeForgottenPassword(string sessionId, string newPassword) { }
        public Agility.Sdk.Model.Users.LogonState SupplyPasscode(string sessionId, string passcode) => throw null;
        public Agility.Sdk.Model.Users.Session GetSingleSignOnSession(string systemSessionId, Agility.Sdk.Model.Users.UserIdentity2 userIdentity) => throw null;
        public string FederatedLogOff(string sessionId) => throw null;
        public Agility.Sdk.Model.Authentication.AuthenticationProvidersForSignIn2 GetFederatedAuthenticationProvidersForSignIn2(string callbackUrl, short callbackProtocol, string origin) => throw null;
        public string GetHomePageUrl(string sessionId) => throw null;
    }
}
