// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CloudStorageService
    {
        public CloudStorageService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.AzureStorage.AzureStorageImportOutput ExecuteAzureBlobStorageImportActivity(string sessionId, Agility.Sdk.Model.AzureStorage.AzureStorageImportSettings azureStorageImportSettings) => throw null;
        public string ExecuteAzureBlobStorageExportActivity(string sessionId, Agility.Sdk.Model.AzureStorage.AzureStorageExportSettings azureStorageExportSettings) => throw null;
    }
}
