// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocumentVariantService
    {
        public DocumentVariantService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.Variant.VariantIdentity SaveDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.DocumentTypeVariant documentTypeVariant, Agility.Sdk.Model.Capture.Variant.DocumentVariantOptions options) => throw null;
        public void SaveVariantToDocumentTypes(string sessionId, Agility.Sdk.Model.Capture.Variant.DocumentTypeVariant documentTypeVariant, Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection childDocumentTypes) { }
        public Agility.Sdk.Model.Capture.Variant.DocumentTypeVariant GetDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Variant.VariantSummaryCollection GetDocumentTypeVariants(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Variant.DocumentTypeActivityVariant CopyActivityVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity documentVariantIdentity, Agility.Sdk.Model.Capture.Variant.ActivityVariantIdentity activityVariantIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Variant.ActivityVariantIdentity AddActivityVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.DocumentTypeActivityVariant activityVariant) => throw null;
        public void UpdateActivityVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.DocumentTypeActivityVariant activityVariant) { }
        public void DeleteActivityVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity documentVariantIdentity, Agility.Sdk.Model.Capture.Variant.ActivityVariantIdentity activityVariantIdentity) { }
        public Agility.Sdk.Model.Capture.Variant.ActivityVariantSummaryCollection GetActivityVariantSummaryCollection(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public void DeleteDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) { }
        public Agility.Sdk.Model.Capture.Variant.DocumentTypeVariant CopyDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
        public void LockDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) { }
        public void UnlockDocumentTypeVariant(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity, bool force) { }
        public Agility.Sdk.Model.Resources.ResourceIdentity IsDocumentTypeVariantLocked(string sessionId, Agility.Sdk.Model.Capture.Variant.VariantIdentity variantIdentity) => throw null;
    }
}
