// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class QuickAppService
    {
        public QuickAppService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.QuickApps.QuickAppSummaryCollection GetQuickApps(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppFilter quickAppFilter) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickApp GetQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity identity) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppSummary SaveQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickApp quickApp) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppSummary PublishQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity, Agility.Sdk.Model.QuickApps.QuickApp quickApp) => throw null;
        public void DeleteQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity, bool deleteAllVersions) { }
        public void LockQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity) { }
        public void UnlockQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity) { }
        public Agility.Sdk.Model.QuickApps.QuickAppAssociations GetQuickAppAssociations(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppAssociations GetQuickAppAssociations2(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity, bool getNestedAssociations) => throw null;
        public Agility.Sdk.Model.QuickClassification.QuickClassificationInfo GetQuickClassificationInfo(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.CaptureSolutions.Classification.ClassificationTrainingResultCollection AnalyzeQuickClassificationTraining(string sessionId, Agility.Sdk.Model.QuickClassification.QuickClassificationInfo quickClassificationInfo) => throw null;
        public Agility.Sdk.Model.QuickClassification.QuickClassificationInfo SaveQuickClassificationGroup(string sessionId, Agility.Sdk.Model.QuickClassification.QuickClassificationInfo quickClassificationInfo, short status) => throw null;
        public double RunQuickClassificationBenchmark(string sessionId, Agility.Sdk.Model.QuickClassification.QuickClassificationInfo quickClassificationInfo) => throw null;
        public Agility.Sdk.Model.Processes.AllowedProcessCollection GetExposedProcesses(string sessionId, Agility.Sdk.Model.QuickApps.ExposedProcessesFilter exposedProcessesFilter) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppSearchItemResultCollection SearchItems(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppSearchItemsFilter searchItemFilter) => throw null;
        public void ForceUnlockQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity quickAppIdentity) { }
        public Agility.Sdk.Model.BusinessRules.BusinessRule GetBusinessRule(string sessionId, Agility.Sdk.Model.BusinessRules.BusinessRuleIdentity businessRuleIdentity) => throw null;
        public Agility.Sdk.Model.Email.EmailServerSettings GetEmailServerSettings(string sessionId) => throw null;
    }
}
