// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocAISolutionService
    {
        public DocAISolutionService(System.ServiceModel.Channels.Binding binding) { }
        public string CreateDocAIFolder(string sessionId) => throw null;
        public void SaveSolution(string sessionId, Agility.Sdk.Model.DocAI.DocAISolution solution) { }
    }
}
