// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class LicenseServerService
    {
        public LicenseServerService(System.ServiceModel.Channels.Binding binding) { }
        public void SetLicenseName(string sessionId, int licenseId, string name) { }
        public void ReleaseFeatureLicense(string sessionId, string host, string debugName, int licenseId, long licenseServerKey) { }
        public void Ping(string sessionId, string host, string debugName, long licenseServerKey) { }
        public void ClientDispose(string sessionId, string host, string debugName, long licenseServerKey) { }
        public Agility.Sdk.Model.License.LicenseServerDetails RequestFeatureLicense(string sessionId, string host, string debugName, int licenseId, int challenge, long licenseServerKey) => throw null;
        public Agility.Sdk.Model.License.SharedLicenseDetails RequestSharedFeatureLicenses(string sessionId, string host, string debugName, int licenseId, long unitsRequested, int challenge, long licenseServerKey) => throw null;
        public Agility.Sdk.Model.License.VolumeLicenseRolloverDetails UseVolumeLicenseWithRollover(string sessionId, string host, string debugName, int licenseId, long units, int challenge, long licenseServerKey, long transactionId, string cachedVolumeData) => throw null;
        public Agility.Sdk.Model.License.LicenseServerInfo GetServerInfo(string sessionId, bool checkServerAvailability) => throw null;
        public Agility.Sdk.Model.License.LicenseServerInfo GetServerInfo2(string sessionId, bool checkServerAvailability, bool getExpiredLicenses = false) => throw null;
    }
}
