// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class TrimIntegrationService
    {
        public TrimIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public string CreateFolder(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity, string relativePath, string mainFolderTitle, string folderTitle, string recordType, Agility.Sdk.Model.Document.DocumentFieldCollection documentFields) => throw null;
        public string CreateFolder2(string sessionId, Agility.Sdk.Model.Integration.Trim.AddTrimFolderInput folderInput) => throw null;
        public bool ValidateDataSetId(string sessionId, string url, string dataSetId, bool raiseException) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationDataCollection GetMetadata(string sessionId, string url, string dataSetId) => throw null;
        public Agility.Sdk.Model.Integration.FilePlanCollection GetDocuments(string sessionId, string url, string classificationName, string folderPath, System.DateTime searchCriteriaDocumentAddedDateFrom, System.DateTime searchCriteriaDocumentAddedDateTo, Agility.Sdk.Model.Document.DocumentFieldCollection searchCriteriaDocumentMetadata, string searchCriteriaTitle, string searchCriteriaDocumentType, string searchCriteriaAuthor, string searchCriteriaContent, string dataSetId) => throw null;
        public Agility.Sdk.Model.Integration.FilePlanCollection GetDocuments2(string sessionId, string url, string classificationName, string folderPath, bool useDateRange, System.DateTime searchCriteriaDocumentAddedDateFrom, System.DateTime searchCriteriaDocumentAddedDateTo, Agility.Sdk.Model.Document.DocumentFieldCollection searchCriteriaDocumentMetadata, string searchCriteriaTitle, string searchCriteriaDocumentType, string searchCriteriaAuthor, string searchCriteriaContent, string dataSetId) => throw null;
        public Agility.Sdk.Model.Integration.FolderPlanCollection GetFolders(string sessionId, string url, string filePlan, string dataSetId) => throw null;
        public string AddDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity, string relativePath, string folderTitle, string filePath, string documentTitle, bool declareAsRecord, string recordType, Agility.Sdk.Model.Document.DocumentFieldCollection documentFields) => throw null;
        public string AddDocument2(string sessionId, Agility.Sdk.Model.Integration.Trim.AddTrimDocumentInput documentInput) => throw null;
        public string CheckIn(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity, string relativePath, string folderTitle, string filePath, string documentTitle, bool declareAsRecord, Agility.Sdk.Model.Document.DocumentFieldCollection documentFields, string recNumber) => throw null;
        public string CheckIn2(string sessionId, Agility.Sdk.Model.Integration.Trim.AddTrimDocumentInput documentInput) => throw null;
        public Agility.Sdk.Model.Integration.TrimDocument GetDocument(string sessionId, string url, int uniqueIdentifier, string dataSetId) => throw null;
        public Agility.Sdk.Model.Integration.IntegrationEventCategoryCollection GetRecordTypes(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity siteIdentity) => throw null;
        public void CheckoutDocument(string sessionId, Agility.Sdk.Model.Integration.IntegrationSiteIdentity integrationSiteIdentity, string relativePath, string folderTitle, string documentTitle, string checkoutLocation, bool isCheckout, string recordNumber, string integrationSiteName = null) { }
    }
}
