// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureDocumentService
    {
        public CaptureDocumentService(System.ServiceModel.Channels.Binding binding) { }
        public CaptureDocumentService(System.ServiceModel.Channels.Binding binding, System.ServiceModel.Description.IEndpointBehavior endpointBehavior) { }
        public Agility.Sdk.Model.Forms.Events.SearchResult SearchFuzzyDatabase(string sessionId, Agility.Sdk.Model.Forms.Events.FuzzyDatabaseIdentity databaseIdentity, Agility.Sdk.Model.Forms.Events.SearchQuery query, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public bool ValidateDocument(string sessionId, string documentId) => throw null;
        public bool ValidateFolder(string sessionId, string folderId) => throw null;
        public bool ValidateHierarchy(string sessionId, string folderId) => throw null;
        public bool ValidateDocumentWithType(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public bool ValidateFolderWithType(string sessionId, string folderId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentFieldValueCollection GetDocumentFieldValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldIdentityCollection fieldIdentities) => throw null;
        public Agility.Sdk.Model.Capture.DocumentFieldValue GetDocumentFieldValue(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldIdentity fieldIdentity) => throw null;
        public Agility.Sdk.Model.Capture.FolderFieldValueCollection GetFolderFieldValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.RuntimeFieldIdentityCollection fieldIdentities) => throw null;
        public Agility.Sdk.Model.Capture.FolderFieldValue GetFolderFieldValue(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.RuntimeFieldIdentity fieldIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Folder GetFolder(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId) => throw null;
        public Agility.Sdk.Model.Capture.FolderCollection SearchFolders(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, Agility.Sdk.Model.Capture.FolderSearchCriteria folderSearchCriteria) => throw null;
        public void UpdateDocumentFieldValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields) { }
        public void UpdateDocumentFieldValue(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeField runtimeField) { }
        public void SetDocumentStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, short documentStatus, string message) { }
        public void SetFolderStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, short folderStatus, string message) { }
        public void MoveDocument(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string folderId, int insertIndex) { }
        public void MovePages(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string toDocumentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes, int insertIndex) { }
        public void RotatePages(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes, short rotationType, bool preserveTextData) { }
        public void RotatePagesRendition(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes, short rotationType, short renditionNumber) { }
        public Agility.Sdk.Model.Capture.DocumentImage GetImage(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string imageId, int desiredWidth, int desiredHeight, string desiredFormat) => throw null;
        public System.IO.Stream GetPageImage(string sessionId, string docId, string pageId, int desiredWidth, int desiredHeight, string desiredFormat) => throw null;
        public Agility.Sdk.Model.Capture.DeletionResult DeleteDocument(string sessionId, string documentId, Agility.Sdk.Model.Capture.ReportingData reportingData, bool failOnError) => throw null;
        public Agility.Sdk.Model.Capture.DeletionResult DeleteDocuments(string sessionId, Agility.Sdk.Model.Server.StringCollection documentIds, Agility.Sdk.Model.Capture.ReportingData reportingData, bool ignoreError) => throw null;
        public string SplitDocument(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, int pageIndex) => throw null;
        public void SetDocumentFieldsStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.FieldStatusCollection fieldsStatus) { }
        public void SetDocumentFieldStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldIdentity fieldIdentity, short documentFieldStatus, string message, object fieldValue) { }
        public void SetFolderFieldsStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.FieldStatusCollection fieldsStatus) { }
        public void SetFolderFieldStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.RuntimeFieldIdentity fieldIdentity, short folderFieldStatus, string message, object fieldValue) { }
        public void InsertTableFieldRow(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string tableFieldId, int rowIndex) { }
        public void InsertTableFieldRows(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string tableFieldId, int insertIndex, int rowsNumber) { }
        public void DeleteTableFieldRow(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string tableFieldId, Agility.Sdk.Model.Capture.RowIndexCollection rowIndexes) { }
        public void InterpolateTableField(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string tableFieldId, int selectedIndex) { }
        public string CreateFolder(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, int insertIndex, Agility.Sdk.Model.Categories.CategoryIdentity folderTypeCategory, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public void RejectPages(string sessionId, string documentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes, string reason) { }
        public void UnrejectPages(string sessionId, string documentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes) { }
        public Agility.Sdk.Model.Capture.RejectedPages GetRejectedPages(string sessionId, string documentId) => throw null;
        public Agility.Sdk.Model.Capture.DeletionResult DeleteFolder(string sessionId, string folderId, Agility.Sdk.Model.Capture.ReportingData reportingData, bool failOnError) => throw null;
        public string SplitFolder(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, int index) => throw null;
        public string SplitFolder2(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, int index) => throw null;
        public void MoveFolder(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string toFolderId, int insertIndex) { }
        public void UpdateFolderFieldValue(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.RuntimeField runtimeField) { }
        public void UpdateFolderFieldValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields) { }
        public void UpdatePages(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string docId, Agility.Sdk.Model.Capture.PageData2Collection pageData2Collection) { }
        public Agility.Sdk.Model.Capture.DocumentIdentityCollection CreateDocuments(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFolderFields, string folderTypeId, Agility.Sdk.Model.Capture.DocumentDataInputCollection documentData) => throw null;
        public Agility.Sdk.Model.Capture.DocumentIdentityCollection CreateDocuments2(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFolderFields, string folderTypeId, Agility.Sdk.Model.Capture.DocumentDataInput2Collection documentData) => throw null;
        public Agility.Sdk.Model.Capture.DocumentIdentity CreateDocumentWithPages(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, string documentTypeId, string folderTypeId, Agility.Sdk.Model.Capture.PageDataCollection pages) => throw null;
        public Agility.Sdk.Model.Capture.DocumentIdentity CreateDocument(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, string filePath, int insertIndex, string documentTypeId, string folderTypeId) => throw null;
        public Agility.Sdk.Model.Capture.DocumentIdentity CreateDocument2(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, string filePath, int insertIndex, string documentTypeId, string folderTypeId, Agility.Sdk.Model.Capture.FieldPropertiesCollection runtimeFieldProperties) => throw null;
        public void CreatePage(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, string filePath, int insertIndex) { }
        public void DeletePages(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.PageIndexCollection pageIndexes) { }
        public Agility.Sdk.Model.Capture.DocumentSourceFile GetSourceFile(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId) => throw null;
        public Agility.Sdk.Model.Capture.Document GetDocument(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId) => throw null;
        public Agility.Sdk.Model.Capture.DocumentCollection SearchDocuments(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, Agility.Sdk.Model.Capture.DocumentSearchCriteria documentSearchCriteria) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ReviewValidationResult ValidateDocumentForReview(string sessionId, string documentId) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ReviewValidationResult ValidateFolderForReview(string sessionId, string folderId) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ReviewValidationResult ValidateDocumentForReviewWithType(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ReviewValidationResult ValidateFolderForReviewWithType(string sessionId, string folderId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResult ValidateDocumentField(string sessionId, string documentTypeId, Agility.Sdk.Model.Capture.RuntimeFieldValue field) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResultCollection ValidateDocumentFields(string sessionId, string documentTypeId, Agility.Sdk.Model.Capture.RuntimeFieldValueCollection fields) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResult ValidateFolderField(string sessionId, string folderTypeId, Agility.Sdk.Model.Capture.RuntimeFieldValue field) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResultCollection ValidateFolderFields(string sessionId, string folderTypeId, Agility.Sdk.Model.Capture.RuntimeFieldValueCollection fields) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FormattingResult TestFieldFormatter(string sessionId, string value, Agility.Sdk.Model.Capture.Formatting.FieldFormatter fieldFormatter) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FormattingResult TestFieldFormatter2(string sessionId, string value, Agility.Sdk.Model.Capture.Formatting.FieldFormatter fieldFormatter, Agility.Sdk.Model.BusinessRules.BusinessRuleInputCollection ruleInputs) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResult TestFieldValidator(string sessionId, string value, Agility.Sdk.Model.Capture.Validation.Validator validator) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationResult TestFieldValidator2(string sessionId, string value, Agility.Sdk.Model.Capture.Validation.ValidatorIdentity validatorIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FormattingResult FormatField(string sessionId, string value, Agility.Sdk.Model.Capture.Formatting.FormatterIdentity formatterIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FormattingResult FormatField2(string sessionId, string value, Agility.Sdk.Model.Capture.Formatting.FormatterIdentity formatterIdentity, Agility.Sdk.Model.BusinessRules.BusinessRuleInputCollection ruleInputs) => throw null;
        public string GetDocumentAsFile(string sessionId, string documentId, string fileLocation, string fileName) => throw null;
        public string GetDocumentAsFile2(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentAsFileOptions options) => throw null;
        public string CreateOnlineLearningFolder(string sessionId, int maxSamples) => throw null;
        public Agility.Sdk.Model.Capture.DocumentSortResult GetDocumentsInOrder(string sessionId, string folderId, string field1NameForSort, string field2NameForSort, string field3NameForSort, bool ascending) => throw null;
        public Agility.Sdk.Model.Capture.FieldAlternativeCollection GetDocumentFieldAlternatives(string sessionId, string documentId, Agility.Sdk.Model.Capture.FieldIdentity fieldIdentity, int numberOfRowsToReturn) => throw null;
        public Agility.Sdk.Model.Capture.FieldAlternative2Collection GetDocumentFieldAlternatives2(string sessionId, string documentId, Agility.Sdk.Model.Capture.FieldIdentity fieldIdentity, int numberOfRowsToReturn) => throw null;
        public void SaveTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string name, string text) { }
        public string GetTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string name) => throw null;
        public Agility.Sdk.Model.Server.StringCollection GetTextExtensions(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string[] names) => throw null;
        public Agility.Sdk.Model.Capture.FieldAlternativesCollection GetDocumentFieldsAlternatives(string sessionId, string documentId, Agility.Sdk.Model.Capture.FieldIdentityCollection fields, int numberOfRowsToReturn) => throw null;
        public Agility.Sdk.Model.Capture.FieldAlternatives2Collection GetDocumentFieldsAlternatives2(string sessionId, string documentId, Agility.Sdk.Model.Capture.FieldIdentityCollection fields, int numberOfRowsToReturn) => throw null;
        public void CreatePageUsingStream(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFields, byte[] data, int insertIndex, string mimeType) { }
        public System.Data.DataSet GetDocumentTableFieldValue(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.TableFieldIdentity tableFieldIdentity) => throw null;
        public Agility.Sdk.Model.Capture.LockedItemCollection GetJobVariableLockStatus(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity) => throw null;
        public void ForceUnlockItem(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, Agility.Sdk.Model.Capture.LockedItemIdentity identity) { }
        public Agility.Sdk.Model.Nlp.NamedEntityCollection GetNamedEntities(string sessionId, string documentId) => throw null;
        public System.IO.Stream GetDocumentFile(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string fileType) => throw null;
        public System.IO.Stream GetDocumentFile2(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.DocumentFileOptions documentFileOptions) => throw null;
        public System.IO.Stream GetDocumentRenditionsFile(string sessionId, string documentId, string renditionName, string fileType) => throw null;
        public void UpdateDocumentType(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) { }
        public void UpdateDocumentType2(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) { }
        public void UpdateDocumentTypeWithConfidence(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, double confidenceLevel) { }
        public void UpdateDocumentTypeWithConfidence2(string sessionId, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, double confidenceLevel, bool classificationConfident) { }
        public void UpdateDocumentTypeWithConfidence3(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, double confidenceLevel, bool classificationConfident) { }
        public Agility.Sdk.Model.Capture.DocumentIdentityCollection SplitDocumentAndClassify(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.SplitDocumentInfoCollection splitDocumentInfoCollection) => throw null;
        public void CopyDocumentFieldValues(string sessionId, string sourceDocumentId, string targetDocumentId) { }
        public void MergeDocuments(string sessionId, Agility.Sdk.Model.Server.StringCollection documentIds) { }
        public void RejectDocuments(string sessionId, Agility.Sdk.Model.Server.StringCollection documentIds, Agility.Sdk.Model.Capture.ReportingData reportingData, string reason) { }
        public void UnrejectDocuments(string sessionId, Agility.Sdk.Model.Server.StringCollection documentIds, Agility.Sdk.Model.Capture.ReportingData reportingData) { }
        public void UpdateDocumentsProcessingCompleted(string sessionId, Agility.Sdk.Model.Server.StringCollection documentIds) { }
        public void RejectDocument(string sessionId, string documentId, string reason) { }
        public string CopyDocument(string sessionId, string sourceDocumentId, string targetDocumentId, Agility.Sdk.Model.Server.StringCollection fieldNames, short copyDocumentOptions) => throw null;
        public Agility.Sdk.Model.Capture.PageImageData SavePageImage(string sessionId, string batchId, byte[] data, string mimeType) => throw null;
        public Agility.Sdk.Model.Capture.PageImageData SavePageImage2(string sessionId, string batchId, byte[] data, string mimeType, bool initializeBatch) => throw null;
        public Agility.Sdk.Model.Capture.Validation.FieldValidationResult2Collection ValidateAllDocumentFields(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, Agility.Sdk.Model.Capture.RuntimeField2Collection documentFields, Agility.Sdk.Model.Capture.DocumentSystemProperties documentSystemProperties) => throw null;
        public void SavePageRendition(string sessionId, string documentId, string pageId, short renditionNumber, string mimeType, byte[] imageStream) { }
        public byte[] GetPageRendition(string sessionId, string documentId, string pageId, short renditionNumber) => throw null;
        public void SetPageSourceImageFromRendition(string sessionId, string documentId, string pageId, short renditionNumber) { }
        public void DeletePageRendition(string sessionId, string documentId, string pageId, short renditionNumber) { }
        public bool AddPageMaskForField(string sessionId, string documentId, int pageIndex, string fieldName, int color) => throw null;
        public bool AddPageMaskForRegion(string sessionId, string documentId, int pageIndex, int left, int top, int right, int bottom, int color) => throw null;
        public int RemovePageMasks(string sessionId, string documentId, int pageIndex, int left, int top, int right, int bottom) => throw null;
        public bool RemoveAllPageMasks(string sessionId, string documentId, int pageIndex) => throw null;
        public Agility.Sdk.Model.Capture.WordCollection GetAllMaskedWords(string sessionId, string documentId, int pageIndex) => throw null;
        public Agility.Sdk.Model.Capture.PageMaskCollection GetAllPageMasks(string sessionId, string documentId, int pageIndex) => throw null;
        public bool IsPageRenditionDefined(string sessionId, string documentId, string pageId, short renditionNumber) => throw null;
        public byte[] GetDocumentTypeImage(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.RuntimeField2Collection GetDocumentFieldsProperties(string sessionId, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldIdentityCollection fields) => throw null;
        public Agility.Sdk.Model.Capture.ImageSummary GetPageRenditionImageSummary(string sessionId, string documentId, string pageId, short renditionNumber) => throw null;
        public Agility.Sdk.Model.Capture.PageSummary GetPageSummary(string sessionId, string documentId, string pageId) => throw null;
        public string CopyDocumentWithPages(string sessionId, string documentId, int insertIndex) => throw null;
        public Agility.Sdk.Model.Capture.FieldPropertiesCollection GetDocumentFieldPropertyValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.FieldPropertiesIdentityCollection fieldProperties) => throw null;
        public void UpdateDocumentFieldPropertyValues(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.FieldPropertiesCollection fieldProperties) { }
        public void UpdateWords(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, Agility.Sdk.Model.Capture.WordUpdateCollection wordUpdates) { }
        public Agility.Sdk.Model.Capture.WordCollection GetWordsInRectangle(string sessionId, Agility.Sdk.Model.Capture.WordCollection words, int top, int left, int height, int width) => throw null;
        public Agility.Sdk.Model.Capture.Annotations.AnnotationDataCollection GetAnnotations(string sessionId, string documentId) => throw null;
        public Agility.Sdk.Model.Capture.Annotations.AnnotationDataCollection GetAnnotations2(string sessionId, string documentId) => throw null;
        public void DeleteExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string name) { }
        public void SaveBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string name, string mimeType, byte[] data) { }
        public Agility.Sdk.Model.Capture.BinaryData GetBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string name) => throw null;
        public void SavePageBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string name, string mimeType, byte[] data) { }
        public Agility.Sdk.Model.Capture.BinaryData GetPageBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string name) => throw null;
        public void SavePageTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string name, string text) { }
        public string GetPageTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string name) => throw null;
        public Agility.Sdk.Model.Server.StringCollection GetPageTextExtensions(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string[] names) => throw null;
        public Agility.Sdk.Model.Capture.PagePropertiesCollection GetPagePropertyValues(string sessionId, string documentId, Agility.Sdk.Model.Capture.PagePropertiesIdentityCollection pagePropertyIdentityValues) => throw null;
        public void DeletePageExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, string pageId, string extensionName) { }
        public void SaveFolderBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string name, string mimeType, byte[] data) { }
        public Agility.Sdk.Model.Capture.BinaryData GetFolderBinaryExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string name) => throw null;
        public void SaveFolderTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string name, string text) { }
        public string GetFolderTextExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string name) => throw null;
        public void DeleteFolderExtension(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId, string name) { }
        public void UpdateSourceFile(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, Agility.Sdk.Model.Capture.DocumentSourceFile sourceFile) { }
        public void DeleteSourceFile(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId) { }
        public Agility.Sdk.Model.Capture.Validation.FieldValidationResult2Collection RunFolderFieldsValidation(string sessionId, string folderId, Agility.Sdk.Model.Capture.RuntimeFieldIdentityCollection runtimeFields) => throw null;
        public Agility.Sdk.Model.Capture.Validation.FieldValidationResult2Collection RunDocumentFieldsValidation(string sessionId, string documentId, Agility.Sdk.Model.Capture.RuntimeFieldIdentityCollection runtimeFields) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidationExecutionContext GetValidationExecutionContext(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.DocumentIdentity CreateDocument3(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string parentId, Agility.Sdk.Model.Capture.RuntimeFieldCollection runtimeFolderFields, string folderTypeId, Agility.Sdk.Model.Capture.DocumentDataInput2 documentDataInput, int insertIndex) => throw null;
        public void UpdateDocumentVariant(string sessionId, string documentId, string variantName) { }
        public string ValidateDocumentData(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, string documentXml, System.Collections.Generic.List<byte[]> sourceFileBinaries) => throw null;
        public void MarkDocumentAsFinished(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId) { }
        public void MarkFolderDocumentsAsFinished(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string folderId) { }
        public string CreateExportZip(string sessionId, string folderId, string documentId, string fileLocation, string fileName) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection GetDocumentTypeIdentities(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentityCollection classificationGroups) => throw null;
        public void StoreBinaryChunk(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string chunkGroupId, int chunkIndex, byte[] data, int offset, int length) { }
        public string MergeBinaryChunks(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string chunkGroupId, string mimeType) => throw null;
        public void DeleteBinaryChunks(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string chunkGroupId) { }
        public int GetBinaryChunksCount(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string chunkGroupId) => throw null;
        public void UpdateGeneratedPdf(string sessionId, Agility.Sdk.Model.Capture.ReportingData reportingData, string documentId, byte[] data, string binaryDataId) { }
        public void AddPdfBookmarks(string sessionId, string documentId, Agility.Sdk.Model.Capture.Pdf.PdfBookmarkCollection bookmarks, short target, Agility.Sdk.Model.Capture.Pdf.PdfBookmarksOptions options) { }
    }
}
