// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DynamicsAxIntegrationService
    {
        public DynamicsAxIntegrationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Integration.DaxEntity EstablishConnectionToSiteAndService(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite site, Agility.Sdk.Model.Integration.DaxEntity entity) => throw null;
        public Agility.Sdk.Model.Integration.DaxAttributeCollection RetrieveComplexTypeElements(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite site, Agility.Sdk.Model.Integration.DaxEntity entity) => throw null;
        public Agility.Sdk.Model.Integration.DaxEntityCollection UpdateAllEntities(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite site, Agility.Sdk.Model.Integration.DaxEntityCollection entities) => throw null;
        public bool ConnectToSite(string sessionId, Agility.Sdk.Model.Integration.IntegrationSite site) => throw null;
        public bool RaiseDaxEvent(string daxInstanceName, string actionType, string tableName, int tableId, long recordId, string originalRecord = null, string updatedRecord = null, string fieldsChanged = null) => throw null;
        public Agility.Sdk.Model.Integration.DaxNodeResults ProcessDaxNode(string sessionId, Agility.Sdk.Model.Integration.DynamicsAxAction daxAction) => throw null;
    }
}
