// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class PackageService
    {
        public PackageService(System.ServiceModel.Channels.Binding binding) { }
        public void SavePackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackage packageInfo) { }
        public void DeletePackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) { }
        public Agility.Sdk.Model.SpaPackages.SpaPackage GetPackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageSummary GetPackageSummary(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageSummaryCollection GetPackages(string sessionId, Agility.Sdk.Model.SpaPackages.PackageFilter filter) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageComparisonSummary ComparePackages(string sessionId, byte[] leftPackage, byte[] rightPackage) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageComparisonSummary ComparePackagesUsingManifest(string sessionId, string leftPackageManifest, string rightPackageManifest) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageImportResult ImportPackage(string sessionId, byte[] packageData, Agility.Sdk.Model.SpaPackages.SpaPackageImportOptions spaPackageImportOptions) => throw null;
        public string SavePackageImportOptions(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageImportOptions spaPackageImportOptions) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageComparisonSummary GetPackageData(string sessionId, byte[] package) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageImportResult ImportPackage2(string sessionId, byte[] packageData, Agility.Sdk.Model.SpaPackages.SpaPackageImportOptions2 importOptions) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageImportResult ImportPackageFromBytes(string sessionId, byte[] packageData, Agility.Sdk.Model.SpaPackages.SpaPackageImportOptions3 importOptions) => throw null;
        public Agility.Sdk.Model.SpaPackages.PackageImportResult ImportPackageFromFile(string sessionId, string packageDataPath, Agility.Sdk.Model.SpaPackages.SpaPackageImportOptions3 importOptions) => throw null;
        public byte[] ExportPackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) => throw null;
        public byte[] ExportPackageToBytes(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) => throw null;
        public byte[] ExportPackageToBytes2(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity, Agility.Sdk.Model.SpaPackages.PackageDeploymentIdentity deploymentIdentity) => throw null;
        public void ExportPackageToFile(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity, string fileLocationToSave) { }
        public void ExportPackageToFile2(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity, Agility.Sdk.Model.SpaPackages.PackageDeploymentIdentity deploymentIdentity, string fileLocationToSave) { }
        public Agility.Sdk.Model.SpaPackages.SpaPackageData GetPackageDataForAssociations(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageItemCollection spaPackageItems) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageData GetPackageDataForAssociations2(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageItemCollection spaPackageItems, Agility.Sdk.Model.SpaPackages.ItemAssociationsOptions itemAssociations) => throw null;
        public Agility.Sdk.Model.SpaPackages.SpaPackageData SearchPackageArtifacts(string sessionId, Agility.Sdk.Model.SpaPackages.PackageArtifactFilter packageArtifactFilter) => throw null;
        public Agility.Sdk.Model.Resources.ResourceIdentityCollection GetRoleMembers(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageItemCollection spaPackageItemCollection) => throw null;
        public Agility.Sdk.Model.SpaPackages.PackageDeploymentItems GetDeploymentItemsForPackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageItemCollection spaPackageItems, bool includeDeviceSettings) => throw null;
        public Agility.Sdk.Model.SpaPackages.PackageDeploymentIdentityCollection GetPackageDeployments(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackageIdentity packageIdentity) => throw null;
    }
}
