// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class ClientService
    {
        public ClientService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Client.ClientSession LogOnWithPassword(Agility.Sdk.Model.Client.ClientIdentity clientIdentity) => throw null;
        public Agility.Sdk.Model.Client.ClientSession LogOnUsingWindowsAuthentication(Agility.Sdk.Model.Client.ClientIdentity clientIdentity) => throw null;
        public void LogOff(string sessionId) { }
        public Agility.Sdk.Model.Client.ModuleInfoCollection GetModules(string sessionId, short clientPlatform) => throw null;
        public Agility.Sdk.Model.Client.ModuleInfoCollection GetModulesForPersona(string sessionId, short clientPlatform, Agility.Sdk.Model.Client.PersonaInfo personaInfo) => throw null;
        public string GetBrowserLanguage() => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection GetDocumentTypes(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity docGroup) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeSummary3Collection GetDocumentTypes3(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity docGroup) => throw null;
        public Agility.Sdk.Model.Capture.FieldGroupIdentityCollection GetFieldGroups(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity docType) => throw null;
        public Agility.Sdk.Model.Capture.FieldIdentityCollection GetFields(string sessionId, Agility.Sdk.Model.Capture.FieldGroupIdentity fieldGroup) => throw null;
        public Agility.Sdk.Model.Resources.ResourceTreeData GetResourceTreeData(string sessionId, Agility.Sdk.Model.Resources.ResourceTreeFilter resourceTreeFilter) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeSummary2Collection GetDocumentTypes2(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection documentTypes) => throw null;
        public Agility.Sdk.Model.Capture.FolderTypeSummary2Collection GetFolderTypes(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentityCollection folderTypes) => throw null;
        public Agility.Sdk.Model.Processes.ProcessWithData GetProcess(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Processes.ProcessWithData GetProcess2(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity, bool updateRecentItems) => throw null;
        public Agility.Sdk.Model.QuickApps.QuickAppWithSupportingData GetQuickApp(string sessionId, Agility.Sdk.Model.QuickApps.QuickAppIdentity identity) => throw null;
        public Agility.Sdk.Model.Forms.Form GetForm(string sessionId, Agility.Sdk.Model.Forms.FormIdentity formIdentity) => throw null;
        public Agility.Sdk.Model.Client.ClientSession2 LogOnWithPassword2(Agility.Sdk.Model.Client.ClientIdentity clientIdentity) => throw null;
        public Agility.Sdk.Model.Client.ClientSession3 LogOnWithPassword3(Agility.Sdk.Model.Users.UserIdentityWithPassword userIdentityWithPassword, bool checkForSecureSession) => throw null;
        public bool IsAzure() => throw null;
        public bool IsMultitenantDeployment() => throw null;
        public string GetCCMServerLocation(string sessionId) => throw null;
        public Agility.Sdk.Model.Client.ClientSession2 LogOnUsingWindowsAuthentication2(Agility.Sdk.Model.Client.ClientIdentity clientIdentity) => throw null;
        public Agility.Sdk.Model.Client.ClientSession3 LogOnUsingWindowsAuthentication3(short logOnProtocol, bool unconditionalLogOn, bool checkForSecureSession) => throw null;
        public Agility.Sdk.Model.Processes.ProcessExtraData GetProcessExtraData(string sessionId, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public Agility.Sdk.Model.Localization.LocaleInfo GetLocaleInfo(string language) => throw null;
        public Agility.Sdk.Model.Client.TDCompatibility GetTDCompatibility() => throw null;
        public int GetMaxCaptureProjectSize(string sessionId) => throw null;
        public void SaveAndExportPackage(string sessionId, Agility.Sdk.Model.SpaPackages.SpaPackage packageInfo) { }
        public Agility.Sdk.Model.Client.ClientSession3 ValidateSession(string sessionId, short logOnProtocol, Agility.Sdk.Model.Client.ClientIdentity clientIdentity) => throw null;
        public string GetHelpURL() => throw null;
        public Agility.Sdk.Model.Capture.PdfGeneration.PdfGenerationProfileIdentityCollection GetPdfProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileIdentityCollection GetScanVrsProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.Separation.SeparationProfileIdentityCollection GetSeparationProfiles(string sessionId) => throw null;
        public Agility.Sdk.Model.JobSchedulers.JobScheduleSummaryCollection GetJobSchedules(string sessionId, Agility.Sdk.Model.JobSchedulers.JobScheduleFilter jobScheduleFilter) => throw null;
    }
}
