// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocumentSetService
    {
        public DocumentSetService(System.ServiceModel.Channels.Binding binding) { }
        public void AddDocument(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentIdentity2 documentIdentity, bool useSource, string source, bool useStatus, short status) { }
        public void AddDocuments(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentIdentity2Collection documentIdentityCollection, Agility.Sdk.Model.Capture.FolderIdentity folderIdentity, bool useSource, string source, bool useStatus, short status) { }
        public void UpdateDocumentStatus(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentIdentity2Collection documentIdentityCollection, Agility.Sdk.Model.Capture.FolderIdentity folderIdentity, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, short status) { }
        public bool EvaluateDocumentRule(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Jobs.JobDocumentTypeRuleResultCollection EvaluateDocumentSet(string sessionId, Agility.Sdk.Model.Jobs.JobIdentity jobIdentity, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseIdentity) => throw null;
    }
}
