// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class DocumentGenerationService
    {
        public DocumentGenerationService(System.ServiceModel.Channels.Binding binding) { }
        public string CreateDocument(string sessionId, string templatePath, string outFilePath, string outFileName, bool overwrite, Agility.Sdk.Model.Document.DocumentFieldCollection docFields, short documentType) => throw null;
        public Agility.Sdk.Model.Document.DocumentFieldCollection GetDocumentPlaceholdersList(string sessionId, Agility.Sdk.Model.Document.DocumentTemplateInfo template) => throw null;
        public Agility.Sdk.Model.Document.CreateDocumentResult CreateDocument2(string sessionId, Agility.Sdk.Model.Document.CreateDocumentInfo createDocumentInfo) => throw null;
        public Agility.Sdk.Model.Document.CreateDocumentResult CreateDocument3(string sessionId, Agility.Sdk.Model.Document.CreateDocumentInfo2 createDocumentInfo) => throw null;
        public Agility.Sdk.Model.Document.DocumentFieldCollection GetDocumentPlaceholdersList2(string sessionId, Agility.Sdk.Model.Document.DocumentTemplateInfo2 documentTemplateInfo) => throw null;
    }
}
