// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class LinkedServerService
    {
        public LinkedServerService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.LinkedServers.LinkedServerIdentity AddLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServer linkedServer) => throw null;
        public Agility.Sdk.Model.LinkedServers.LinkedServerIdentityCollection GetLinkedServers(string sessionId) => throw null;
        public void UpdateLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServer linkedServer) { }
        public void DeleteLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity) { }
        public Agility.Sdk.Model.LinkedServers.LinkedServer GetLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity) => throw null;
        public Agility.Sdk.Model.Categories.CategorySummaryCollection GetCategoriesForLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity, Agility.Sdk.Model.Categories.CategoryFilter categoryFilter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessSummaryCollection GetProcessesForLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity, Agility.Sdk.Model.Processes.ProcessFilter filter) => throw null;
        public Agility.Sdk.Model.Processes.ProcessInitialization GetProcessInitializationForLinkedServer(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity, Agility.Sdk.Model.Processes.ProcessIdentity processIdentity) => throw null;
        public string ExecuteTransferActivity(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity, string folderId, string documentId, Agility.Sdk.Model.Processes.ProcessIdentity documentsReceivedProcess, short jobType, Agility.Sdk.Model.CaseProcesses.CaseIdentity caseJobIdentity, Agility.Sdk.Model.Processes.ProcessInitialization documentsReceivedProcessInputs, bool failOnError, string transferBatchId) => throw null;
        public void SendReportingData(string sessionId, string functionName, byte[] data, bool isCompressed) { }
        public Agility.Sdk.Model.Processes.ProcessType GetLinkedServerProcessType(string sessionId, Agility.Sdk.Model.LinkedServers.LinkedServerIdentity linkedServerIdentity, string processId) => throw null;
    }
}
