// <auto-generated/>
// Target Frameworks: net48

namespace TotalAgility.Sdk
{
    public class CaptureConfigurationService
    {
        public CaptureConfigurationService(System.ServiceModel.Channels.Binding binding) { }
        public Agility.Sdk.Model.Capture.DocumentTypeXmlCollection GetDocumentTypesAsXml(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentTypeCollection GetDocumentTypes(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentType GetDocumentType(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public string GetDocumentTypeAsXml(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public void SaveFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderType folderType, short status) { }
        public void LockFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) { }
        public void UnlockFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) { }
        public void ForceUnlockFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) { }
        public void DeleteFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity, bool deletePreviousVersions) { }
        public Agility.Sdk.Model.Capture.FolderTypeSummaryCollection GetFolderTypes(string sessionId, Agility.Sdk.Model.Capture.FolderTypeFilter folderTypeFilter) => throw null;
        public Agility.Sdk.Model.Capture.VersionCollection GetFolderTypeVersions(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.FolderType GetFolderType(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.FolderType GetFolderTypeConfiguration(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public string GetFolderTypeAsXml(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity) => throw null;
        public void SaveDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroup documentGroup, short status) { }
        public void LockDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) { }
        public void UnlockDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) { }
        public void ForceUnlockDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) { }
        public void DeleteDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity, bool deletePreviousVersions) { }
        public Agility.Sdk.Model.Capture.DocumentGroupSummaryCollection GetDocumentGroups(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupFilter documentGroupFilter) => throw null;
        public Agility.Sdk.Model.Capture.VersionCollection GetDocumentGroupVersions(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentGroupAssociations GetDocumentGroupAssociations(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity, short documentGroupAssociationsFilter) => throw null;
        public Agility.Sdk.Model.Capture.DocumentGroup GetDocumentGroup(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.DocumentGroup GetDocumentGroupConfiguration(string sessionId, Agility.Sdk.Model.Capture.DocumentGroupIdentity documentGroupIdentity) => throw null;
        public void SaveClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroup classificationGroup, short status) { }
        public void LockClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) { }
        public void UnlockClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) { }
        public void ForceUnlockClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) { }
        public void DeleteClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity, bool deletePreviousVersions) { }
        public Agility.Sdk.Model.Capture.ClassificationGroupSummaryCollection GetClassificationGroups(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupFilter classificationGroupFilter) => throw null;
        public Agility.Sdk.Model.Capture.VersionCollection GetClassificationGroupVersions(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.ClassificationGroup GetClassificationGroup(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.FieldGroupSummaryCollection GetDocumentTypeFieldGroups(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentType) => throw null;
        public Agility.Sdk.Model.Capture.FieldSummaryCollection GetDocumentTypeFields(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentType, Agility.Sdk.Model.Capture.FieldGroupIdentity fieldGroup) => throw null;
        public Agility.Sdk.Model.Capture.FieldGroupSummaryCollection GetFolderTypeFieldGroups(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderType) => throw null;
        public Agility.Sdk.Model.Capture.FieldSummaryCollection GetFolderTypeFields(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderType, Agility.Sdk.Model.Capture.FieldGroupIdentity fieldGroup) => throw null;
        public Agility.Sdk.Model.Capture.DocumentGroupIdentity GetDocumentGroupIdentity(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity) => throw null;
        public Agility.Sdk.Model.Capture.FieldAttributeCollection GetDocumentTypeFieldAttributes(string sessionId) => throw null;
        public Agility.Sdk.Model.Capture.FieldAttributeCollection GetFolderTypeFieldAttributes(string sessionId) => throw null;
        public bool IsScanVrsProfileInUse(string sessionId, Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileIdentity scanVrsProfile) => throw null;
        public Agility.Sdk.Model.Capture.Scanning.ScanVrsProfile GetScanVrsProfile(string sessionId, Agility.Sdk.Model.Capture.Scanning.ScanVrsProfileIdentity profileIdentity) => throw null;
        public bool IsSeparationProfileInUse(string sessionId, Agility.Sdk.Model.Capture.Separation.SeparationProfileIdentity separationProfile) => throw null;
        public bool IsPdfGenerationProfileInUse(string sessionId, Agility.Sdk.Model.Capture.PdfGeneration.PdfGenerationProfileIdentity pdfGenerationProfile) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FormatterIdentity AddFieldFormatter(string sessionId, Agility.Sdk.Model.Capture.Formatting.FieldFormatter fieldFormatter) => throw null;
        public Agility.Sdk.Model.Capture.Formatting.FieldFormatter GetFieldFormatter(string sessionId, Agility.Sdk.Model.Capture.Formatting.FormatterIdentity formatterIdentity) => throw null;
        public void UpdateFieldFormatter(string sessionId, Agility.Sdk.Model.Capture.Formatting.FieldFormatter fieldFormatter, bool overwrite) { }
        public void DeleteFieldFormatter(string sessionId, Agility.Sdk.Model.Capture.Formatting.FormatterIdentity formatterIdentity) { }
        public Agility.Sdk.Model.Capture.Formatting.FormatterSummaryCollection GetFieldFormatters(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity category) => throw null;
        public Agility.Sdk.Model.Capture.DocumentGroupIdentityCollection GetDocumentGroupsWithOnlineLearningEnabled(string sessionId) => throw null;
        public byte[] GetNewSamples(string sessionId, string onlineLearningFolderId) => throw null;
        public byte[] GetNewSampleChunk(string sessionId, string onlineLearningFolderId, bool restart, int maxSize, int maxDocs) => throw null;
        public int AvailableNewSamples(string sessionId, string onlineLearningFolderId) => throw null;
        public int ResetNewSamples(string sessionId, string onlineLearningFolderId) => throw null;
        public int DeleteDownloadedNewSamples(string sessionId, string onlineLearningFolderId) => throw null;
        public Agility.Sdk.Model.Forms.Events.FuzzyDatabaseCollection GetFuzzyDatabasesForDocumentType(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentType) => throw null;
        public Agility.Sdk.Model.Forms.Events.FuzzyDatabase GetFuzzyDatabaseForDocumentType(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentType, Agility.Sdk.Model.Forms.Events.FuzzyDatabaseIdentity fuzzyDatabase) => throw null;
        public void UpdateDocumentTypeForms(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity documentTypeIdentity, Agility.Sdk.Model.Capture.CaptureForms forms, bool checkAllLocks) { }
        public void UpdateFolderTypeForms(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity, Agility.Sdk.Model.Capture.CaptureForms forms, bool checkAllLocks) { }
        public void UpdateMaxNewSamples(string sessionId, string onlineLearningFolderId, int maxNewSamples) { }
        public Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection GetChildDocumentTypeIdentities(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentity parentDocumentType) => throw null;
        public Agility.Sdk.Model.Capture.CaptureConfigurationItems GetCaptureConfigurationItems(string sessionId, Agility.Sdk.Model.Capture.DocumentTypeIdentityCollection documentTypeIdentityCollection, Agility.Sdk.Model.Capture.FolderTypeIdentityCollection folderTypeIdentityCollection) => throw null;
        public Agility.Sdk.Model.Capture.FolderTypeAssociations GetFolderTypeAssociations(string sessionId, Agility.Sdk.Model.Capture.FolderTypeIdentity folderTypeIdentity, short folderTypeAssociationsFilter) => throw null;
        public Agility.Sdk.Model.Capture.ClassificationGroupAssociations GetClassificationGroupAssociations(string sessionId, Agility.Sdk.Model.Capture.ClassificationGroupIdentity classificationGroupIdentity) => throw null;
        public Agility.Sdk.Model.Capture.Validation.ValidatorIdentity AddFieldValidator(string sessionId, Agility.Sdk.Model.Capture.Validation.GlobalFieldValidator fieldValidator) => throw null;
        public Agility.Sdk.Model.Capture.Validation.GlobalFieldValidator GetFieldValidator(string sessionId, Agility.Sdk.Model.Capture.Validation.ValidatorIdentity validatorIdentity) => throw null;
        public void UpdateFieldValidator(string sessionId, Agility.Sdk.Model.Capture.Validation.GlobalFieldValidator fieldValidator, bool overwrite) { }
        public void DeleteFieldValidator(string sessionId, Agility.Sdk.Model.Capture.Validation.ValidatorIdentity validatorIdentity) { }
        public Agility.Sdk.Model.Capture.Validation.ValidatorSummaryCollection GetFieldValidators(string sessionId, Agility.Sdk.Model.Categories.CategoryIdentity categoryIdentity, Agility.Sdk.Model.Capture.Validation.ValidatorIdentityCollection specificValidators) => throw null;
    }
}
